import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";
import "dotenv/config";

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: {
    rejectUnauthorized: false,
  },
});
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

// US States with regions
const states = [
  { code: "AL", name: "Alabama", region: "Southeast" },
  { code: "AK", name: "Alaska", region: "West" },
  { code: "AZ", name: "Arizona", region: "Southwest" },
  { code: "AR", name: "Arkansas", region: "South" },
  { code: "CA", name: "California", region: "West" },
  { code: "CO", name: "Colorado", region: "Mountain" },
  { code: "CT", name: "Connecticut", region: "Northeast" },
  { code: "DE", name: "Delaware", region: "Northeast" },
  { code: "FL", name: "Florida", region: "Southeast" },
  { code: "GA", name: "Georgia", region: "Southeast" },
  { code: "HI", name: "Hawaii", region: "West" },
  { code: "ID", name: "Idaho", region: "Mountain" },
  { code: "IL", name: "Illinois", region: "Midwest" },
  { code: "IN", name: "Indiana", region: "Midwest" },
  { code: "IA", name: "Iowa", region: "Midwest" },
  { code: "KS", name: "Kansas", region: "Midwest" },
  { code: "KY", name: "Kentucky", region: "Southeast" },
  { code: "LA", name: "Louisiana", region: "South" },
  { code: "ME", name: "Maine", region: "Northeast" },
  { code: "MD", name: "Maryland", region: "Northeast" },
  { code: "MA", name: "Massachusetts", region: "Northeast" },
  { code: "MI", name: "Michigan", region: "Midwest" },
  { code: "MN", name: "Minnesota", region: "Midwest" },
  { code: "MS", name: "Mississippi", region: "South" },
  { code: "MO", name: "Missouri", region: "Midwest" },
  { code: "MT", name: "Montana", region: "Mountain" },
  { code: "NE", name: "Nebraska", region: "Midwest" },
  { code: "NV", name: "Nevada", region: "West" },
  { code: "NH", name: "New Hampshire", region: "Northeast" },
  { code: "NJ", name: "New Jersey", region: "Northeast" },
  { code: "NM", name: "New Mexico", region: "Southwest" },
  { code: "NY", name: "New York", region: "Northeast" },
  { code: "NC", name: "North Carolina", region: "Southeast" },
  { code: "ND", name: "North Dakota", region: "Midwest" },
  { code: "OH", name: "Ohio", region: "Midwest" },
  { code: "OK", name: "Oklahoma", region: "South" },
  { code: "OR", name: "Oregon", region: "West" },
  { code: "PA", name: "Pennsylvania", region: "Northeast" },
  { code: "RI", name: "Rhode Island", region: "Northeast" },
  { code: "SC", name: "South Carolina", region: "Southeast" },
  { code: "SD", name: "South Dakota", region: "Midwest" },
  { code: "TN", name: "Tennessee", region: "Southeast" },
  { code: "TX", name: "Texas", region: "South" },
  { code: "UT", name: "Utah", region: "Mountain" },
  { code: "VT", name: "Vermont", region: "Northeast" },
  { code: "VA", name: "Virginia", region: "Southeast" },
  { code: "WA", name: "Washington", region: "West" },
  { code: "WV", name: "West Virginia", region: "Southeast" },
  { code: "WI", name: "Wisconsin", region: "Midwest" },
  { code: "WY", name: "Wyoming", region: "Mountain" },
];

// National/Federal Grants (available to all states)
const federalGrants = [
  {
    title: "SBIR Phase I - Advanced AI for Healthcare Diagnostics",
    funder: "National Institutes of Health (NIH)",
    description: "Funding for small businesses to develop innovative AI-powered diagnostic tools that can improve early detection of diseases. Projects should demonstrate technical feasibility and commercial potential.",
    amount: "$275,000",
    amountMin: 250000,
    amountMax: 300000,
    deadline: new Date("2025-04-15"),
    url: "https://grants.nih.gov/grants/guide/pa-files/PA-24-001.html",
    type: "federal",
    category: "sbir",
    eligibility: "Small businesses with fewer than 500 employees. Must be US-based and for-profit.",
    requirements: "Principal investigator must be employed by the small business. Must demonstrate technical innovation and commercial viability.",
    state: "ALL",
    region: "National",
    contactName: "NIH SBIR/STTR Program",
    contactEmail: "sbir@nih.gov",
    contactPhone: "301-435-2688",
    agencyName: "National Institutes of Health",
    tags: '["healthcare", "AI", "diagnostics", "medical devices", "research"]',
    matchScore: 92,
    source: "grants.gov",
  },
  {
    title: "STTR Phase II - Clean Energy Technology Development",
    funder: "Department of Energy (DOE)",
    description: "Continuation funding for promising clean energy technologies that have completed Phase I. Focus areas include solar, wind, battery storage, and grid modernization.",
    amount: "$1,000,000 - $1,500,000",
    amountMin: 1000000,
    amountMax: 1500000,
    deadline: new Date("2025-03-01"),
    url: "https://science.osti.gov/sbir/Funding-Opportunities",
    type: "federal",
    category: "sttr",
    eligibility: "Must have successfully completed STTR Phase I. Partnership with research institution required.",
    requirements: "40% of work must be performed by small business, 30% by research institution. Detailed commercialization plan required.",
    state: "ALL",
    region: "National",
    contactName: "DOE SBIR/STTR Office",
    contactEmail: "sc.sbir-sttr@science.doe.gov",
    contactPhone: "301-903-1414",
    agencyName: "Department of Energy",
    tags: '["clean energy", "solar", "wind", "battery", "sustainability"]',
    matchScore: 78,
    source: "grants.gov",
  },
  {
    title: "NSF SBIR Phase I - Deep Technology Ventures",
    funder: "National Science Foundation (NSF)",
    description: "Seed funding for startups developing deep technology innovations across all NSF research areas including AI/ML, quantum computing, advanced materials, and biotechnology.",
    amount: "$275,000",
    amountMin: 275000,
    amountMax: 275000,
    deadline: new Date("2025-06-05"),
    url: "https://seedfund.nsf.gov/",
    type: "federal",
    category: "sbir",
    eligibility: "US small businesses. Women-owned and minority-owned businesses encouraged to apply.",
    requirements: "Must propose innovative technology with strong intellectual merit and broader impacts. No preliminary data required.",
    state: "ALL",
    region: "National",
    contactName: "NSF SBIR Program",
    contactEmail: "sbir@nsf.gov",
    contactPhone: "703-292-8050",
    agencyName: "National Science Foundation",
    tags: '["deep tech", "AI", "quantum", "biotech", "innovation"]',
    matchScore: 88,
    source: "nsf.gov",
  },
  {
    title: "USDA Small Business Innovation Research",
    funder: "U.S. Department of Agriculture",
    description: "Funding for agricultural technology innovation including precision agriculture, sustainable farming, food safety, and rural development technologies.",
    amount: "$100,000 - $650,000",
    amountMin: 100000,
    amountMax: 650000,
    deadline: new Date("2025-04-02"),
    url: "https://www.nifa.usda.gov/grants/programs/small-business-innovation-research-program-sbir",
    type: "federal",
    category: "sbir",
    eligibility: "US small businesses in agricultural technology sector.",
    requirements: "Must address USDA research priorities. Environmental sustainability focus preferred.",
    state: "ALL",
    region: "National",
    contactName: "USDA SBIR Program",
    contactEmail: "sbir@usda.gov",
    contactPhone: "202-401-4002",
    agencyName: "U.S. Department of Agriculture",
    tags: '["agriculture", "farming", "food tech", "rural", "sustainability"]',
    matchScore: 55,
    source: "grants.gov",
  },
  {
    title: "ARPA-E OPEN Program",
    funder: "Advanced Research Projects Agency-Energy",
    description: "Funding for high-risk, high-reward energy technology research. Open to transformational ideas across all energy technology areas.",
    amount: "$500,000 - $10,000,000",
    amountMin: 500000,
    amountMax: 10000000,
    deadline: new Date("2025-05-15"),
    url: "https://arpa-e.energy.gov/",
    type: "federal",
    category: "research",
    eligibility: "Universities, national labs, small businesses, and large companies.",
    requirements: "Must demonstrate transformational potential. Technical and commercialization milestones required.",
    state: "ALL",
    region: "National",
    contactName: "ARPA-E Program Office",
    contactEmail: "ARPA-E-CO@hq.doe.gov",
    contactPhone: "202-287-1000",
    agencyName: "ARPA-E",
    tags: '["energy", "transformational", "research", "innovation"]',
    matchScore: 68,
    source: "grants.gov",
  },
  {
    title: "Economic Development Administration - Build to Scale",
    funder: "U.S. Economic Development Administration",
    description: "Funding to build regional economies through scalable startups. Supports accelerators, incubators, and innovation ecosystems.",
    amount: "$750,000 - $2,000,000",
    amountMin: 750000,
    amountMax: 2000000,
    deadline: new Date("2025-06-30"),
    url: "https://www.eda.gov/funding/programs/build-to-scale",
    type: "federal",
    category: "economic_development",
    eligibility: "Economic development organizations, universities, nonprofits.",
    requirements: "Must demonstrate regional economic impact and job creation potential.",
    state: "ALL",
    region: "National",
    contactName: "EDA Build to Scale Program",
    contactEmail: "BuildtoScale@eda.gov",
    contactPhone: "202-482-2659",
    agencyName: "Economic Development Administration",
    tags: '["economic development", "accelerator", "incubator", "startups"]',
    matchScore: 75,
    source: "grants.gov",
  },
];

// Foundation Grants (national) - Expanded with more private foundations
const foundationGrants = [
  {
    title: "Social Innovation Fund",
    funder: "Bill & Melinda Gates Foundation",
    description: "Supporting innovative solutions to global health and development challenges. Priority areas include infectious disease prevention, maternal health, and digital health solutions.",
    amount: "$500,000 - $2,000,000",
    amountMin: 500000,
    amountMax: 2000000,
    deadline: new Date("2025-05-30"),
    url: "https://www.gatesfoundation.org/about/how-we-work/grants",
    type: "foundation",
    category: "health",
    eligibility: "Nonprofits and social enterprises with proven track record. Must demonstrate measurable impact.",
    requirements: "Letter of inquiry required before full application. Must align with foundation's strategic priorities.",
    state: "ALL",
    region: "National",
    contactName: "Gates Foundation Grants",
    contactEmail: "grants@gatesfoundation.org",
    agencyName: "Bill & Melinda Gates Foundation",
    tags: '["health", "global development", "innovation", "social impact"]',
    matchScore: 65,
    source: "foundation_directory",
  },
  {
    title: "Climate Solutions Accelerator Grant",
    funder: "Bloomberg Philanthropies",
    description: "Funding for organizations developing scalable solutions to climate change. Focus on clean energy transition, sustainable cities, and climate resilience.",
    amount: "$250,000 - $750,000",
    amountMin: 250000,
    amountMax: 750000,
    deadline: new Date("2025-04-01"),
    url: "https://www.bloomberg.org/environment/",
    type: "foundation",
    category: "environment",
    eligibility: "501(c)(3) nonprofits and B-Corps. International organizations eligible with US fiscal sponsor.",
    requirements: "Must demonstrate clear pathway to emissions reduction. Data-driven approach required.",
    state: "ALL",
    region: "National",
    contactName: "Bloomberg Environment Program",
    contactEmail: "environment@bloomberg.org",
    agencyName: "Bloomberg Philanthropies",
    tags: '["climate", "environment", "sustainability", "clean energy"]',
    matchScore: 71,
    source: "foundation_directory",
  },
  {
    title: "Startup Community Development Grant",
    funder: "Kauffman Foundation",
    description: "Supporting organizations that strengthen entrepreneurial ecosystems. Funding for accelerators, incubators, and programs that support underrepresented founders.",
    amount: "$100,000 - $500,000",
    amountMin: 100000,
    amountMax: 500000,
    deadline: new Date("2025-07-15"),
    url: "https://www.kauffman.org/grants/",
    type: "foundation",
    category: "entrepreneurship",
    eligibility: "Nonprofits supporting entrepreneurship. Must serve diverse founder populations.",
    requirements: "Must demonstrate community engagement and sustainable program model.",
    state: "ALL",
    region: "National",
    contactName: "Kauffman Foundation Grants",
    contactEmail: "grants@kauffman.org",
    contactPhone: "816-932-1000",
    agencyName: "Kauffman Foundation",
    tags: '["entrepreneurship", "startups", "diversity", "ecosystem"]',
    matchScore: 82,
    source: "foundation_directory",
  },
  {
    title: "Tech for Social Good Initiative",
    funder: "Ford Foundation",
    description: "Supporting technology projects that advance social justice and reduce inequality. Focus on digital rights, civic tech, and technology access.",
    amount: "$150,000 - $500,000",
    amountMin: 150000,
    amountMax: 500000,
    deadline: new Date("2025-08-31"),
    url: "https://www.fordfoundation.org/work/our-grants/",
    type: "foundation",
    category: "technology",
    eligibility: "501(c)(3) nonprofits working on technology and social justice.",
    requirements: "Must demonstrate commitment to equity and inclusion.",
    state: "ALL",
    region: "National",
    contactName: "Ford Foundation Grants",
    contactEmail: "grants@fordfoundation.org",
    agencyName: "Ford Foundation",
    tags: '["social justice", "technology", "civic tech", "equity"]',
    matchScore: 60,
    source: "foundation_directory",
  },
  // NEW PRIVATE FOUNDATION GRANTS
  {
    title: "Bezos Earth Fund Climate Innovation Grant",
    funder: "Bezos Earth Fund",
    description: "Large-scale funding for transformative climate and nature solutions. Focus areas include decarbonization, nature conservation, and environmental justice.",
    amount: "$1,000,000 - $50,000,000",
    amountMin: 1000000,
    amountMax: 50000000,
    deadline: new Date("2025-06-15"),
    url: "https://www.bezosearthfund.org/",
    type: "foundation",
    category: "environment",
    eligibility: "Nonprofits, research institutions, and innovative companies working on climate solutions.",
    requirements: "Must demonstrate potential for transformative impact at scale. Strong scientific basis required.",
    state: "ALL",
    region: "National",
    contactName: "Bezos Earth Fund",
    contactEmail: "grants@bezosearthfund.org",
    agencyName: "Bezos Earth Fund",
    tags: '["climate", "environment", "conservation", "decarbonization", "nature"]',
    matchScore: 75,
    source: "foundation_directory",
  },
  {
    title: "Chan Zuckerberg Initiative Science Grant",
    funder: "Chan Zuckerberg Initiative",
    description: "Funding for breakthrough science research with focus on curing, preventing, or managing all diseases by the end of the century.",
    amount: "$500,000 - $5,000,000",
    amountMin: 500000,
    amountMax: 5000000,
    deadline: new Date("2025-04-30"),
    url: "https://chanzuckerberg.com/science/",
    type: "foundation",
    category: "research",
    eligibility: "Research institutions, universities, and biotech companies.",
    requirements: "Must propose novel approaches to understanding disease. Open science principles encouraged.",
    state: "ALL",
    region: "National",
    contactName: "CZI Science Program",
    contactEmail: "science@chanzuckerberg.com",
    agencyName: "Chan Zuckerberg Initiative",
    tags: '["science", "research", "biotech", "health", "disease"]',
    matchScore: 70,
    source: "foundation_directory",
  },
  {
    title: "Walton Family Foundation Environment Program",
    funder: "Walton Family Foundation",
    description: "Supporting freshwater conservation, ocean health, and sustainable food systems. Focus on market-based conservation solutions.",
    amount: "$100,000 - $2,000,000",
    amountMin: 100000,
    amountMax: 2000000,
    deadline: new Date("2025-05-01"),
    url: "https://www.waltonfamilyfoundation.org/environment",
    type: "foundation",
    category: "environment",
    eligibility: "Nonprofits working on freshwater, ocean, or food system conservation.",
    requirements: "Must demonstrate measurable conservation outcomes and community engagement.",
    state: "ALL",
    region: "National",
    contactName: "Walton Environment Program",
    contactEmail: "environment@wffmail.com",
    agencyName: "Walton Family Foundation",
    tags: '["environment", "conservation", "freshwater", "ocean", "food systems"]',
    matchScore: 68,
    source: "foundation_directory",
  },
  {
    title: "MacArthur Foundation Big Bets Grant",
    funder: "John D. and Catherine T. MacArthur Foundation",
    description: "Large-scale grants for ambitious solutions to critical social challenges. Current focus areas include climate solutions, nuclear risk reduction, and criminal justice reform.",
    amount: "$500,000 - $10,000,000",
    amountMin: 500000,
    amountMax: 10000000,
    deadline: new Date("2025-07-01"),
    url: "https://www.macfound.org/programs/",
    type: "foundation",
    category: "research",
    eligibility: "Organizations with bold, evidence-based approaches to systemic problems.",
    requirements: "Must demonstrate potential for field-wide impact. Multi-year commitment expected.",
    state: "ALL",
    region: "National",
    contactName: "MacArthur Grants Office",
    contactEmail: "4answers@macfound.org",
    agencyName: "MacArthur Foundation",
    tags: '["social change", "climate", "justice", "nuclear", "systemic change"]',
    matchScore: 62,
    source: "foundation_directory",
  },
  {
    title: "Rockefeller Foundation Innovation Grant",
    funder: "Rockefeller Foundation",
    description: "Funding for innovative solutions to global challenges including health equity, food systems, and economic opportunity.",
    amount: "$250,000 - $3,000,000",
    amountMin: 250000,
    amountMax: 3000000,
    deadline: new Date("2025-08-15"),
    url: "https://www.rockefellerfoundation.org/grants/",
    type: "foundation",
    category: "health",
    eligibility: "Nonprofits, social enterprises, and research institutions.",
    requirements: "Must align with foundation priorities. Strong evaluation framework required.",
    state: "ALL",
    region: "National",
    contactName: "Rockefeller Foundation Grants",
    contactEmail: "grants@rockfound.org",
    agencyName: "Rockefeller Foundation",
    tags: '["health", "food", "economic opportunity", "innovation", "equity"]',
    matchScore: 66,
    source: "foundation_directory",
  },
  {
    title: "Skoll Foundation Social Entrepreneurship Award",
    funder: "Skoll Foundation",
    description: "Recognizing and supporting social entrepreneurs driving large-scale change. Multi-year unrestricted funding for proven social innovators.",
    amount: "$1,000,000 - $1,500,000",
    amountMin: 1000000,
    amountMax: 1500000,
    deadline: new Date("2025-03-15"),
    url: "https://skoll.org/",
    type: "foundation",
    category: "entrepreneurship",
    eligibility: "Social entrepreneurs with proven track record of systemic change.",
    requirements: "Must demonstrate sustainable model and significant social impact achieved.",
    state: "ALL",
    region: "National",
    contactName: "Skoll Foundation",
    contactEmail: "info@skoll.org",
    agencyName: "Skoll Foundation",
    tags: '["social entrepreneurship", "social enterprise", "impact", "innovation"]',
    matchScore: 78,
    source: "foundation_directory",
  },
  {
    title: "Omidyar Network Emerging Tech Fund",
    funder: "Omidyar Network",
    description: "Investing in responsible technology that promotes individual agency and social benefit. Focus on AI ethics, digital identity, and platform accountability.",
    amount: "$250,000 - $2,000,000",
    amountMin: 250000,
    amountMax: 2000000,
    deadline: new Date("2025-09-01"),
    url: "https://omidyar.com/",
    type: "foundation",
    category: "technology",
    eligibility: "Nonprofits, research institutions, and mission-driven companies.",
    requirements: "Must address responsible technology development or tech accountability.",
    state: "ALL",
    region: "National",
    contactName: "Omidyar Network",
    contactEmail: "info@omidyar.com",
    agencyName: "Omidyar Network",
    tags: '["technology", "AI", "ethics", "digital rights", "responsible tech"]',
    matchScore: 74,
    source: "foundation_directory",
  },
  {
    title: "Arnold Ventures Evidence-Based Policy Grant",
    funder: "Arnold Ventures",
    description: "Supporting rigorous research and evidence-based policy solutions. Focus areas include criminal justice, education, health, and public finance.",
    amount: "$100,000 - $5,000,000",
    amountMin: 100000,
    amountMax: 5000000,
    deadline: new Date("2025-06-30"),
    url: "https://www.arnoldventures.org/",
    type: "foundation",
    category: "research",
    eligibility: "Research institutions and policy organizations.",
    requirements: "Must propose rigorous evaluation methodology. Policy relevance required.",
    state: "ALL",
    region: "National",
    contactName: "Arnold Ventures Grants",
    contactEmail: "info@arnoldventures.org",
    agencyName: "Arnold Ventures",
    tags: '["research", "policy", "evidence-based", "criminal justice", "education"]',
    matchScore: 58,
    source: "foundation_directory",
  },
  {
    title: "Emerson Collective Social Impact Grant",
    funder: "Emerson Collective",
    description: "Supporting innovative organizations working on education, immigration, environment, and health equity.",
    amount: "$100,000 - $1,000,000",
    amountMin: 100000,
    amountMax: 1000000,
    deadline: new Date("2025-05-15"),
    url: "https://www.emersoncollective.com/",
    type: "foundation",
    category: "health",
    eligibility: "Nonprofits and social enterprises with innovative approaches.",
    requirements: "Must demonstrate measurable impact and scalable model.",
    state: "ALL",
    region: "National",
    contactName: "Emerson Collective",
    contactEmail: "hello@emersoncollective.com",
    agencyName: "Emerson Collective",
    tags: '["education", "immigration", "environment", "health equity", "social impact"]',
    matchScore: 72,
    source: "foundation_directory",
  },
  {
    title: "Schmidt Futures Technology Innovation Grant",
    funder: "Schmidt Futures",
    description: "Betting on people and ideas that could create breakthroughs. Focus on AI, science, and technology for societal benefit.",
    amount: "$500,000 - $10,000,000",
    amountMin: 500000,
    amountMax: 10000000,
    deadline: new Date("2025-04-15"),
    url: "https://www.schmidtfutures.com/",
    type: "foundation",
    category: "technology",
    eligibility: "Researchers, entrepreneurs, and innovators with breakthrough ideas.",
    requirements: "Must demonstrate transformative potential and strong leadership.",
    state: "ALL",
    region: "National",
    contactName: "Schmidt Futures",
    contactEmail: "info@schmidtfutures.com",
    agencyName: "Schmidt Futures",
    tags: '["AI", "science", "technology", "innovation", "breakthrough"]',
    matchScore: 80,
    source: "foundation_directory",
  },
  {
    title: "W.K. Kellogg Foundation Racial Equity Grant",
    funder: "W.K. Kellogg Foundation",
    description: "Supporting organizations working to advance racial equity and healing in communities. Focus on children, families, and communities.",
    amount: "$100,000 - $500,000",
    amountMin: 100000,
    amountMax: 500000,
    deadline: new Date("2025-07-31"),
    url: "https://www.wkkf.org/",
    type: "foundation",
    category: "health",
    eligibility: "Nonprofits serving children and families in underserved communities.",
    requirements: "Must center racial equity in approach. Community engagement required.",
    state: "ALL",
    region: "National",
    contactName: "Kellogg Foundation Grants",
    contactEmail: "grants@wkkf.org",
    agencyName: "W.K. Kellogg Foundation",
    tags: '["racial equity", "children", "families", "community", "healing"]',
    matchScore: 64,
    source: "foundation_directory",
  },
  {
    title: "Robert Wood Johnson Foundation Health Innovation",
    funder: "Robert Wood Johnson Foundation",
    description: "Building a culture of health in America. Funding for innovative approaches to health equity and community health.",
    amount: "$250,000 - $2,000,000",
    amountMin: 250000,
    amountMax: 2000000,
    deadline: new Date("2025-08-01"),
    url: "https://www.rwjf.org/",
    type: "foundation",
    category: "health",
    eligibility: "Nonprofits, research institutions, and community organizations.",
    requirements: "Must address social determinants of health. Equity focus required.",
    state: "ALL",
    region: "National",
    contactName: "RWJF Grants Office",
    contactEmail: "mail@rwjf.org",
    agencyName: "Robert Wood Johnson Foundation",
    tags: '["health", "equity", "community health", "social determinants", "wellness"]',
    matchScore: 69,
    source: "foundation_directory",
  },
  {
    title: "Open Philanthropy AI Safety Grant",
    funder: "Open Philanthropy",
    description: "Funding for AI safety research and policy work. Supporting efforts to ensure artificial intelligence benefits humanity.",
    amount: "$100,000 - $5,000,000",
    amountMin: 100000,
    amountMax: 5000000,
    deadline: null,
    url: "https://www.openphilanthropy.org/",
    type: "foundation",
    category: "technology",
    eligibility: "Research institutions, nonprofits, and individuals working on AI safety.",
    requirements: "Must propose concrete contributions to AI safety or alignment research.",
    state: "ALL",
    region: "National",
    contactName: "Open Philanthropy",
    contactEmail: "info@openphilanthropy.org",
    agencyName: "Open Philanthropy",
    tags: '["AI", "safety", "alignment", "technology", "research"]',
    matchScore: 76,
    source: "foundation_directory",
  },
  {
    title: "Hewlett Foundation Cyber Policy Initiative",
    funder: "William and Flora Hewlett Foundation",
    description: "Supporting research and policy work on cybersecurity and digital policy. Focus on internet governance and digital rights.",
    amount: "$150,000 - $1,000,000",
    amountMin: 150000,
    amountMax: 1000000,
    deadline: new Date("2025-09-15"),
    url: "https://hewlett.org/programs/cyber/",
    type: "foundation",
    category: "technology",
    eligibility: "Research institutions, think tanks, and advocacy organizations.",
    requirements: "Must produce actionable policy recommendations or research.",
    state: "ALL",
    region: "National",
    contactName: "Hewlett Cyber Program",
    contactEmail: "cyber@hewlett.org",
    agencyName: "Hewlett Foundation",
    tags: '["cybersecurity", "policy", "digital rights", "internet governance"]',
    matchScore: 63,
    source: "foundation_directory",
  },
  {
    title: "Simons Foundation Scientific Research Grant",
    funder: "Simons Foundation",
    description: "Supporting basic scientific research in mathematics, theoretical physics, and life sciences. Focus on foundational research.",
    amount: "$500,000 - $10,000,000",
    amountMin: 500000,
    amountMax: 10000000,
    deadline: new Date("2025-05-30"),
    url: "https://www.simonsfoundation.org/",
    type: "foundation",
    category: "research",
    eligibility: "Universities and research institutions.",
    requirements: "Must propose fundamental research with potential for breakthrough discoveries.",
    state: "ALL",
    region: "National",
    contactName: "Simons Foundation",
    contactEmail: "info@simonsfoundation.org",
    agencyName: "Simons Foundation",
    tags: '["science", "research", "mathematics", "physics", "life sciences"]',
    matchScore: 55,
    source: "foundation_directory",
  },
  {
    title: "Moore Foundation Environmental Conservation",
    funder: "Gordon and Betty Moore Foundation",
    description: "Large-scale grants for environmental conservation including marine conservation, Amazon preservation, and sustainable agriculture.",
    amount: "$500,000 - $20,000,000",
    amountMin: 500000,
    amountMax: 20000000,
    deadline: new Date("2025-06-01"),
    url: "https://www.moore.org/programs/environmental-conservation",
    type: "foundation",
    category: "environment",
    eligibility: "Large conservation organizations and research institutions.",
    requirements: "Must demonstrate landscape-scale conservation impact.",
    state: "ALL",
    region: "National",
    contactName: "Moore Foundation Environment",
    contactEmail: "info@moore.org",
    agencyName: "Moore Foundation",
    tags: '["conservation", "environment", "marine", "Amazon", "agriculture"]',
    matchScore: 67,
    source: "foundation_directory",
  },
  {
    title: "Knight Foundation Community Innovation Grant",
    funder: "John S. and James L. Knight Foundation",
    description: "Supporting informed and engaged communities through journalism, arts, and community engagement innovation.",
    amount: "$50,000 - $500,000",
    amountMin: 50000,
    amountMax: 500000,
    deadline: new Date("2025-04-01"),
    url: "https://knightfoundation.org/",
    type: "foundation",
    category: "technology",
    eligibility: "Nonprofits and civic organizations in Knight communities.",
    requirements: "Must demonstrate innovative approach to community engagement.",
    state: "ALL",
    region: "National",
    contactName: "Knight Foundation",
    contactEmail: "grants@knightfoundation.org",
    agencyName: "Knight Foundation",
    tags: '["journalism", "arts", "community", "civic engagement", "innovation"]',
    matchScore: 71,
    source: "foundation_directory",
  },
  {
    title: "Lumina Foundation Education Equity Grant",
    funder: "Lumina Foundation",
    description: "Advancing equitable access to postsecondary education and credentials. Focus on systems change and equity.",
    amount: "$100,000 - $1,000,000",
    amountMin: 100000,
    amountMax: 1000000,
    deadline: new Date("2025-07-15"),
    url: "https://www.luminafoundation.org/",
    type: "foundation",
    category: "health",
    eligibility: "Organizations working on postsecondary education access and completion.",
    requirements: "Must address systemic barriers to educational attainment.",
    state: "ALL",
    region: "National",
    contactName: "Lumina Foundation",
    contactEmail: "info@luminafoundation.org",
    agencyName: "Lumina Foundation",
    tags: '["education", "equity", "postsecondary", "credentials", "access"]',
    matchScore: 59,
    source: "foundation_directory",
  },
  {
    title: "Ballmer Group Human Services Innovation",
    funder: "Ballmer Group",
    description: "Supporting economic mobility for children and families in poverty. Focus on systems change and evidence-based interventions.",
    amount: "$250,000 - $5,000,000",
    amountMin: 250000,
    amountMax: 5000000,
    deadline: new Date("2025-05-01"),
    url: "https://www.ballmergroup.org/",
    type: "foundation",
    category: "health",
    eligibility: "Nonprofits working on economic mobility and child welfare.",
    requirements: "Must use data-driven approaches and demonstrate scalability.",
    state: "ALL",
    region: "National",
    contactName: "Ballmer Group",
    contactEmail: "info@ballmergroup.org",
    agencyName: "Ballmer Group",
    tags: '["economic mobility", "poverty", "children", "families", "human services"]',
    matchScore: 73,
    source: "foundation_directory",
  },
  {
    title: "Packard Foundation Ocean Conservation",
    funder: "David and Lucile Packard Foundation",
    description: "Major funding for ocean and coastal conservation including marine protected areas, sustainable fisheries, and ocean climate.",
    amount: "$250,000 - $5,000,000",
    amountMin: 250000,
    amountMax: 5000000,
    deadline: new Date("2025-08-31"),
    url: "https://www.packard.org/what-we-fund/ocean/",
    type: "foundation",
    category: "environment",
    eligibility: "Marine conservation organizations and research institutions.",
    requirements: "Must propose science-based conservation strategies.",
    state: "ALL",
    region: "National",
    contactName: "Packard Foundation Ocean",
    contactEmail: "inquiries@packard.org",
    agencyName: "Packard Foundation",
    tags: '["ocean", "marine", "conservation", "fisheries", "climate"]',
    matchScore: 65,
    source: "foundation_directory",
  },
  {
    title: "Wellcome Trust Health Research Grant",
    funder: "Wellcome Trust",
    description: "Funding for innovative health research with global impact. Support for early-career researchers and established investigators.",
    amount: "$500,000 - $3,000,000",
    amountMin: 500000,
    amountMax: 3000000,
    deadline: new Date("2025-09-30"),
    url: "https://wellcome.org/grant-funding",
    type: "foundation",
    category: "research",
    eligibility: "Researchers at accredited institutions worldwide.",
    requirements: "Must propose innovative approach to health challenge. Open access publication required.",
    state: "ALL",
    region: "National",
    contactName: "Wellcome Trust Grants",
    contactEmail: "grantenquiries@wellcome.org",
    agencyName: "Wellcome Trust",
    tags: '["health", "research", "global health", "science", "medicine"]',
    matchScore: 61,
    source: "foundation_directory",
  },
  {
    title: "Surdna Foundation Sustainable Economies",
    funder: "Surdna Foundation",
    description: "Building sustainable economies that are just, equitable, and regenerative. Focus on workers' rights and sustainable businesses.",
    amount: "$100,000 - $500,000",
    amountMin: 100000,
    amountMax: 500000,
    deadline: new Date("2025-06-15"),
    url: "https://surdna.org/programs/sustainable-economies/",
    type: "foundation",
    category: "economic_development",
    eligibility: "Nonprofits working on economic justice and sustainability.",
    requirements: "Must center equity and worker voice in approach.",
    state: "ALL",
    region: "National",
    contactName: "Surdna Foundation",
    contactEmail: "grants@surdna.org",
    agencyName: "Surdna Foundation",
    tags: '["sustainable economy", "workers rights", "equity", "regenerative", "justice"]',
    matchScore: 70,
    source: "foundation_directory",
  },
];

// Corporate Grants (national)
const corporateGrants = [
  {
    title: "Google for Startups Cloud Program",
    funder: "Google",
    description: "Cloud credits and technical support for high-potential startups. Includes access to Google Cloud Platform, mentorship, and networking opportunities.",
    amount: "$100,000 in cloud credits",
    amountMin: 100000,
    amountMax: 100000,
    deadline: new Date("2025-12-31"),
    url: "https://startup.google.com/",
    type: "corporate",
    category: "technology",
    eligibility: "Seed to Series A startups. Must be building on cloud infrastructure.",
    requirements: "Application review by Google team. Must demonstrate growth potential and technical innovation.",
    state: "ALL",
    region: "National",
    contactName: "Google for Startups",
    contactEmail: "startups@google.com",
    agencyName: "Google",
    tags: '["cloud", "startups", "technology", "infrastructure"]',
    matchScore: 95,
    source: "corporate_programs",
  },
  {
    title: "Microsoft AI for Good Grant",
    funder: "Microsoft",
    description: "Supporting organizations using AI to address societal challenges including accessibility, humanitarian action, cultural heritage, and environmental sustainability.",
    amount: "$50,000 - $500,000",
    amountMin: 50000,
    amountMax: 500000,
    deadline: new Date("2025-03-31"),
    url: "https://www.microsoft.com/en-us/ai/ai-for-good",
    type: "corporate",
    category: "technology",
    eligibility: "Nonprofits, academic institutions, and social enterprises.",
    requirements: "Must use AI/ML in solution. Clear metrics for social impact required.",
    state: "ALL",
    region: "National",
    contactName: "Microsoft AI for Good",
    contactEmail: "aiforgood@microsoft.com",
    agencyName: "Microsoft",
    tags: '["AI", "social impact", "accessibility", "sustainability"]',
    matchScore: 76,
    source: "corporate_programs",
  },
  {
    title: "AWS Startup Credits Program",
    funder: "Amazon Web Services",
    description: "Cloud infrastructure credits for startups building innovative products. Includes technical support, training, and access to AWS partner network.",
    amount: "$25,000 - $100,000 in credits",
    amountMin: 25000,
    amountMax: 100000,
    deadline: null,
    url: "https://aws.amazon.com/startups/",
    type: "corporate",
    category: "technology",
    eligibility: "Startups with less than $10M in funding. Must be building technology product.",
    requirements: "Must be affiliated with approved accelerator, incubator, or VC.",
    state: "ALL",
    region: "National",
    contactName: "AWS Startups",
    contactEmail: "startups@amazon.com",
    agencyName: "Amazon Web Services",
    tags: '["cloud", "AWS", "startups", "infrastructure"]',
    matchScore: 90,
    source: "corporate_programs",
  },
  {
    title: "Salesforce Impact Fund",
    funder: "Salesforce",
    description: "Supporting nonprofits leveraging technology for social impact. Includes grants, product donations, and technical assistance.",
    amount: "$10,000 - $100,000",
    amountMin: 10000,
    amountMax: 100000,
    deadline: new Date("2025-09-30"),
    url: "https://www.salesforce.org/grants/",
    type: "corporate",
    category: "technology",
    eligibility: "501(c)(3) nonprofits using or planning to use Salesforce.",
    requirements: "Must demonstrate social impact goals and technical capacity.",
    state: "ALL",
    region: "National",
    contactName: "Salesforce.org Grants",
    contactEmail: "grants@salesforce.org",
    agencyName: "Salesforce",
    tags: '["CRM", "nonprofits", "technology", "social impact"]',
    matchScore: 70,
    source: "corporate_programs",
  },
  {
    title: "NVIDIA Inception Program",
    funder: "NVIDIA",
    description: "AI startup program offering GPU credits, technical support, and go-to-market assistance for AI-focused startups.",
    amount: "$50,000 - $150,000 in credits",
    amountMin: 50000,
    amountMax: 150000,
    deadline: null,
    url: "https://www.nvidia.com/en-us/startups/",
    type: "corporate",
    category: "technology",
    eligibility: "AI/ML startups building on GPU computing.",
    requirements: "Must demonstrate AI/ML use case and growth potential.",
    state: "ALL",
    region: "National",
    contactName: "NVIDIA Inception",
    contactEmail: "inception@nvidia.com",
    agencyName: "NVIDIA",
    tags: '["AI", "ML", "GPU", "deep learning", "startups"]',
    matchScore: 85,
    source: "corporate_programs",
  },
  // Additional Corporate Grants
  {
    title: "Meta AI Research Grant",
    funder: "Meta",
    description: "Supporting academic and nonprofit research in AI, machine learning, AR/VR, and responsible technology development.",
    amount: "$50,000 - $300,000",
    amountMin: 50000,
    amountMax: 300000,
    deadline: new Date("2025-05-31"),
    url: "https://research.facebook.com/research-awards/",
    type: "corporate",
    category: "research",
    eligibility: "Academic institutions and nonprofit research organizations.",
    requirements: "Must propose novel research with potential for open publication.",
    state: "ALL",
    region: "National",
    contactName: "Meta Research",
    contactEmail: "research@meta.com",
    agencyName: "Meta",
    tags: '["AI", "research", "VR", "AR", "machine learning"]',
    matchScore: 72,
    source: "corporate_programs",
  },
  {
    title: "IBM Quantum Network Grant",
    funder: "IBM",
    description: "Access to IBM quantum computers and funding for quantum computing research and applications development.",
    amount: "$100,000 - $500,000",
    amountMin: 100000,
    amountMax: 500000,
    deadline: new Date("2025-06-30"),
    url: "https://www.ibm.com/quantum/network",
    type: "corporate",
    category: "research",
    eligibility: "Research institutions, startups, and enterprises exploring quantum computing.",
    requirements: "Must propose specific quantum computing use case or research project.",
    state: "ALL",
    region: "National",
    contactName: "IBM Quantum",
    contactEmail: "quantum@ibm.com",
    agencyName: "IBM",
    tags: '["quantum", "computing", "research", "technology"]',
    matchScore: 68,
    source: "corporate_programs",
  },
  {
    title: "Intel RISE Technology Initiative",
    funder: "Intel",
    description: "Supporting diverse entrepreneurs and organizations in STEM education, workforce readiness, and inclusive technology.",
    amount: "$25,000 - $200,000",
    amountMin: 25000,
    amountMax: 200000,
    deadline: new Date("2025-04-15"),
    url: "https://www.intel.com/content/www/us/en/corporate-responsibility/rise.html",
    type: "corporate",
    category: "technology",
    eligibility: "Nonprofits and educational institutions focused on STEM and diversity.",
    requirements: "Must demonstrate commitment to increasing diversity in technology.",
    state: "ALL",
    region: "National",
    contactName: "Intel RISE",
    contactEmail: "rise@intel.com",
    agencyName: "Intel",
    tags: '["STEM", "diversity", "education", "workforce", "technology"]',
    matchScore: 74,
    source: "corporate_programs",
  },
  {
    title: "Cisco Social Impact Grant",
    funder: "Cisco",
    description: "Funding for organizations using technology to address social challenges. Focus on digital inclusion, education, and economic empowerment.",
    amount: "$50,000 - $250,000",
    amountMin: 50000,
    amountMax: 250000,
    deadline: new Date("2025-07-31"),
    url: "https://www.cisco.com/c/en/us/about/csr.html",
    type: "corporate",
    category: "technology",
    eligibility: "Nonprofits working on digital equity and technology access.",
    requirements: "Must leverage technology for social impact. Networking focus preferred.",
    state: "ALL",
    region: "National",
    contactName: "Cisco Social Impact",
    contactEmail: "socialimpact@cisco.com",
    agencyName: "Cisco",
    tags: '["digital inclusion", "networking", "education", "social impact"]',
    matchScore: 71,
    source: "corporate_programs",
  },
  {
    title: "Oracle for Startups Cloud Credits",
    funder: "Oracle",
    description: "Cloud infrastructure and database credits for startups. Includes technical support and access to Oracle partner ecosystem.",
    amount: "$50,000 - $250,000 in credits",
    amountMin: 50000,
    amountMax: 250000,
    deadline: null,
    url: "https://www.oracle.com/startup/",
    type: "corporate",
    category: "technology",
    eligibility: "Startups building on cloud infrastructure. Pre-seed to Series B.",
    requirements: "Must be building technology product with cloud component.",
    state: "ALL",
    region: "National",
    contactName: "Oracle Startups",
    contactEmail: "startups@oracle.com",
    agencyName: "Oracle",
    tags: '["cloud", "database", "enterprise", "startups"]',
    matchScore: 82,
    source: "corporate_programs",
  },
  {
    title: "Adobe Creative Residency Grant",
    funder: "Adobe",
    description: "Supporting emerging creators and designers with funding, tools, and mentorship to develop their creative practice.",
    amount: "$50,000 + Adobe Creative Cloud",
    amountMin: 50000,
    amountMax: 75000,
    deadline: new Date("2025-03-01"),
    url: "https://www.adobe.com/about-adobe/creative-residency.html",
    type: "corporate",
    category: "technology",
    eligibility: "Emerging creators, designers, and creative technologists.",
    requirements: "Must propose creative project. Portfolio required.",
    state: "ALL",
    region: "National",
    contactName: "Adobe Creative Residency",
    contactEmail: "residency@adobe.com",
    agencyName: "Adobe",
    tags: '["creative", "design", "arts", "technology"]',
    matchScore: 65,
    source: "corporate_programs",
  },
  {
    title: "Stripe Economic Infrastructure Grant",
    funder: "Stripe",
    description: "Supporting organizations building financial infrastructure for underserved communities and emerging markets.",
    amount: "$100,000 - $500,000",
    amountMin: 100000,
    amountMax: 500000,
    deadline: new Date("2025-08-15"),
    url: "https://stripe.com/climate",
    type: "corporate",
    category: "economic_development",
    eligibility: "Fintech startups and nonprofits working on financial inclusion.",
    requirements: "Must address financial infrastructure gaps. Technical team required.",
    state: "ALL",
    region: "National",
    contactName: "Stripe Impact",
    contactEmail: "impact@stripe.com",
    agencyName: "Stripe",
    tags: '["fintech", "payments", "economic infrastructure", "financial inclusion"]',
    matchScore: 79,
    source: "corporate_programs",
  },
  {
    title: "Shopify Entrepreneurship Fund",
    funder: "Shopify",
    description: "Supporting underrepresented entrepreneurs with grants, mentorship, and access to Shopify's commerce platform.",
    amount: "$25,000 - $100,000",
    amountMin: 25000,
    amountMax: 100000,
    deadline: new Date("2025-06-01"),
    url: "https://www.shopify.com/build-black",
    type: "corporate",
    category: "entrepreneurship",
    eligibility: "Black entrepreneurs and businesses. BIPOC-owned businesses encouraged.",
    requirements: "Must be launching or growing e-commerce business.",
    state: "ALL",
    region: "National",
    contactName: "Shopify Social Impact",
    contactEmail: "socialimpact@shopify.com",
    agencyName: "Shopify",
    tags: '["e-commerce", "entrepreneurship", "diversity", "retail"]',
    matchScore: 77,
    source: "corporate_programs",
  },
  {
    title: "JPMorgan Chase Small Business Forward",
    funder: "JPMorgan Chase",
    description: "Supporting small businesses in underserved communities with capital, technical assistance, and growth resources.",
    amount: "$50,000 - $250,000",
    amountMin: 50000,
    amountMax: 250000,
    deadline: new Date("2025-05-01"),
    url: "https://www.jpmorganchase.com/impact/small-business",
    type: "corporate",
    category: "small_business",
    eligibility: "Small businesses in underserved communities. CDFI partners preferred.",
    requirements: "Must demonstrate community impact and job creation potential.",
    state: "ALL",
    region: "National",
    contactName: "JPMorgan Chase Impact",
    contactEmail: "smallbusiness@jpmchase.com",
    agencyName: "JPMorgan Chase",
    tags: '["small business", "financial inclusion", "community development"]',
    matchScore: 73,
    source: "corporate_programs",
  },
  {
    title: "Bank of America Neighborhood Builders",
    funder: "Bank of America",
    description: "Leadership development and grants for nonprofits making a difference in local communities across the U.S.",
    amount: "$200,000",
    amountMin: 200000,
    amountMax: 200000,
    deadline: new Date("2025-04-30"),
    url: "https://about.bankofamerica.com/en/making-an-impact/neighborhood-builders",
    type: "corporate",
    category: "health",
    eligibility: "Nonprofits with annual operating budgets between $1M and $10M.",
    requirements: "Must serve local community needs. Leadership development component included.",
    state: "ALL",
    region: "National",
    contactName: "Bank of America Charitable Foundation",
    contactEmail: "neighborhoodbuilders@bofa.com",
    agencyName: "Bank of America",
    tags: '["nonprofits", "community", "leadership", "social services"]',
    matchScore: 66,
    source: "corporate_programs",
  },
  {
    title: "Target Community Grants",
    funder: "Target",
    description: "Supporting organizations that create equitable access to essential needs, education, and opportunity in local communities.",
    amount: "$10,000 - $100,000",
    amountMin: 10000,
    amountMax: 100000,
    deadline: new Date("2025-09-30"),
    url: "https://corporate.target.com/sustainability-ESG/community",
    type: "corporate",
    category: "health",
    eligibility: "501(c)(3) nonprofits serving communities where Target operates.",
    requirements: "Must align with Target's focus areas: equity, education, or essential needs.",
    state: "ALL",
    region: "National",
    contactName: "Target Community Relations",
    contactEmail: "community@target.com",
    agencyName: "Target",
    tags: '["community", "education", "equity", "retail"]',
    matchScore: 62,
    source: "corporate_programs",
  },
  {
    title: "Walmart Foundation Community Grant",
    funder: "Walmart Foundation",
    description: "Local grants supporting hunger relief, workforce development, and disaster response in communities served by Walmart.",
    amount: "$25,000 - $500,000",
    amountMin: 25000,
    amountMax: 500000,
    deadline: null,
    url: "https://walmart.org/how-we-give/local-community-grants",
    type: "corporate",
    category: "health",
    eligibility: "Nonprofits in communities with Walmart stores. Focus on underserved areas.",
    requirements: "Must address hunger, workforce, or disaster preparedness.",
    state: "ALL",
    region: "National",
    contactName: "Walmart Foundation",
    contactEmail: "foundation@walmart.com",
    agencyName: "Walmart Foundation",
    tags: '["hunger relief", "workforce", "community", "disaster response"]',
    matchScore: 64,
    source: "corporate_programs",
  },
  {
    title: "Patagonia Environmental Grants",
    funder: "Patagonia",
    description: "Supporting grassroots environmental organizations working on biodiversity, climate, communities, land, and water.",
    amount: "$5,000 - $50,000",
    amountMin: 5000,
    amountMax: 50000,
    deadline: new Date("2025-04-30"),
    url: "https://www.patagonia.com/how-we-fund/",
    type: "corporate",
    category: "environment",
    eligibility: "Grassroots environmental organizations. Direct action focus preferred.",
    requirements: "Must propose specific environmental campaign or project.",
    state: "ALL",
    region: "National",
    contactName: "Patagonia Environmental Grants",
    contactEmail: "enviro_grants@patagonia.com",
    agencyName: "Patagonia",
    tags: '["environment", "activism", "conservation", "grassroots"]',
    matchScore: 69,
    source: "corporate_programs",
  },
  {
    title: "Verizon Forward for Good",
    funder: "Verizon",
    description: "Digital inclusion initiatives supporting education, healthcare access, and workforce development through connectivity.",
    amount: "$50,000 - $300,000",
    amountMin: 50000,
    amountMax: 300000,
    deadline: new Date("2025-06-15"),
    url: "https://www.verizon.com/about/responsibility",
    type: "corporate",
    category: "technology",
    eligibility: "Nonprofits working on digital equity and connectivity.",
    requirements: "Must leverage technology for social impact. Metrics-driven approach required.",
    state: "ALL",
    region: "National",
    contactName: "Verizon Social Impact",
    contactEmail: "socialimpact@verizon.com",
    agencyName: "Verizon",
    tags: '["digital inclusion", "connectivity", "education", "healthcare"]',
    matchScore: 75,
    source: "corporate_programs",
  },
  {
    title: "AT&T Connected Learning Grant",
    funder: "AT&T",
    description: "Bridging the digital divide through support for digital literacy, connectivity, and educational technology programs.",
    amount: "$25,000 - $150,000",
    amountMin: 25000,
    amountMax: 150000,
    deadline: new Date("2025-07-01"),
    url: "https://about.att.com/csr/home/society/connected-learning.html",
    type: "corporate",
    category: "technology",
    eligibility: "Nonprofits and schools addressing the digital divide.",
    requirements: "Must focus on underserved communities. Education component required.",
    state: "ALL",
    region: "National",
    contactName: "AT&T Foundation",
    contactEmail: "attfoundation@att.com",
    agencyName: "AT&T",
    tags: '["digital divide", "education", "connectivity", "literacy"]',
    matchScore: 70,
    source: "corporate_programs",
  },
  {
    title: "Twilio Social Impact Credits",
    funder: "Twilio",
    description: "Communications API credits for nonprofits and social impact organizations. Includes technical support and onboarding.",
    amount: "$25,000 - $100,000 in credits",
    amountMin: 25000,
    amountMax: 100000,
    deadline: null,
    url: "https://www.twilio.org/",
    type: "corporate",
    category: "technology",
    eligibility: "501(c)(3) nonprofits and B-Corps.",
    requirements: "Must use communications technology for social impact.",
    state: "ALL",
    region: "National",
    contactName: "Twilio.org",
    contactEmail: "impact@twilio.org",
    agencyName: "Twilio",
    tags: '["communications", "API", "nonprofits", "social impact"]',
    matchScore: 78,
    source: "corporate_programs",
  },
  {
    title: "Comcast NBCUniversal Project UP",
    funder: "Comcast NBCUniversal",
    description: "Digital equity initiative supporting connectivity, skills training, and resources for underrepresented communities.",
    amount: "$25,000 - $200,000",
    amountMin: 25000,
    amountMax: 200000,
    deadline: new Date("2025-05-15"),
    url: "https://corporate.comcast.com/impact/project-up",
    type: "corporate",
    category: "technology",
    eligibility: "Nonprofits addressing digital equity in Comcast service areas.",
    requirements: "Must demonstrate measurable impact on digital skills or access.",
    state: "ALL",
    region: "National",
    contactName: "Comcast Foundation",
    contactEmail: "foundation@comcast.com",
    agencyName: "Comcast NBCUniversal",
    tags: '["digital equity", "connectivity", "skills training", "media"]',
    matchScore: 67,
    source: "corporate_programs",
  },
  {
    title: "Mastercard Strive USA",
    funder: "Mastercard Center for Inclusive Growth",
    description: "Supporting small businesses owned by women and people of color with capital access, digital tools, and mentorship.",
    amount: "$50,000 - $250,000",
    amountMin: 50000,
    amountMax: 250000,
    deadline: new Date("2025-08-31"),
    url: "https://www.mastercardcenter.org/strive",
    type: "corporate",
    category: "small_business",
    eligibility: "CDFIs and organizations supporting diverse small business owners.",
    requirements: "Must serve women-owned or BIPOC-owned small businesses.",
    state: "ALL",
    region: "National",
    contactName: "Mastercard Center",
    contactEmail: "striveusa@mastercard.com",
    agencyName: "Mastercard",
    tags: '["small business", "diversity", "financial inclusion", "women-owned"]',
    matchScore: 76,
    source: "corporate_programs",
  },
];

// State-specific grant templates
function generateStateGrants(state: { code: string; name: string; region: string }) {
  const stateGrants = [
    {
      title: `${state.name} Small Business Development Grant`,
      funder: `${state.name} Department of Commerce`,
      description: `State funding program to support small business growth and job creation in ${state.name}. Priority given to businesses in underserved communities and emerging industries.`,
      amount: "$25,000 - $150,000",
      amountMin: 25000,
      amountMax: 150000,
      deadline: new Date("2025-06-30"),
      url: `https://commerce.${state.code.toLowerCase()}.gov/grants`,
      type: "state",
      category: "small_business",
      eligibility: `Must be a registered business in ${state.name} with fewer than 50 employees.`,
      requirements: "Business plan, financial statements, and job creation projections required.",
      state: state.code,
      region: state.region,
      contactName: `${state.name} Commerce Grants Office`,
      contactEmail: `grants@commerce.${state.code.toLowerCase()}.gov`,
      contactPhone: "555-STATE-BIZ",
      agencyName: `${state.name} Department of Commerce`,
      tags: '["small business", "job creation", "state grant"]',
      matchScore: Math.floor(Math.random() * 30) + 50,
      source: "state_programs",
    },
    {
      title: `${state.name} Innovation Fund`,
      funder: `${state.name} Economic Development Authority`,
      description: `Venture-style funding for innovative startups headquartered in ${state.name}. Focus on technology, life sciences, and clean energy sectors.`,
      amount: "$100,000 - $500,000",
      amountMin: 100000,
      amountMax: 500000,
      deadline: new Date("2025-05-15"),
      url: `https://eda.${state.code.toLowerCase()}.gov/innovation`,
      type: "state",
      category: "venture",
      eligibility: `Startups headquartered in ${state.name}. Must have at least one full-time employee.`,
      requirements: "Pitch deck, cap table, and use of funds required. Must match with private investment.",
      state: state.code,
      region: state.region,
      contactName: `${state.name} Innovation Office`,
      contactEmail: `innovation@eda.${state.code.toLowerCase()}.gov`,
      agencyName: `${state.name} Economic Development Authority`,
      tags: '["innovation", "startups", "venture", "technology"]',
      matchScore: Math.floor(Math.random() * 30) + 60,
      source: "state_programs",
    },
    {
      title: `${state.name} Workforce Training Grant`,
      funder: `${state.name} Department of Labor`,
      description: `Funding for businesses to train and upskill workers in ${state.name}. Covers training costs, curriculum development, and equipment.`,
      amount: "$10,000 - $75,000",
      amountMin: 10000,
      amountMax: 75000,
      deadline: new Date("2025-08-01"),
      url: `https://labor.${state.code.toLowerCase()}.gov/training`,
      type: "state",
      category: "workforce",
      eligibility: `Employers in ${state.name} providing training to ${state.name} residents.`,
      requirements: "Training plan, employee roster, and outcomes tracking required.",
      state: state.code,
      region: state.region,
      contactName: `${state.name} Workforce Development`,
      contactEmail: `workforce@labor.${state.code.toLowerCase()}.gov`,
      agencyName: `${state.name} Department of Labor`,
      tags: '["workforce", "training", "employment", "skills"]',
      matchScore: Math.floor(Math.random() * 25) + 45,
      source: "state_programs",
    },
    {
      title: `${state.name} Clean Energy Business Incentive`,
      funder: `${state.name} Energy Office`,
      description: `Grants and incentives for businesses adopting clean energy solutions or developing clean tech products in ${state.name}.`,
      amount: "$50,000 - $250,000",
      amountMin: 50000,
      amountMax: 250000,
      deadline: new Date("2025-07-31"),
      url: `https://energy.${state.code.toLowerCase()}.gov/incentives`,
      type: "state",
      category: "energy",
      eligibility: `Businesses operating in ${state.name} in clean energy sector.`,
      requirements: "Energy audit, project plan, and environmental impact assessment required.",
      state: state.code,
      region: state.region,
      contactName: `${state.name} Energy Office`,
      contactEmail: `energy@${state.code.toLowerCase()}.gov`,
      agencyName: `${state.name} Energy Office`,
      tags: '["clean energy", "sustainability", "green business"]',
      matchScore: Math.floor(Math.random() * 30) + 55,
      source: "state_programs",
    },
  ];

  // Add some variety - some states get extra grants
  if (["CA", "NY", "TX", "FL", "MA", "WA"].includes(state.code)) {
    stateGrants.push({
      title: `${state.name} Tech Startup Accelerator Grant`,
      funder: `${state.name} Technology Council`,
      description: `Accelerator funding for tech startups in ${state.name}. Includes mentorship, office space, and demo day opportunities.`,
      amount: "$50,000 - $200,000",
      amountMin: 50000,
      amountMax: 200000,
      deadline: new Date("2025-04-30"),
      url: `https://techcouncil.${state.code.toLowerCase()}.org/accelerator`,
      type: "state",
      category: "accelerator",
      eligibility: `Tech startups based in ${state.name}. Pre-seed to Series A stage.`,
      requirements: "Demo-ready product, founding team bios, and market analysis required.",
      state: state.code,
      region: state.region,
      contactName: `${state.name} Tech Council`,
      contactEmail: `accelerator@techcouncil.${state.code.toLowerCase()}.org`,
      agencyName: `${state.name} Technology Council`,
      tags: '["tech", "accelerator", "startups", "mentorship"]',
      matchScore: Math.floor(Math.random() * 25) + 70,
      source: "state_programs",
    });
  }

  return stateGrants;
}

// Generate all grants
const allGrants = [
  ...federalGrants,
  ...foundationGrants,
  ...corporateGrants,
  ...states.flatMap(generateStateGrants),
];

async function main() {
  console.log("🌱 Seeding database with comprehensive grant data...\n");

  // Clear existing grants
  await prisma.grant.deleteMany({});
  console.log("Cleared existing grants\n");

  console.log(`Creating ${allGrants.length} grants...\n`);

  // Insert all grants
  let created = 0;
  for (const grant of allGrants) {
    await prisma.grant.create({
      data: {
        ...grant,
        status: "discovered",
      },
    });
    created++;
    if (created % 25 === 0) {
      console.log(`✅ Created ${created}/${allGrants.length} grants...`);
    }
  }

  console.log(`\n🎉 Successfully seeded ${created} grants!`);
  console.log(`   - ${federalGrants.length} Federal grants`);
  console.log(`   - ${foundationGrants.length} Foundation grants (private foundations)`);
  console.log(`   - ${corporateGrants.length} Corporate grants (corporate giving programs)`);
  console.log(`   - ${states.length * 4 + 6} State grants (across ${states.length} states)`);
}

main()
  .catch((e) => {
    console.error("Error seeding database:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
