import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";
import "dotenv/config";

const connectionString = process.env.DIRECT_URL || process.env.DATABASE_URL;

const pool = new Pool({
  connectionString,
});
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

// Matthew Lesko-style grants - Government programs for small businesses and individuals
// These are the types of accessible, often overlooked programs that Lesko's service highlights

const leskoStyleGrants = [
  // SBA Programs
  {
    title: "SBA 7(a) Loan Guarantee Program",
    funder: "U.S. Small Business Administration",
    description: "The SBA's most common loan program, providing up to $5 million in financing for small businesses. Government guarantees up to 85% of the loan, making it easier for small businesses to qualify.",
    amount: "Up to $5,000,000",
    amountMin: 50000,
    amountMax: 5000000,
    deadline: null,
    url: "https://www.sba.gov/funding-programs/loans/7a-loans",
    type: "federal",
    category: "small_business",
    eligibility: "Small businesses meeting SBA size standards. Must be for-profit and operate in the U.S.",
    requirements: "Good credit history, ability to repay, and use of funds for sound business purpose.",
    state: "ALL",
    region: "National",
    contactName: "SBA Loan Programs",
    contactEmail: "answerdesk@sba.gov",
    contactPhone: "1-800-827-5722",
    agencyName: "U.S. Small Business Administration",
    tags: '["SBA", "small business", "loan", "financing", "government backed"]',
    matchScore: 88,
    source: "sba.gov",
  },
  {
    title: "SBA Microloan Program",
    funder: "U.S. Small Business Administration",
    description: "Provides small loans up to $50,000 to help small businesses and certain not-for-profit childcare centers start up and expand. Average microloan is about $13,000.",
    amount: "Up to $50,000",
    amountMin: 500,
    amountMax: 50000,
    deadline: null,
    url: "https://www.sba.gov/funding-programs/loans/microloans",
    type: "federal",
    category: "small_business",
    eligibility: "Small businesses and certain nonprofit childcare centers. Women-owned, minority-owned, and veteran-owned businesses encouraged.",
    requirements: "May require collateral. Interest rates typically 8-13%.",
    state: "ALL",
    region: "National",
    contactName: "SBA Microloan Program",
    contactEmail: "answerdesk@sba.gov",
    contactPhone: "1-800-827-5722",
    agencyName: "U.S. Small Business Administration",
    tags: '["SBA", "microloan", "small business", "startup", "women-owned", "minority-owned"]',
    matchScore: 85,
    source: "sba.gov",
  },
  {
    title: "SBA Community Advantage Loan",
    funder: "U.S. Small Business Administration",
    description: "Loans specifically for small businesses in underserved markets. Designed to reach entrepreneurs who may not qualify for traditional SBA loans.",
    amount: "Up to $350,000",
    amountMin: 50000,
    amountMax: 350000,
    deadline: null,
    url: "https://www.sba.gov/partners/lenders/community-advantage",
    type: "federal",
    category: "small_business",
    eligibility: "Small businesses in underserved markets including LMI communities, rural areas, and minority-owned businesses.",
    requirements: "Apply through SBA-approved Community Advantage lenders.",
    state: "ALL",
    region: "National",
    contactName: "SBA Community Advantage",
    contactEmail: "answerdesk@sba.gov",
    agencyName: "U.S. Small Business Administration",
    tags: '["SBA", "underserved", "community", "minority", "rural", "LMI"]',
    matchScore: 82,
    source: "sba.gov",
  },
  {
    title: "SBA 504 Loan Program",
    funder: "U.S. Small Business Administration",
    description: "Long-term, fixed-rate financing for major fixed assets like real estate and equipment. Promotes business growth and job creation.",
    amount: "$125,000 - $5,500,000",
    amountMin: 125000,
    amountMax: 5500000,
    deadline: null,
    url: "https://www.sba.gov/funding-programs/loans/504-loans",
    type: "federal",
    category: "small_business",
    eligibility: "For-profit businesses with tangible net worth under $15 million and average net income under $5 million.",
    requirements: "Must create or retain jobs or meet public policy goals. Cannot be used for working capital.",
    state: "ALL",
    region: "National",
    contactName: "SBA 504 Program",
    contactEmail: "answerdesk@sba.gov",
    agencyName: "U.S. Small Business Administration",
    tags: '["SBA", "real estate", "equipment", "fixed assets", "job creation"]',
    matchScore: 75,
    source: "sba.gov",
  },
  // USDA Programs
  {
    title: "USDA Rural Business Development Grant",
    funder: "U.S. Department of Agriculture",
    description: "Grants to support targeted technical assistance, training, and other activities leading to the development or expansion of small and emerging private businesses in rural areas.",
    amount: "$10,000 - $500,000",
    amountMin: 10000,
    amountMax: 500000,
    deadline: new Date("2025-05-31"),
    url: "https://www.rd.usda.gov/programs-services/business-programs/rural-business-development-grants",
    type: "federal",
    category: "small_business",
    eligibility: "Towns, communities, state agencies, authorities, nonprofits in rural areas (populations up to 50,000).",
    requirements: "Must benefit small and emerging businesses in rural areas.",
    state: "ALL",
    region: "National",
    contactName: "USDA Rural Development",
    contactEmail: "rd.info@usda.gov",
    contactPhone: "1-800-670-6553",
    agencyName: "USDA Rural Development",
    tags: '["USDA", "rural", "small business", "development", "technical assistance"]',
    matchScore: 72,
    source: "usda.gov",
  },
  {
    title: "USDA Value-Added Producer Grant (VAPG)",
    funder: "U.S. Department of Agriculture",
    description: "Grants to help agricultural producers enter value-added activities related to their products. Can fund planning activities or working capital for marketing value-added products.",
    amount: "$75,000 - $250,000",
    amountMin: 75000,
    amountMax: 250000,
    deadline: new Date("2025-04-15"),
    url: "https://www.rd.usda.gov/programs-services/business-programs/value-added-producer-grants",
    type: "federal",
    category: "small_business",
    eligibility: "Independent agricultural producers, farmer and rancher cooperatives, agricultural producer groups.",
    requirements: "Must propose value-added agricultural business venture. Matching funds required.",
    state: "ALL",
    region: "National",
    contactName: "USDA VAPG Program",
    contactEmail: "vapg@usda.gov",
    agencyName: "USDA Rural Development",
    tags: '["USDA", "agriculture", "farming", "value-added", "producer"]',
    matchScore: 65,
    source: "usda.gov",
  },
  {
    title: "USDA Rural Energy for America Program (REAP)",
    funder: "U.S. Department of Agriculture",
    description: "Provides guaranteed loan financing and grant funding to agricultural producers and rural small businesses for renewable energy systems or energy efficiency improvements.",
    amount: "$2,500 - $1,000,000",
    amountMin: 2500,
    amountMax: 1000000,
    deadline: new Date("2025-03-31"),
    url: "https://www.rd.usda.gov/programs-services/energy-programs/rural-energy-america-program-renewable-energy-systems-energy-efficiency-improvement-guaranteed-loans",
    type: "federal",
    category: "energy",
    eligibility: "Agricultural producers and rural small businesses.",
    requirements: "Must be for renewable energy or energy efficiency. Rural location required.",
    state: "ALL",
    region: "National",
    contactName: "USDA REAP Program",
    contactEmail: "reap@usda.gov",
    agencyName: "USDA Rural Development",
    tags: '["USDA", "renewable energy", "solar", "rural", "energy efficiency", "agriculture"]',
    matchScore: 70,
    source: "usda.gov",
  },
  // HUD Programs
  {
    title: "HUD Section 108 Loan Guarantee Program",
    funder: "U.S. Department of Housing and Urban Development",
    description: "Enables communities to leverage their Community Development Block Grant (CDBG) funds to access low-cost financing for economic development, housing, and public facilities.",
    amount: "Up to $50,000,000",
    amountMin: 100000,
    amountMax: 50000000,
    deadline: null,
    url: "https://www.hud.gov/program_offices/comm_planning/section108",
    type: "federal",
    category: "economic_development",
    eligibility: "Local governments that receive CDBG entitlement grants or states on behalf of non-entitlement communities.",
    requirements: "Must meet CDBG national objectives: benefit LMI persons, prevent slums, or address urgent community needs.",
    state: "ALL",
    region: "National",
    contactName: "HUD Section 108 Program",
    contactEmail: "section108@hud.gov",
    agencyName: "U.S. Department of Housing and Urban Development",
    tags: '["HUD", "economic development", "community development", "CDBG", "infrastructure"]',
    matchScore: 60,
    source: "hud.gov",
  },
  // EDA Programs
  {
    title: "EDA Public Works Program",
    funder: "U.S. Economic Development Administration",
    description: "Empowers distressed communities to revitalize, expand, and upgrade their physical infrastructure to attract new industry, encourage business expansion, and generate jobs.",
    amount: "$100,000 - $3,000,000",
    amountMin: 100000,
    amountMax: 3000000,
    deadline: null,
    url: "https://www.eda.gov/funding/programs/public-works",
    type: "federal",
    category: "economic_development",
    eligibility: "State and local governments, Indian tribes, institutions of higher education, and nonprofits in distressed areas.",
    requirements: "Must be in economically distressed area. Projects must support long-term economic development.",
    state: "ALL",
    region: "National",
    contactName: "EDA Public Works",
    contactEmail: "publicworks@eda.gov",
    agencyName: "U.S. Economic Development Administration",
    tags: '["EDA", "infrastructure", "public works", "economic development", "job creation"]',
    matchScore: 68,
    source: "eda.gov",
  },
  {
    title: "EDA Revolving Loan Fund Program",
    funder: "U.S. Economic Development Administration",
    description: "Capitalizes Revolving Loan Funds that provide gap financing to businesses that cannot otherwise obtain traditional bank financing.",
    amount: "$500,000 - $2,000,000",
    amountMin: 500000,
    amountMax: 2000000,
    deadline: null,
    url: "https://www.eda.gov/funding/programs/revolving-loan-fund",
    type: "federal",
    category: "economic_development",
    eligibility: "State and local governments, Indian tribes, and nonprofits that want to administer a revolving loan fund.",
    requirements: "Operators must lend to businesses that create jobs in distressed areas.",
    state: "ALL",
    region: "National",
    contactName: "EDA RLF Program",
    contactEmail: "rlf@eda.gov",
    agencyName: "U.S. Economic Development Administration",
    tags: '["EDA", "revolving loan", "small business", "gap financing"]',
    matchScore: 62,
    source: "eda.gov",
  },
  // Treasury/CDFI Programs
  {
    title: "CDFI Fund Financial Assistance Award",
    funder: "U.S. Department of the Treasury",
    description: "Provides financial assistance to certified Community Development Financial Institutions (CDFIs) to support their lending, investment, and financial services activities.",
    amount: "$50,000 - $2,000,000",
    amountMin: 50000,
    amountMax: 2000000,
    deadline: new Date("2025-06-30"),
    url: "https://www.cdfifund.gov/programs-training/programs/cdfi-program",
    type: "federal",
    category: "economic_development",
    eligibility: "Certified CDFIs including banks, credit unions, loan funds, and venture capital funds.",
    requirements: "Must be CDFI certified and serve low-income communities.",
    state: "ALL",
    region: "National",
    contactName: "CDFI Fund",
    contactEmail: "cdfihelp@cdfi.treas.gov",
    contactPhone: "202-653-0300",
    agencyName: "CDFI Fund, U.S. Treasury",
    tags: '["CDFI", "community development", "low-income", "financial services"]',
    matchScore: 58,
    source: "cdfifund.gov",
  },
  {
    title: "New Markets Tax Credit Program",
    funder: "U.S. Department of the Treasury",
    description: "Provides tax credit incentives to investors who make qualified equity investments in Community Development Entities (CDEs) that invest in low-income communities.",
    amount: "$5,000,000 - $100,000,000",
    amountMin: 5000000,
    amountMax: 100000000,
    deadline: new Date("2025-05-01"),
    url: "https://www.cdfifund.gov/programs-training/programs/new-markets-tax-credit",
    type: "federal",
    category: "economic_development",
    eligibility: "Community Development Entities serving low-income communities.",
    requirements: "Must invest in qualified low-income community businesses.",
    state: "ALL",
    region: "National",
    contactName: "NMTC Program",
    contactEmail: "nmtc@cdfi.treas.gov",
    agencyName: "CDFI Fund, U.S. Treasury",
    tags: '["NMTC", "tax credits", "community development", "investment"]',
    matchScore: 55,
    source: "cdfifund.gov",
  },
  // Women & Minority Business Programs
  {
    title: "SBA Women's Business Center (WBC) Grants",
    funder: "U.S. Small Business Administration",
    description: "Funding for organizations that provide entrepreneurial training and counseling to women-owned small businesses. Over 140 WBCs across the country.",
    amount: "$150,000 - $300,000",
    amountMin: 150000,
    amountMax: 300000,
    deadline: new Date("2025-07-15"),
    url: "https://www.sba.gov/local-assistance/resource-partners/womens-business-centers",
    type: "federal",
    category: "small_business",
    eligibility: "Nonprofit organizations providing services to women entrepreneurs.",
    requirements: "Must provide training and counseling services. Matching funds required.",
    state: "ALL",
    region: "National",
    contactName: "SBA Office of Women's Business Ownership",
    contactEmail: "owbo@sba.gov",
    agencyName: "U.S. Small Business Administration",
    tags: '["SBA", "women-owned", "entrepreneurship", "training", "counseling"]',
    matchScore: 78,
    source: "sba.gov",
  },
  {
    title: "Minority Business Development Agency Business Center Grants",
    funder: "U.S. Department of Commerce",
    description: "Funding for organizations that provide business development services to minority-owned businesses. Helps with access to capital, contracts, and markets.",
    amount: "$300,000 - $700,000",
    amountMin: 300000,
    amountMax: 700000,
    deadline: new Date("2025-04-30"),
    url: "https://www.mbda.gov/mbda-programs/business-centers",
    type: "federal",
    category: "small_business",
    eligibility: "Organizations providing business development services to minority entrepreneurs.",
    requirements: "Must serve minority business enterprises. Performance outcomes required.",
    state: "ALL",
    region: "National",
    contactName: "MBDA Business Centers",
    contactEmail: "info@mbda.gov",
    contactPhone: "1-888-324-1551",
    agencyName: "Minority Business Development Agency",
    tags: '["MBDA", "minority-owned", "business development", "capital access"]',
    matchScore: 76,
    source: "mbda.gov",
  },
  // Veterans Programs
  {
    title: "SBA Boots to Business Program",
    funder: "U.S. Small Business Administration",
    description: "Entrepreneurship training program for veterans as part of the Department of Defense's Transition Assistance Program. Free training and resources for veteran entrepreneurs.",
    amount: "Free training + counseling",
    amountMin: 0,
    amountMax: 10000,
    deadline: null,
    url: "https://www.sba.gov/sba-learning-platform/boots-business",
    type: "federal",
    category: "small_business",
    eligibility: "Transitioning service members, veterans, and military spouses.",
    requirements: "Must be veteran, transitioning service member, or military spouse.",
    state: "ALL",
    region: "National",
    contactName: "SBA Veterans Programs",
    contactEmail: "veteransbusiness@sba.gov",
    agencyName: "U.S. Small Business Administration",
    tags: '["SBA", "veterans", "military", "entrepreneurship", "training"]',
    matchScore: 90,
    source: "sba.gov",
  },
  {
    title: "Veteran Readiness and Employment (VR&E) Self-Employment Track",
    funder: "U.S. Department of Veterans Affairs",
    description: "Provides self-employment services to veterans with service-connected disabilities. Includes business plan development, training, and funding for starting a small business.",
    amount: "$25,000 - $100,000",
    amountMin: 25000,
    amountMax: 100000,
    deadline: null,
    url: "https://www.va.gov/careers-employment/vocational-rehabilitation/",
    type: "federal",
    category: "small_business",
    eligibility: "Veterans with service-connected disabilities rated at 10% or higher.",
    requirements: "Must have employment handicap and viable business plan.",
    state: "ALL",
    region: "National",
    contactName: "VA VR&E Program",
    contactEmail: "vetsuccess@va.gov",
    agencyName: "U.S. Department of Veterans Affairs",
    tags: '["VA", "veterans", "disability", "self-employment", "small business"]',
    matchScore: 80,
    source: "va.gov",
  },
  // Research & Innovation Programs
  {
    title: "NSF Partnerships for Innovation (PFI)",
    funder: "National Science Foundation",
    description: "Supports academic researchers in translating their discoveries into commercial products. Focus on technology transfer and entrepreneurship.",
    amount: "$250,000 - $550,000",
    amountMin: 250000,
    amountMax: 550000,
    deadline: new Date("2025-09-15"),
    url: "https://www.nsf.gov/eng/iip/pfi/index.jsp",
    type: "federal",
    category: "research",
    eligibility: "Universities with technology ready for commercial development.",
    requirements: "Must have proof-of-concept technology. Industry partner involvement encouraged.",
    state: "ALL",
    region: "National",
    contactName: "NSF PFI Program",
    contactEmail: "pfi@nsf.gov",
    agencyName: "National Science Foundation",
    tags: '["NSF", "technology transfer", "commercialization", "innovation", "university"]',
    matchScore: 72,
    source: "nsf.gov",
  },
  {
    title: "NSF I-Corps Program",
    funder: "National Science Foundation",
    description: "Prepares scientists and engineers to extend their focus beyond the university laboratory. Provides entrepreneurship training and funding for customer discovery.",
    amount: "$50,000",
    amountMin: 50000,
    amountMax: 50000,
    deadline: null,
    url: "https://www.nsf.gov/news/special_reports/i-corps/",
    type: "federal",
    category: "research",
    eligibility: "Teams with NSF-funded research and a technology with commercial potential.",
    requirements: "Must participate in 7-week entrepreneurship training program.",
    state: "ALL",
    region: "National",
    contactName: "NSF I-Corps Program",
    contactEmail: "icorps@nsf.gov",
    agencyName: "National Science Foundation",
    tags: '["NSF", "I-Corps", "entrepreneurship", "customer discovery", "commercialization"]',
    matchScore: 85,
    source: "nsf.gov",
  },
  // Manufacturing Programs
  {
    title: "Manufacturing Extension Partnership (MEP) Services",
    funder: "National Institute of Standards and Technology",
    description: "The MEP National Network provides small and medium-sized manufacturers with technical assistance, workforce development, and technology adoption support.",
    amount: "Subsidized services worth $10,000 - $100,000",
    amountMin: 10000,
    amountMax: 100000,
    deadline: null,
    url: "https://www.nist.gov/mep",
    type: "federal",
    category: "small_business",
    eligibility: "Small and medium-sized manufacturers (under 500 employees).",
    requirements: "Must be a U.S.-based manufacturer.",
    state: "ALL",
    region: "National",
    contactName: "NIST MEP Program",
    contactEmail: "mep@nist.gov",
    contactPhone: "301-975-5020",
    agencyName: "National Institute of Standards and Technology",
    tags: '["NIST", "manufacturing", "technical assistance", "workforce", "technology"]',
    matchScore: 75,
    source: "nist.gov",
  },
  // Export & Trade Programs
  {
    title: "SBA State Trade Expansion Program (STEP)",
    funder: "U.S. Small Business Administration",
    description: "Helps small businesses access export training, counseling, and trade mission support. Administered through state agencies to help small businesses enter global markets.",
    amount: "$5,000 - $50,000",
    amountMin: 5000,
    amountMax: 50000,
    deadline: new Date("2025-06-01"),
    url: "https://www.sba.gov/funding-programs/grants/state-trade-expansion-program-step",
    type: "federal",
    category: "small_business",
    eligibility: "Small businesses with products or services suitable for export.",
    requirements: "Must participate in export training. Product must be export-ready.",
    state: "ALL",
    region: "National",
    contactName: "SBA STEP Program",
    contactEmail: "step@sba.gov",
    agencyName: "U.S. Small Business Administration",
    tags: '["SBA", "export", "international trade", "global markets"]',
    matchScore: 68,
    source: "sba.gov",
  },
  {
    title: "Export-Import Bank Working Capital Guarantee",
    funder: "Export-Import Bank of the United States",
    description: "Government-backed loan guarantees to help U.S. exporters obtain working capital from commercial lenders to fulfill export orders.",
    amount: "$500,000 - $50,000,000",
    amountMin: 500000,
    amountMax: 50000000,
    deadline: null,
    url: "https://www.exim.gov/what-we-do/working-capital",
    type: "federal",
    category: "small_business",
    eligibility: "U.S. companies with export orders or export-related inventory/accounts receivable.",
    requirements: "Must have confirmed export orders or export-related business activity.",
    state: "ALL",
    region: "National",
    contactName: "EXIM Bank",
    contactEmail: "info@exim.gov",
    contactPhone: "1-800-565-3946",
    agencyName: "Export-Import Bank of the United States",
    tags: '["EXIM", "export", "working capital", "loan guarantee", "international trade"]',
    matchScore: 65,
    source: "exim.gov",
  },
  // Disaster & Emergency Programs
  {
    title: "SBA Economic Injury Disaster Loan (EIDL)",
    funder: "U.S. Small Business Administration",
    description: "Low-interest loans to small businesses suffering substantial economic injury from a declared disaster. Provides working capital to help businesses survive.",
    amount: "Up to $2,000,000",
    amountMin: 5000,
    amountMax: 2000000,
    deadline: null,
    url: "https://www.sba.gov/funding-programs/disaster-assistance",
    type: "federal",
    category: "small_business",
    eligibility: "Small businesses in declared disaster areas.",
    requirements: "Must demonstrate economic injury from disaster. Credit check required.",
    state: "ALL",
    region: "National",
    contactName: "SBA Disaster Assistance",
    contactEmail: "disastercustomerservice@sba.gov",
    contactPhone: "1-800-659-2955",
    agencyName: "U.S. Small Business Administration",
    tags: '["SBA", "disaster", "emergency", "working capital", "recovery"]',
    matchScore: 70,
    source: "sba.gov",
  },
  // Technology & Cybersecurity Programs
  {
    title: "NIST Cybersecurity for Small Business",
    funder: "National Institute of Standards and Technology",
    description: "Free resources and training to help small businesses protect themselves from cybersecurity threats. Includes assessment tools and implementation guidance.",
    amount: "Free resources + training",
    amountMin: 0,
    amountMax: 25000,
    deadline: null,
    url: "https://www.nist.gov/itl/smallbusinesscyber",
    type: "federal",
    category: "technology",
    eligibility: "All small businesses.",
    requirements: "None - free resources available to all small businesses.",
    state: "ALL",
    region: "National",
    contactName: "NIST Small Business Cyber",
    contactEmail: "smallbizcyber@nist.gov",
    agencyName: "National Institute of Standards and Technology",
    tags: '["NIST", "cybersecurity", "security", "training", "small business"]',
    matchScore: 80,
    source: "nist.gov",
  },
  // Health & Social Services Programs
  {
    title: "HRSA Community Health Center Grant",
    funder: "Health Resources and Services Administration",
    description: "Funding for health centers providing primary care services in underserved communities. Supports operational costs, facility improvements, and service expansion.",
    amount: "$500,000 - $5,000,000",
    amountMin: 500000,
    amountMax: 5000000,
    deadline: new Date("2025-03-31"),
    url: "https://www.hrsa.gov/grants/health-centers",
    type: "federal",
    category: "health",
    eligibility: "Federally Qualified Health Centers (FQHCs) and look-alikes.",
    requirements: "Must serve medically underserved area or population.",
    state: "ALL",
    region: "National",
    contactName: "HRSA Bureau of Primary Health Care",
    contactEmail: "healthcenters@hrsa.gov",
    agencyName: "Health Resources and Services Administration",
    tags: '["HRSA", "health center", "primary care", "underserved", "community health"]',
    matchScore: 55,
    source: "hrsa.gov",
  },
  // Education & Training Programs
  {
    title: "Department of Labor YouthBuild Grants",
    funder: "U.S. Department of Labor",
    description: "Grants for programs that help at-risk youth ages 16-24 obtain education and employment skills while building affordable housing in their communities.",
    amount: "$700,000 - $1,500,000",
    amountMin: 700000,
    amountMax: 1500000,
    deadline: new Date("2025-05-15"),
    url: "https://www.dol.gov/agencies/eta/youth/youthbuild",
    type: "federal",
    category: "workforce",
    eligibility: "Nonprofits, public agencies, and community colleges.",
    requirements: "Must serve disconnected youth. Construction training component required.",
    state: "ALL",
    region: "National",
    contactName: "DOL YouthBuild",
    contactEmail: "youthbuild@dol.gov",
    agencyName: "U.S. Department of Labor",
    tags: '["DOL", "youth", "workforce", "construction", "education"]',
    matchScore: 60,
    source: "dol.gov",
  },
  {
    title: "Department of Labor Apprenticeship Program Grants",
    funder: "U.S. Department of Labor",
    description: "Funding to expand and diversify Registered Apprenticeship programs. Focus on underrepresented populations and high-growth industries.",
    amount: "$500,000 - $5,000,000",
    amountMin: 500000,
    amountMax: 5000000,
    deadline: new Date("2025-06-30"),
    url: "https://www.apprenticeship.gov/",
    type: "federal",
    category: "workforce",
    eligibility: "State agencies, nonprofits, employers, and industry associations.",
    requirements: "Must create or expand Registered Apprenticeship programs.",
    state: "ALL",
    region: "National",
    contactName: "Office of Apprenticeship",
    contactEmail: "apprenticeship@dol.gov",
    agencyName: "U.S. Department of Labor",
    tags: '["DOL", "apprenticeship", "workforce", "training", "skilled trades"]',
    matchScore: 65,
    source: "dol.gov",
  },
  // Housing & Community Development
  {
    title: "HUD HOME Investment Partnerships Program",
    funder: "U.S. Department of Housing and Urban Development",
    description: "Formula grants to states and local governments to create affordable housing for low-income households. Can be used for construction, rehabilitation, or tenant-based rental assistance.",
    amount: "$500,000 - $50,000,000",
    amountMin: 500000,
    amountMax: 50000000,
    deadline: null,
    url: "https://www.hud.gov/program_offices/comm_planning/home",
    type: "federal",
    category: "economic_development",
    eligibility: "State and local governments (Participating Jurisdictions).",
    requirements: "Must serve households at or below 80% AMI. 15% set-aside for CHDOs.",
    state: "ALL",
    region: "National",
    contactName: "HUD HOME Program",
    contactEmail: "home@hud.gov",
    agencyName: "U.S. Department of Housing and Urban Development",
    tags: '["HUD", "housing", "affordable housing", "community development"]',
    matchScore: 52,
    source: "hud.gov",
  },
  // Additional Popular Programs
  {
    title: "AmeriCorps State and National Grants",
    funder: "AmeriCorps",
    description: "Funding for organizations to engage AmeriCorps members in national service. Members address critical community needs while earning education awards.",
    amount: "$100,000 - $2,000,000",
    amountMin: 100000,
    amountMax: 2000000,
    deadline: new Date("2025-05-20"),
    url: "https://americorps.gov/funding-opportunity/fy-2025-americorps-state-national-grants",
    type: "federal",
    category: "health",
    eligibility: "Nonprofits, educational institutions, state and local governments.",
    requirements: "Must engage AmeriCorps members in addressing community needs.",
    state: "ALL",
    region: "National",
    contactName: "AmeriCorps State and National",
    contactEmail: "grants@americorps.gov",
    agencyName: "AmeriCorps",
    tags: '["AmeriCorps", "national service", "volunteers", "community", "education"]',
    matchScore: 62,
    source: "americorps.gov",
  },
  {
    title: "NEA Grants for Arts Projects",
    funder: "National Endowment for the Arts",
    description: "Grants to support artistically excellent projects that celebrate our creativity and cultural heritage, engage communities, and advance arts learning opportunities.",
    amount: "$10,000 - $100,000",
    amountMin: 10000,
    amountMax: 100000,
    deadline: new Date("2025-02-06"),
    url: "https://www.arts.gov/grants/grants-for-arts-projects",
    type: "federal",
    category: "research",
    eligibility: "501(c)(3) nonprofit organizations, units of state or local government.",
    requirements: "Must support public engagement with or creation of excellent art.",
    state: "ALL",
    region: "National",
    contactName: "NEA Grants Office",
    contactEmail: "webmgr@arts.gov",
    contactPhone: "202-682-5400",
    agencyName: "National Endowment for the Arts",
    tags: '["NEA", "arts", "culture", "creative", "community"]',
    matchScore: 58,
    source: "arts.gov",
  },
  {
    title: "NEH Public Humanities Projects",
    funder: "National Endowment for the Humanities",
    description: "Grants to support a wide range of public humanities projects that bring the insights of humanities scholarship to the general public.",
    amount: "$1,000 - $400,000",
    amountMin: 1000,
    amountMax: 400000,
    deadline: new Date("2025-01-15"),
    url: "https://www.neh.gov/grants/public/public-humanities-projects",
    type: "federal",
    category: "research",
    eligibility: "Nonprofits, state and local governments, tribal governments, academic institutions.",
    requirements: "Must engage public audiences with humanities content.",
    state: "ALL",
    region: "National",
    contactName: "NEH Public Programs",
    contactEmail: "publicpgms@neh.gov",
    contactPhone: "202-606-8269",
    agencyName: "National Endowment for the Humanities",
    tags: '["NEH", "humanities", "education", "public programs", "culture"]',
    matchScore: 55,
    source: "neh.gov",
  },
  // State-based Government Programs (examples)
  {
    title: "Free Government Grants Database Access",
    funder: "Grants.gov",
    description: "The official federal grants portal providing free access to over 1,000 grant programs from 26 federal agencies. Search, apply, and track federal funding opportunities.",
    amount: "Varies by program",
    amountMin: 500,
    amountMax: 100000000,
    deadline: null,
    url: "https://www.grants.gov",
    type: "federal",
    category: "research",
    eligibility: "All eligible applicants - varies by specific grant program.",
    requirements: "Must register with SAM.gov and Grants.gov to apply.",
    state: "ALL",
    region: "National",
    contactName: "Grants.gov Support",
    contactEmail: "support@grants.gov",
    contactPhone: "1-800-518-4726",
    agencyName: "Grants.gov",
    tags: '["grants.gov", "federal grants", "database", "government funding"]',
    matchScore: 95,
    source: "grants.gov",
  },
  {
    title: "SAM.gov Entity Registration (Required for Grants)",
    funder: "U.S. General Services Administration",
    description: "Free registration required for any organization seeking federal grants or contracts. Entity registration in SAM.gov is mandatory for all federal funding applications.",
    amount: "Free registration (required)",
    amountMin: 0,
    amountMax: 0,
    deadline: null,
    url: "https://sam.gov",
    type: "federal",
    category: "research",
    eligibility: "All organizations seeking federal funding.",
    requirements: "Must obtain DUNS number and complete registration annually.",
    state: "ALL",
    region: "National",
    contactName: "SAM.gov Federal Service Desk",
    contactEmail: "support@sam.gov",
    contactPhone: "1-866-606-8220",
    agencyName: "U.S. General Services Administration",
    tags: '["SAM", "registration", "federal", "required", "DUNS"]',
    matchScore: 100,
    source: "sam.gov",
  },
];

async function main() {
  console.log("🌱 Adding Lesko-style government program grants...\n");

  console.log(`Creating ${leskoStyleGrants.length} additional grants...\n`);

  let created = 0;
  for (const grant of leskoStyleGrants) {
    // Check if grant with same title already exists
    const existing = await prisma.grant.findFirst({
      where: { title: grant.title },
    });

    if (!existing) {
      await prisma.grant.create({
        data: {
          ...grant,
          status: "discovered",
        },
      });
      created++;
      console.log(`✅ Created: ${grant.title}`);
    } else {
      console.log(`⏭️ Skipped (exists): ${grant.title}`);
    }
  }

  const totalGrants = await prisma.grant.count();

  console.log(`\n🎉 Successfully added ${created} new grants!`);
  console.log(`📊 Total grants in database: ${totalGrants}`);
}

main()
  .catch((e) => {
    console.error("Error seeding database:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
