import { Metadata } from "next";
import Link from "next/link";
import { Sparkles, ArrowLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "GrantPilot terms of service — usage terms, success fees, and grant guarantee conditions.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-950">
      <header className="border-b border-slate-800">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <Sparkles className="h-6 w-6 text-emerald-400" />
            <span className="font-bold text-white text-lg">GrantPilot</span>
          </Link>
          <Link href="/" className="text-slate-400 hover:text-white text-sm flex items-center gap-1 transition-colors duration-200">
            <ArrowLeft className="h-4 w-4" /> Back
          </Link>
        </div>
      </header>
      <main className="max-w-4xl mx-auto px-4 sm:px-6 py-12">
        <h1 className="text-3xl font-bold text-white mb-8">Terms of Service</h1>
        <div className="prose prose-invert prose-slate max-w-none space-y-6">
          <p className="text-slate-400 leading-7">
            Last updated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
          </p>
          <h2 className="text-xl font-bold text-white mt-8">1. Service Description</h2>
          <p className="text-slate-400 leading-7">
            GrantPilot is an AI-powered platform that helps organizations discover, match, and apply
            for grants. Our Smart Fill technology generates grant applications using your organization&apos;s
            data and optimizes them for each funder&apos;s scoring criteria.
          </p>
          <h2 className="text-xl font-bold text-white mt-8">2. Success Fees</h2>
          <p className="text-slate-400 leading-7">
            Paid plans include a success fee on grants won using GrantPilot&apos;s Smart Fill feature.
            The fee percentage varies by plan: Growth (5% on grants $10K+), Pro (3%), Organization (2%).
            Success fees are invoiced automatically when you report a grant award. You are required to
            report grant outcomes within 30 days of notification. Failure to report outcomes may result
            in estimated fees based on the grant&apos;s listed amount.
          </p>
          <h2 className="text-xl font-bold text-white mt-8">3. Grant Guarantee</h2>
          <p className="text-slate-400 leading-7">
            Pro and Organization plans include the Grant Guarantee: if you don&apos;t win a grant within
            12 months of subscribing, we&apos;ll extend your subscription 3 months free. To qualify,
            you must submit at least 10 applications using Smart Fill during the 12-month period.
            The guarantee does not apply to grants where the applicant was deemed ineligible.
          </p>
          <h2 className="text-xl font-bold text-white mt-8">4. AI-Generated Content</h2>
          <p className="text-slate-400 leading-7">
            Grant applications generated by Smart Fill are drafts. You are responsible for reviewing
            all content before submission. GrantPilot does not guarantee the accuracy of AI-generated
            content. You retain ownership of all content in your Content Library and generated applications.
          </p>
          <h2 className="text-xl font-bold text-white mt-8">5. Subscription and Billing</h2>
          <p className="text-slate-400 leading-7">
            Subscriptions are billed monthly or annually. You may upgrade or downgrade at any time.
            Downgrades take effect at the end of the current billing period. Refunds are not provided
            for partial months except under the Grant Guarantee terms.
          </p>
          <h2 className="text-xl font-bold text-white mt-8">6. Contact</h2>
          <p className="text-slate-400 leading-7">
            Questions? Contact us at legal@grantpilot.ai.
          </p>
        </div>
      </main>
    </div>
  );
}
