import type { ScholarshipSource, ScrapedScholarship, ScholarshipFilters } from "./types";

export class CorporateScholarshipsSource implements ScholarshipSource {
  id = "corporate-scholarships";
  name = "Corporate Scholarship Programs";
  type = "corporate" as const;

  isEnabled(): boolean {
    return true;
  }

  async scrape(_filters?: ScholarshipFilters): Promise<ScrapedScholarship[]> {
    return CORPORATE_SCHOLARSHIPS;
  }
}

const CORPORATE_SCHOLARSHIPS: ScrapedScholarship[] = [
  {
    title: "Google Lime Scholarship",
    provider: "Google / Lime Connect",
    description:
      "The Google Lime Scholarship supports students with disabilities pursuing computer science or related degrees. Recipients receive $10,000 and an invitation to attend the annual Google Scholars' Retreat to connect with Google engineers.",
    amount: "$10,000",
    amountMin: 10000,
    amountMax: 10000,
    deadline: new Date("2026-03-31"),
    url: "https://buildyourfuture.withgoogle.com/scholarships/lime-scholarship",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate", "graduate"],
    fieldsOfStudy: ["computer science", "software engineering", "STEM", "technology"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 400,
    submissionMethod: "portal",
    portalUrl: "https://buildyourfuture.withgoogle.com/scholarships/lime-scholarship",
    tags: ["disability", "tech", "STEM", "Google", "computer-science", "diversity"],
    sourceId: "google-lime",
    sourceUrl: "https://buildyourfuture.withgoogle.com/scholarships/lime-scholarship",
  },
  {
    title: "Microsoft Disability Scholarship",
    provider: "Microsoft",
    description:
      "Microsoft awards scholarships to students with disabilities who are pursuing degrees in computer science or related STEM fields. Each scholarship is worth $5,000 and includes invitations to Microsoft events and mentorship opportunities.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2026-02-28"),
    url: "https://careers.microsoft.com/students/us/en/usscholarshipprogram",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate"],
    fieldsOfStudy: ["computer science", "engineering", "STEM", "mathematics"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 500,
    submissionMethod: "portal",
    portalUrl: "https://careers.microsoft.com/students/us/en/usscholarshipprogram",
    tags: ["disability", "tech", "STEM", "Microsoft", "computer-science", "diversity"],
    sourceId: "microsoft-disability",
    sourceUrl: "https://careers.microsoft.com/students/us/en/usscholarshipprogram",
  },
  {
    title: "Amazon Future Engineer Scholarship",
    provider: "Amazon",
    description:
      "Amazon Future Engineer awards $40,000 scholarships ($10,000/year) to high school seniors from underserved communities who plan to study computer science. Recipients also receive a guaranteed Amazon software engineering internship upon completion of freshman year.",
    amount: "$40,000 ($10,000/year)",
    amountMin: 10000,
    amountMax: 40000,
    deadline: new Date("2026-01-15"),
    url: "https://www.amazonfutureengineer.com/scholarships",
    scholarshipType: "merit-need",
    renewable: true,
    minGPA: 2.9,
    educationLevels: ["undergraduate"],
    fieldsOfStudy: ["computer science", "software engineering"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 600,
    submissionMethod: "portal",
    portalUrl: "https://www.amazonfutureengineer.com/scholarships",
    tags: ["tech", "computer-science", "Amazon", "internship", "underserved", "renewable"],
    sourceId: "amazon-future-engineer",
    sourceUrl: "https://www.amazonfutureengineer.com/scholarships",
  },
  {
    title: "Coca-Cola First Generation Scholarship",
    provider: "Coca-Cola Scholars Foundation",
    description:
      "The Coca-Cola Scholars Foundation awards $20,000 to first-generation college students demonstrating leadership, community involvement, and academic achievement. Recipients join an elite network of Coke Scholars across the country.",
    amount: "$20,000",
    amountMin: 20000,
    amountMax: 20000,
    deadline: new Date("2025-10-31"),
    url: "https://www.coca-colascholarsfoundation.org",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 350,
    submissionMethod: "portal",
    portalUrl: "https://www.coca-colascholarsfoundation.org/apply/",
    tags: ["first-generation", "leadership", "community-service", "Coca-Cola", "merit"],
    sourceId: "coca-cola-first-gen",
    sourceUrl: "https://www.coca-colascholarsfoundation.org",
  },
  {
    title: "Burger King Scholars Program",
    provider: "Burger King McLamore Foundation",
    description:
      "The Burger King Scholars Program awards scholarships ranging from $1,000 to $50,000 to Burger King employees, their spouses and dependents, and high school seniors. The program demonstrates BK's commitment to supporting education in its communities.",
    amount: "$1,000–$50,000",
    amountMin: 1000,
    amountMax: 50000,
    deadline: new Date("2026-03-01"),
    url: "https://bkmclamorefoundation.org/who-we-are/scholarships/",
    scholarshipType: "merit-need",
    renewable: false,
    minGPA: 2.5,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 600,
    submissionMethod: "portal",
    portalUrl: "https://bkmclamorefoundation.org/who-we-are/scholarships/",
    tags: ["fast-food", "employee", "community", "Burger-King", "merit-need"],
    sourceId: "burger-king-scholars",
    sourceUrl: "https://bkmclamorefoundation.org",
  },
  {
    title: "Taco Bell Live Más Scholarship",
    provider: "Taco Bell Foundation",
    description:
      "The Taco Bell Foundation's Live Más Scholarship rewards passionate and creative young people for how they make an impact in the world. Awards of up to $25,000 go toward pursuing higher education or a creative endeavor.",
    amount: "Up to $25,000",
    amountMin: 5000,
    amountMax: 25000,
    deadline: new Date("2026-02-28"),
    url: "https://www.tacobellfoundation.org/live-mas-scholarship/",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 0,
    educationLevels: ["undergraduate", "vocational", "trade-school"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayPrompt: "Describe your passion and how it shapes your future",
    essayWordLimit: 500,
    submissionMethod: "portal",
    portalUrl: "https://www.tacobellfoundation.org/live-mas-scholarship/",
    tags: ["passion", "creativity", "Taco-Bell", "community-impact", "no-minimum-GPA"],
    sourceId: "taco-bell-live-mas",
    sourceUrl: "https://www.tacobellfoundation.org",
  },
  {
    title: "FedEx Scholarship Program",
    provider: "FedEx",
    description:
      "FedEx supports employees and their families through the FedEx Scholarship Program, providing $5,000 awards for higher education. Recipients demonstrate academic merit, leadership potential, and a commitment to community service.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2026-04-01"),
    url: "https://about.van.fedex.com/blog/fedex-scholarships-for-employees-and-their-families/",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 500,
    submissionMethod: "portal",
    tags: ["employee", "family", "logistics", "FedEx", "leadership"],
    sourceId: "fedex-scholarship",
    sourceUrl: "https://about.van.fedex.com",
  },
  {
    title: "Starbucks College Achievement Plan",
    provider: "Starbucks / Arizona State University",
    description:
      "The Starbucks College Achievement Plan provides eligible Starbucks partners (employees) with full tuition coverage toward an online bachelor's degree at Arizona State University. This benefit covers all four years of a first-time bachelor's degree at ASU Online.",
    amount: "Full tuition (varies)",
    amountMin: 8000,
    amountMax: 40000,
    deadline: new Date("2026-12-31"),
    url: "https://www.starbucks.com/careers/working-at-starbucks/education/",
    scholarshipType: "employee-benefit",
    renewable: true,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    eligibilityText:
      "Must be employed as a Starbucks partner (employee) working at least 20 hours/week at a U.S. company-operated store or support center.",
    essayRequired: false,
    submissionMethod: "portal",
    portalUrl: "https://www.starbucks.com/careers/working-at-starbucks/education/",
    tags: ["employee-benefit", "ASU", "online-degree", "Starbucks", "full-tuition", "renewable"],
    sourceId: "starbucks-cap",
    sourceUrl: "https://www.starbucks.com/careers/working-at-starbucks/education/",
  },
  {
    title: "Apple HBCU Founders Scholarship",
    provider: "Apple",
    description:
      "Apple's HBCU Founders Scholarship supports exceptional students at Historically Black Colleges and Universities who are pursuing degrees in technology, business, or entrepreneurship. Recipients receive $25,000 and mentorship from Apple professionals.",
    amount: "$25,000",
    amountMin: 25000,
    amountMax: 25000,
    deadline: new Date("2026-01-31"),
    url: "https://www.apple.com/diversity/",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.2,
    educationLevels: ["undergraduate"],
    fieldsOfStudy: ["technology", "business", "entrepreneurship", "computer science", "engineering"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 700,
    submissionMethod: "portal",
    tags: ["HBCU", "African-American", "tech", "entrepreneurship", "Apple", "diversity"],
    sourceId: "apple-hbcu",
    sourceUrl: "https://www.apple.com/diversity/",
  },
  {
    title: "Intel Rising Star Scholarship",
    provider: "Intel",
    description:
      "Intel's Rising Star Scholarship awards $10,000 to students from underrepresented groups pursuing degrees in engineering, computer science, or related STEM fields. Recipients are recognized at an annual Intel awards event and gain exposure to Intel's innovation ecosystem.",
    amount: "$10,000",
    amountMin: 10000,
    amountMax: 10000,
    deadline: new Date("2026-04-15"),
    url: "https://www.intel.com/content/www/us/en/diversity/intel-rising-stars-scholarship.html",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate", "graduate"],
    fieldsOfStudy: ["computer science", "engineering", "electrical engineering", "STEM"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 500,
    submissionMethod: "portal",
    portalUrl: "https://www.intel.com/content/www/us/en/diversity/intel-rising-stars-scholarship.html",
    tags: ["STEM", "tech", "Intel", "diversity", "underrepresented", "engineering"],
    sourceId: "intel-rising-star",
    sourceUrl: "https://www.intel.com/content/www/us/en/diversity/intel-rising-stars-scholarship.html",
  },
  {
    title: "Bank of America Student Leaders Scholarship",
    provider: "Bank of America",
    description:
      "The Bank of America Student Leaders Program identifies and develops students who are committed to building stronger communities. Selected students receive a paid internship at a local nonprofit, attend a leadership summit in Washington D.C., and earn a $5,000 scholarship.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2026-01-31"),
    url: "https://about.bankofamerica.com/en/making-an-impact/student-leaders",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 400,
    submissionMethod: "portal",
    tags: ["leadership", "community-service", "Bank-of-America", "nonprofit", "internship"],
    sourceId: "bofa-student-leaders",
    sourceUrl: "https://about.bankofamerica.com/en/making-an-impact/student-leaders",
  },
  {
    title: "Walmart Associate Scholarship",
    provider: "Walmart Foundation",
    description:
      "The Walmart Associate Scholarship Program provides financial assistance to Walmart associates and their dependents. Awards of up to $16,000 over four years support employees and family members pursuing undergraduate degrees.",
    amount: "Up to $16,000 total",
    amountMin: 2000,
    amountMax: 16000,
    deadline: new Date("2026-03-31"),
    url: "https://walmart.scholarsapply.org",
    scholarshipType: "merit-need",
    renewable: true,
    minGPA: 2.5,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 400,
    submissionMethod: "portal",
    portalUrl: "https://walmart.scholarsapply.org",
    tags: ["employee", "family", "Walmart", "retail", "renewable", "need-based"],
    sourceId: "walmart-associate",
    sourceUrl: "https://walmart.scholarsapply.org",
  },
];
