import type { ScholarshipSource, ScrapedScholarship, ScholarshipFilters } from "./types";

export class CuratedDatabaseSource implements ScholarshipSource {
  id = "curated-database";
  name = "Curated Scholarship Database";
  type = "curated" as const;

  isEnabled(): boolean {
    return true;
  }

  async scrape(_filters?: ScholarshipFilters): Promise<ScrapedScholarship[]> {
    return CURATED_SCHOLARSHIPS;
  }
}

const CURATED_SCHOLARSHIPS: ScrapedScholarship[] = [
  // ── Major Scholarships ──────────────────────────────────────────────────────
  {
    title: "Gates Scholarship (formerly Gates Millennium Scholars)",
    provider: "Bill & Melinda Gates Foundation",
    description:
      "The Gates Scholarship selects 300 outstanding minority students each year to receive a full scholarship. It covers the full cost of attendance not already covered by other aid and is renewable through undergraduate and graduate study.",
    amount: "Up to $20,000/year",
    amountMin: 5000,
    amountMax: 20000,
    deadline: new Date("2026-01-15"),
    url: "https://www.thegatesscholarship.org",
    applicationUrl: "https://www.thegatesscholarship.org/scholarship",
    scholarshipType: "merit-need",
    renewable: true,
    minGPA: 3.3,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayPrompt: "Describe your leadership experience and community service",
    essayWordLimit: 1000,
    submissionMethod: "portal",
    portalUrl: "https://www.thegatesscholarship.org/scholarship",
    tags: ["minority", "need-based", "full-ride", "renewable", "leadership"],
    sourceId: "gates-scholarship",
    sourceUrl: "https://www.thegatesscholarship.org",
  },
  {
    title: "Jack Kent Cooke Foundation College Scholarship",
    provider: "Jack Kent Cooke Foundation",
    description:
      "The Jack Kent Cooke Foundation College Scholarship Program is an undergraduate scholarship for high-achieving students with financial need. Up to $55,000 per year is awarded to help students attend the nation's best colleges.",
    amount: "Up to $55,000/year",
    amountMin: 10000,
    amountMax: 55000,
    deadline: new Date("2025-11-20"),
    url: "https://www.jkcf.org/our-scholarships/college-scholarship-program/",
    scholarshipType: "merit-need",
    renewable: true,
    minGPA: 3.5,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 1500,
    submissionMethod: "portal",
    tags: ["high-achieving", "need-based", "renewable", "prestigious"],
    sourceId: "jkc-college",
    sourceUrl: "https://www.jkcf.org",
  },
  {
    title: "Coca-Cola Scholars Program",
    provider: "Coca-Cola Scholars Foundation",
    description:
      "One of the most prestigious achievement-based scholarships in the nation, the Coca-Cola Scholars Program awards 150 students $20,000 each year. It recognizes students who lead and serve in their schools and communities.",
    amount: "$20,000",
    amountMin: 20000,
    amountMax: 20000,
    deadline: new Date("2025-10-31"),
    url: "https://www.coca-colascholarsfoundation.org",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 350,
    submissionMethod: "portal",
    tags: ["leadership", "community-service", "prestigious", "high-school-senior"],
    sourceId: "coca-cola-scholars",
    sourceUrl: "https://www.coca-colascholarsfoundation.org",
  },
  {
    title: "QuestBridge National College Match",
    provider: "QuestBridge",
    description:
      "QuestBridge matches top low-income students with full four-year scholarships to the nation's best colleges. The National College Match scholarship covers tuition, room and board, books, and travel expenses at partner colleges.",
    amount: "Up to $40,000/year (full ride)",
    amountMin: 30000,
    amountMax: 40000,
    deadline: new Date("2025-09-26"),
    url: "https://www.questbridge.org/college-prep/national-college-match",
    scholarshipType: "need-based",
    renewable: true,
    minGPA: 3.7,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 700,
    submissionMethod: "portal",
    tags: ["low-income", "full-ride", "prestigious", "college-match"],
    sourceId: "questbridge-ncm",
    sourceUrl: "https://www.questbridge.org",
  },
  {
    title: "Dell Scholars Program",
    provider: "Michael & Susan Dell Foundation",
    description:
      "The Dell Scholars Program provides $20,000 scholarships and ongoing support to hardworking students who demonstrate the potential to succeed. Recipients receive a laptop, textbook credits, and dedicated case management.",
    amount: "$20,000",
    amountMin: 20000,
    amountMax: 20000,
    deadline: new Date("2026-01-15"),
    url: "https://www.dellscholars.org",
    scholarshipType: "merit-need",
    renewable: true,
    minGPA: 2.4,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 750,
    submissionMethod: "portal",
    tags: ["need-based", "first-generation", "renewable", "support-services"],
    sourceId: "dell-scholars",
    sourceUrl: "https://www.dellscholars.org",
  },
  {
    title: "Elks National Foundation Most Valuable Student Scholarship",
    provider: "Elks National Foundation",
    description:
      "The Elks National Foundation awards over $3.6 million in scholarships to 500 students annually through its Most Valuable Student competition. Awards range from $4,000 to $20,000 for four-year use.",
    amount: "Up to $20,000",
    amountMin: 4000,
    amountMax: 20000,
    deadline: new Date("2025-11-15"),
    url: "https://www.elks.org/scholars/scholarships/MVS.cfm",
    scholarshipType: "merit",
    renewable: true,
    minGPA: 0,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen",
    essayRequired: true,
    essayWordLimit: 500,
    submissionMethod: "portal",
    tags: ["merit", "leadership", "community-service", "renewable"],
    sourceId: "elks-mvs",
    sourceUrl: "https://www.elks.org/scholars",
  },
  {
    title: "Rotary Peace Fellowship",
    provider: "Rotary Foundation",
    description:
      "Rotary Peace Fellowships fund master's degrees or professional development certificates in peace and conflict resolution studies. Fellows join a network of more than 1,600 alumni working around the world to promote peace.",
    amount: "Up to $30,000/year",
    amountMin: 20000,
    amountMax: 30000,
    deadline: new Date("2025-11-15"),
    url: "https://www.rotary.org/en/our-programs/peace-fellowships",
    scholarshipType: "fellowship",
    renewable: true,
    educationLevels: ["graduate"],
    fieldsOfStudy: ["peace studies", "conflict resolution", "international relations", "social sciences"],
    citizenshipRequired: "Any nationality",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["peace", "conflict-resolution", "international", "fellowship"],
    sourceId: "rotary-peace",
    sourceUrl: "https://www.rotary.org",
  },
  {
    title: "United Negro College Fund (UNCF) Scholarships",
    provider: "United Negro College Fund",
    description:
      "UNCF administers more than 400 scholarship programs that award over $100 million to African American students annually. Awards support students attending UNCF member HBCUs and other accredited colleges.",
    amount: "Up to $25,000",
    amountMin: 2000,
    amountMax: 25000,
    deadline: new Date("2026-03-01"),
    url: "https://uncf.org/scholarships",
    scholarshipType: "need-based",
    renewable: true,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["African-American", "HBCU", "need-based", "minority"],
    sourceId: "uncf",
    sourceUrl: "https://uncf.org",
  },
  {
    title: "Hispanic Scholarship Fund",
    provider: "Hispanic Scholarship Fund",
    description:
      "The Hispanic Scholarship Fund awards merit-based scholarships of $500–$5,000 to Hispanic American students each year. HSF provides financial aid and support to help students succeed in college and career.",
    amount: "$500–$5,000",
    amountMin: 500,
    amountMax: 5000,
    deadline: new Date("2026-02-15"),
    url: "https://www.hsf.net/scholarship",
    scholarshipType: "merit-need",
    renewable: true,
    minGPA: 3.0,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["Hispanic", "Latino", "minority", "merit-need"],
    sourceId: "hsf",
    sourceUrl: "https://www.hsf.net",
  },
  {
    title: "APIA Scholars Program",
    provider: "Asian Pacific Islander American Scholarship Fund",
    description:
      "APIA Scholars awards merit and need-based scholarships to Asian Pacific Islander American students. Scholarships range from $2,500 to $20,000 and come with access to mentoring and professional development.",
    amount: "$2,500–$20,000",
    amountMin: 2500,
    amountMax: 20000,
    deadline: new Date("2026-01-12"),
    url: "https://apiascholars.org/scholarship/apia-scholarship/",
    scholarshipType: "merit-need",
    renewable: true,
    minGPA: 2.7,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["Asian-Pacific-Islander", "minority", "merit-need"],
    sourceId: "apia-scholars",
    sourceUrl: "https://apiascholars.org",
  },
  {
    title: "Ron Brown Scholar Program",
    provider: "Ron Brown Scholar Fund",
    description:
      "The Ron Brown Scholar Program identifies African American high school seniors who excel academically, exhibit leadership, participate in community service, and demonstrate financial need. Scholars receive $40,000 over four years.",
    amount: "$40,000 ($10,000/year)",
    amountMin: 10000,
    amountMax: 40000,
    deadline: new Date("2025-11-01"),
    url: "https://www.ronbrown.org",
    scholarshipType: "merit-need",
    renewable: true,
    minGPA: 3.5,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen",
    essayRequired: true,
    essayWordLimit: 500,
    submissionMethod: "portal",
    tags: ["African-American", "leadership", "community-service", "need-based"],
    sourceId: "ron-brown",
    sourceUrl: "https://www.ronbrown.org",
  },
  {
    title: "Horatio Alger Scholarship",
    provider: "Horatio Alger Association of Distinguished Americans",
    description:
      "Horatio Alger Scholarships support students who have overcome adversity and demonstrate integrity, perseverance, and a commitment to higher education. Awards of $25,000 support students attending their home state institutions.",
    amount: "$25,000",
    amountMin: 25000,
    amountMax: 25000,
    deadline: new Date("2025-10-25"),
    url: "https://scholars.horatioalger.org",
    scholarshipType: "merit-need",
    renewable: false,
    minGPA: 2.0,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["adversity", "perseverance", "need-based", "integrity"],
    sourceId: "horatio-alger",
    sourceUrl: "https://scholars.horatioalger.org",
  },
  {
    title: "Goldwater Scholarship",
    provider: "Barry Goldwater Scholarship and Excellence in Education Foundation",
    description:
      "The Goldwater Scholarship is the preeminent undergraduate award for STEM students intending to pursue research careers. Up to $7,500 per year is awarded to sophomores and juniors with outstanding research potential.",
    amount: "Up to $7,500/year",
    amountMin: 5000,
    amountMax: 7500,
    deadline: new Date("2026-01-31"),
    url: "https://goldwater.scholarsapply.org",
    scholarshipType: "merit",
    renewable: true,
    minGPA: 3.7,
    educationLevels: ["undergraduate"],
    fieldsOfStudy: ["STEM", "science", "technology", "engineering", "mathematics", "research"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 600,
    submissionMethod: "portal",
    tags: ["STEM", "research", "prestigious", "undergraduate", "academic-excellence"],
    sourceId: "goldwater",
    sourceUrl: "https://goldwater.scholarsapply.org",
  },
  {
    title: "Truman Scholarship",
    provider: "Harry S. Truman Scholarship Foundation",
    description:
      "The Truman Scholarship supports college juniors committed to careers in government, nonprofit, or advocacy. Up to $30,000 funds the final year of undergraduate study and graduate education.",
    amount: "Up to $30,000",
    amountMin: 10000,
    amountMax: 30000,
    deadline: new Date("2026-02-01"),
    url: "https://www.truman.gov/are-you-a-candidate/",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.5,
    educationLevels: ["undergraduate", "graduate"],
    fieldsOfStudy: ["public policy", "government", "nonprofit management", "social work", "advocacy"],
    citizenshipRequired: "US Citizen",
    essayRequired: true,
    essayWordLimit: 600,
    submissionMethod: "portal",
    tags: ["public-service", "leadership", "government", "prestigious"],
    sourceId: "truman",
    sourceUrl: "https://www.truman.gov",
  },
  {
    title: "Marshall Scholarship",
    provider: "Marshall Aid Commemoration Commission",
    description:
      "Marshall Scholarships finance young Americans of high ability to study in the UK. Up to 50 scholarships are awarded annually, covering tuition, living costs, travel, and fees for two years of graduate study.",
    amount: "Up to $80,000",
    amountMin: 60000,
    amountMax: 80000,
    deadline: new Date("2025-10-01"),
    url: "https://www.marshallscholarship.org",
    scholarshipType: "merit",
    renewable: true,
    minGPA: 3.7,
    educationLevels: ["graduate"],
    citizenshipRequired: "US Citizen",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["UK-study", "prestigious", "international", "graduate", "full-funding"],
    sourceId: "marshall",
    sourceUrl: "https://www.marshallscholarship.org",
  },
  {
    title: "Rhodes Scholarship",
    provider: "Rhodes Trust",
    description:
      "The Rhodes Scholarship is the oldest and most prestigious international graduate scholarship, enabling exceptional students to study at the University of Oxford. It covers all expenses including university fees, personal stipend, and travel.",
    amount: "Up to $75,000",
    amountMin: 60000,
    amountMax: 75000,
    deadline: new Date("2025-10-01"),
    url: "https://www.rhodeshouse.ox.ac.uk/scholarships/the-rhodes-scholarship/",
    scholarshipType: "merit",
    renewable: true,
    minGPA: 3.8,
    educationLevels: ["graduate"],
    citizenshipRequired: "US Citizen",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["Oxford", "prestigious", "international", "leadership", "full-funding"],
    sourceId: "rhodes",
    sourceUrl: "https://www.rhodeshouse.ox.ac.uk",
  },
  {
    title: "Fulbright U.S. Student Program",
    provider: "U.S. Department of State / Institute of International Education",
    description:
      "The Fulbright Program is the flagship international educational exchange program sponsored by the U.S. government. Awards cover living stipend, health insurance, and travel for study, research, or English teaching abroad for one academic year.",
    amount: "Up to $40,000",
    amountMin: 20000,
    amountMax: 40000,
    deadline: new Date("2025-10-14"),
    url: "https://us.fulbrightonline.org",
    scholarshipType: "fellowship",
    renewable: false,
    educationLevels: ["graduate", "postgraduate"],
    citizenshipRequired: "US Citizen",
    essayRequired: true,
    essayWordLimit: 1000,
    submissionMethod: "portal",
    tags: ["international", "research", "teaching", "government-funded", "prestigious"],
    sourceId: "fulbright",
    sourceUrl: "https://us.fulbrightonline.org",
  },
  {
    title: "Schwarzman Scholars",
    provider: "Schwarzman College, Tsinghua University",
    description:
      "Schwarzman Scholars is a highly selective master's degree program at Tsinghua University designed for future global leaders. The fully funded one-year program covers all tuition, travel, room and board, and personal expenses.",
    amount: "Up to $75,000 (full funding)",
    amountMin: 60000,
    amountMax: 75000,
    deadline: new Date("2025-09-28"),
    url: "https://www.schwarzmanscholars.org",
    scholarshipType: "fellowship",
    renewable: false,
    minGPA: 3.5,
    educationLevels: ["graduate"],
    citizenshipRequired: "Any nationality",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["China", "global-leadership", "prestigious", "Tsinghua", "full-funding"],
    sourceId: "schwarzman",
    sourceUrl: "https://www.schwarzmanscholars.org",
  },
  {
    title: "Knight-Hennessy Scholars Program",
    provider: "Stanford University",
    description:
      "Knight-Hennessy Scholars is one of the world's largest fully endowed international graduate scholarship programs at Stanford University. It supports up to three years of graduate education, covering tuition, fees, and living stipend.",
    amount: "Up to $90,000/year",
    amountMin: 60000,
    amountMax: 90000,
    deadline: new Date("2025-10-09"),
    url: "https://knight-hennessy.stanford.edu",
    scholarshipType: "fellowship",
    renewable: true,
    educationLevels: ["graduate"],
    citizenshipRequired: "Any nationality",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["Stanford", "prestigious", "global-leadership", "full-funding", "international"],
    sourceId: "knight-hennessy",
    sourceUrl: "https://knight-hennessy.stanford.edu",
  },
  {
    title: "Google Generation Scholarship",
    provider: "Google",
    description:
      "The Google Generation Scholarship supports students in computer science or related technical fields who demonstrate academic excellence and leadership. Recipients receive $10,000 and an invitation to attend the annual Google Scholars' Retreat.",
    amount: "$10,000",
    amountMin: 10000,
    amountMax: 10000,
    deadline: new Date("2026-03-31"),
    url: "https://buildyourfuture.withgoogle.com/scholarships",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.2,
    educationLevels: ["undergraduate", "graduate"],
    fieldsOfStudy: ["computer science", "software engineering", "STEM", "technology"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 400,
    submissionMethod: "portal",
    tags: ["STEM", "tech", "Google", "computer-science", "leadership"],
    sourceId: "google-generation",
    sourceUrl: "https://buildyourfuture.withgoogle.com/scholarships",
  },

  // ── Niche / Unusual Scholarships ─────────────────────────────────────────────
  {
    title: "Tall Clubs International Student of the Year Scholarship",
    provider: "Tall Clubs International",
    description:
      "Tall Clubs International awards $1,000 scholarships to tall young people who exhibit exemplary character, scholarship, and participation in school and community activities. Applicants must meet height requirements (women 5'10\"+, men 6'2\"+).",
    amount: "$1,000",
    amountMin: 1000,
    amountMax: 1000,
    deadline: new Date("2026-03-01"),
    url: "https://www.tall.org/tci-scholarship/",
    scholarshipType: "merit",
    renewable: false,
    educationLevels: ["undergraduate"],
    essayRequired: true,
    essayWordLimit: 500,
    submissionMethod: "portal",
    tags: ["height", "unusual", "niche", "community"],
    sourceId: "tall-clubs",
    sourceUrl: "https://www.tall.org",
  },
  {
    title: "Duck Brand Stuck at Prom Scholarship",
    provider: "ShurTech Brands (Duck Brand)",
    description:
      "The Stuck at Prom Scholarship challenges couples to make creative prom attire entirely from Duck Brand duct tape. The winning couple receives a $10,000 scholarship split equally between them, with additional prizes for runners-up.",
    amount: "$10,000 (split)",
    amountMin: 5000,
    amountMax: 10000,
    deadline: new Date("2026-05-31"),
    url: "https://www.duckbrand.com/promotions/stuck-at-prom",
    scholarshipType: "creative",
    renewable: false,
    educationLevels: ["undergraduate"],
    essayRequired: false,
    submissionMethod: "portal",
    tags: ["creative", "unusual", "duct-tape", "prom", "craft", "niche"],
    sourceId: "duck-brand-prom",
    sourceUrl: "https://www.duckbrand.com/promotions/stuck-at-prom",
  },
  {
    title: "Vegetarian Resource Group Scholarship",
    provider: "Vegetarian Resource Group",
    description:
      "VRG awards scholarships of up to $10,000 to graduating high school students who have promoted vegetarianism in their schools and communities. Recipients demonstrate a commitment to vegetarian principles and environmental awareness.",
    amount: "Up to $10,000",
    amountMin: 5000,
    amountMax: 10000,
    deadline: new Date("2026-02-20"),
    url: "https://www.vrg.org/student/scholar.htm",
    scholarshipType: "merit",
    renewable: false,
    educationLevels: ["undergraduate"],
    essayRequired: true,
    essayWordLimit: 600,
    submissionMethod: "portal",
    tags: ["vegetarian", "environmental", "community", "unusual", "niche"],
    sourceId: "vrg-scholarship",
    sourceUrl: "https://www.vrg.org",
  },
  {
    title: "Zombie Apocalypse Scholarship",
    provider: "Unigo",
    description:
      "The Zombie Apocalypse Scholarship asks students to submit a creative essay describing their zombie apocalypse survival plan. This $2,000 award encourages creative thinking and quick decision-making skills in a fun way.",
    amount: "$2,000",
    amountMin: 2000,
    amountMax: 2000,
    deadline: new Date("2025-10-31"),
    url: "https://www.unigo.com/scholarships/all/zombie-apocalypse-scholarship",
    scholarshipType: "creative",
    renewable: false,
    educationLevels: ["undergraduate", "graduate"],
    essayRequired: true,
    essayPrompt: "If there was a zombie apocalypse, describe your survival plan",
    essayWordLimit: 250,
    submissionMethod: "portal",
    tags: ["creative", "unusual", "fun", "essay", "niche"],
    sourceId: "zombie-apocalypse",
    sourceUrl: "https://www.unigo.com",
  },
  {
    title: "$2,000 No Essay Scholarship",
    provider: "College Raptor / Niche",
    description:
      "The No Essay Scholarship is a monthly $2,000 award with no essay requirement. Students simply sign up and are entered into the monthly drawing. It is open to any current or future college student.",
    amount: "$2,000/month",
    amountMin: 2000,
    amountMax: 2000,
    deadline: new Date("2026-12-31"),
    url: "https://www.niche.com/colleges/scholarships/no-essay-scholarship/",
    scholarshipType: "lottery",
    renewable: false,
    educationLevels: ["undergraduate", "graduate"],
    essayRequired: false,
    submissionMethod: "portal",
    tags: ["no-essay", "monthly", "easy-apply", "rolling"],
    sourceId: "no-essay-2000",
    sourceUrl: "https://www.niche.com",
  },
  {
    title: "Frederick and Mary F. Beckley Left-Handed Scholarship",
    provider: "Juniata College",
    description:
      "Juniata College awards scholarships specifically to left-handed students demonstrating academic achievement and financial need. The scholarship honors the lefty experience in a predominantly right-handed world.",
    amount: "Up to $1,500",
    amountMin: 1000,
    amountMax: 1500,
    deadline: new Date("2026-05-01"),
    url: "https://www.juniata.edu/offices/financial-aid/scholarships/",
    scholarshipType: "merit-need",
    renewable: true,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["left-handed", "unusual", "niche", "need-based"],
    sourceId: "left-handed-juniata",
    sourceUrl: "https://www.juniata.edu",
  },
  {
    title: "National Potato Council Scholarship",
    provider: "National Potato Council",
    description:
      "The National Potato Council awards annual scholarships to graduate students pursuing agriculture-related fields in potato production, processing, marketing, or research. Awardees receive $10,000 toward their advanced degree.",
    amount: "$10,000",
    amountMin: 10000,
    amountMax: 10000,
    deadline: new Date("2026-06-01"),
    url: "https://nationalpotatocouncil.org/educational-programs/scholarship/",
    scholarshipType: "merit",
    renewable: false,
    educationLevels: ["graduate"],
    fieldsOfStudy: ["agriculture", "food science", "agronomy", "horticulture"],
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["agriculture", "food science", "potato", "unusual", "niche", "graduate"],
    sourceId: "national-potato-council",
    sourceUrl: "https://nationalpotatocouncil.org",
  },
  {
    title: "Blogging Scholarship",
    provider: "College Scholarships",
    description:
      "The Blogging Scholarship recognizes students with outstanding blogs that demonstrate quality writing, creativity, and audience engagement. The $5,000 award encourages digital literacy and online communication skills.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2025-11-30"),
    url: "https://www.collegescholarships.org/scholarships/blogging.htm",
    scholarshipType: "merit",
    renewable: false,
    educationLevels: ["undergraduate", "graduate"],
    fieldsOfStudy: ["communications", "journalism", "digital media", "writing"],
    essayRequired: false,
    submissionMethod: "portal",
    tags: ["blogging", "writing", "digital-media", "creative", "niche"],
    sourceId: "blogging-scholarship",
    sourceUrl: "https://www.collegescholarships.org",
  },
  {
    title: "Society of Women Engineers Scholarship",
    provider: "Society of Women Engineers",
    description:
      "SWE awards scholarships to women pursuing STEM degrees at accredited U.S. universities. More than $1.5 million in scholarships are awarded annually, ranging from $1,000 to $17,000, supporting undergraduate and graduate women in engineering.",
    amount: "$1,000–$17,000",
    amountMin: 1000,
    amountMax: 17000,
    deadline: new Date("2025-05-01"),
    url: "https://swe.org/scholarships/",
    scholarshipType: "merit",
    renewable: true,
    minGPA: 3.0,
    educationLevels: ["undergraduate", "graduate"],
    fieldsOfStudy: ["engineering", "STEM", "technology", "computer science"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 500,
    submissionMethod: "portal",
    tags: ["women", "STEM", "engineering", "diversity", "SWE"],
    sourceId: "swe-scholarship",
    sourceUrl: "https://swe.org",
  },
  {
    title: "Duck Brand Duct Tape Scholarship",
    provider: "ShurTech Brands",
    description:
      "Students who create a prom outfit made entirely from Duck Brand duct tape compete for this $10,000 scholarship. Submissions are judged on originality, workmanship, and use of color and patterned duct tape.",
    amount: "$10,000",
    amountMin: 10000,
    amountMax: 10000,
    deadline: new Date("2026-05-31"),
    url: "https://www.duckbrand.com/promotions/stuck-at-prom",
    scholarshipType: "creative",
    renewable: false,
    educationLevels: ["undergraduate"],
    essayRequired: false,
    submissionMethod: "portal",
    tags: ["creative", "duct-tape", "unusual", "niche", "craft"],
    sourceId: "duck-tape-scholarship",
    sourceUrl: "https://www.duckbrand.com",
  },

  // ── Medical / Professional Scholarships ─────────────────────────────────────
  {
    title: "AAMC FIRST Scholarship",
    provider: "Association of American Medical Colleges",
    description:
      "AAMC supports aspiring medical students through the Fee Assistance Program and FIRST scholarship opportunities. Awards help underrepresented minorities and financially disadvantaged applicants cover MCAT fees and application costs, ranging from $10,000 to $50,000.",
    amount: "$10,000–$50,000",
    amountMin: 10000,
    amountMax: 50000,
    deadline: new Date("2026-01-31"),
    url: "https://www.aamc.org/services/fee-assistance-program",
    scholarshipType: "need-based",
    educationLevels: ["graduate", "professional"],
    fieldsOfStudy: ["medicine", "pre-med", "health sciences"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["medical", "pre-med", "health", "minority", "need-based"],
    sourceId: "aamc-first",
    sourceUrl: "https://www.aamc.org",
  },
  {
    title: "AMA Foundation Physicians of Tomorrow Scholarship",
    provider: "American Medical Association Foundation",
    description:
      "The AMA Foundation Physicians of Tomorrow Scholarship awards $10,000 to medical students demonstrating academic excellence and financial need. The award recognizes students who show the qualities and dedication of tomorrow's leading physicians.",
    amount: "$10,000",
    amountMin: 10000,
    amountMax: 10000,
    deadline: new Date("2026-04-30"),
    url: "https://www.ama-assn.org/about/ama-foundation/physicians-tomorrow-scholarship",
    scholarshipType: "merit-need",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["professional"],
    fieldsOfStudy: ["medicine", "medical school"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["medicine", "medical-school", "AMA", "need-based"],
    sourceId: "ama-foundation",
    sourceUrl: "https://www.ama-assn.org",
  },
  {
    title: "ABA Law School Scholarship (Legal Opportunity Scholarship Fund)",
    provider: "American Bar Association",
    description:
      "The ABA Legal Opportunity Scholarship Fund awards $15,000 to first-year law students from underrepresented racial and ethnic minority groups. Recipients demonstrate commitment to increasing diversity in the legal profession.",
    amount: "$15,000",
    amountMin: 15000,
    amountMax: 15000,
    deadline: new Date("2026-03-01"),
    url: "https://www.americanbar.org/groups/diversity/racial_ethnicity_diversity/initiatives/LOSF/",
    scholarshipType: "merit-need",
    renewable: true,
    educationLevels: ["professional"],
    fieldsOfStudy: ["law", "legal studies"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["law", "legal", "diversity", "minority", "ABA"],
    sourceId: "aba-losf",
    sourceUrl: "https://www.americanbar.org",
  },
  {
    title: "Tylenol Future Care Scholarship",
    provider: "Johnson & Johnson / Tylenol",
    description:
      "The Tylenol Future Care Scholarship awards up to $10,000 to students pursuing careers in health care. The scholarship supports undergraduate and graduate students in nursing, pharmacy, public health, medicine, and other health-related fields.",
    amount: "Up to $10,000",
    amountMin: 5000,
    amountMax: 10000,
    deadline: new Date("2026-05-31"),
    url: "https://www.tylenol.com/news/scholarship",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate", "graduate"],
    fieldsOfStudy: ["nursing", "pharmacy", "public health", "medicine", "health sciences"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 500,
    submissionMethod: "portal",
    tags: ["healthcare", "nursing", "pharmacy", "medicine", "Tylenol"],
    sourceId: "tylenol-future-care",
    sourceUrl: "https://www.tylenol.com",
  },
  {
    title: "HRSA Health Careers Scholarship",
    provider: "Health Resources & Services Administration",
    description:
      "HRSA scholarships fund health professions students who commit to serving in Health Professional Shortage Areas (HPSAs) after graduation. The scholarship covers tuition, fees, and a monthly living stipend up to $40,000/year.",
    amount: "Up to $40,000/year",
    amountMin: 20000,
    amountMax: 40000,
    deadline: new Date("2026-03-31"),
    url: "https://bhw.hrsa.gov/scholarships-loans-scholarships",
    scholarshipType: "service-obligation",
    renewable: true,
    educationLevels: ["graduate", "professional"],
    fieldsOfStudy: ["medicine", "nursing", "dentistry", "mental health", "primary care"],
    citizenshipRequired: "US Citizen",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["health-shortage-area", "service-obligation", "government", "healthcare"],
    sourceId: "hrsa-health-careers",
    sourceUrl: "https://bhw.hrsa.gov",
  },
  {
    title: "National Health Service Corps Scholarship",
    provider: "Health Resources & Services Administration (HRSA)",
    description:
      "The NHSC Scholarship Program pays for health professions school costs in exchange for service in a health professional shortage area. It covers tuition, required fees, and a living stipend, worth up to $50,000/year at some institutions.",
    amount: "Up to $50,000/year",
    amountMin: 30000,
    amountMax: 50000,
    deadline: new Date("2026-04-15"),
    url: "https://nhsc.hrsa.gov/scholarships",
    scholarshipType: "service-obligation",
    renewable: true,
    educationLevels: ["graduate", "professional"],
    fieldsOfStudy: ["primary care", "medicine", "dentistry", "nursing", "mental health"],
    citizenshipRequired: "US Citizen",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["NHSC", "service-obligation", "primary-care", "government", "health-shortage"],
    sourceId: "nhsc-scholarship",
    sourceUrl: "https://nhsc.hrsa.gov",
  },
  {
    title: "PhRMA Foundation Predoctoral Fellowship in Pharmacology",
    provider: "Pharmaceutical Research and Manufacturers of America Foundation",
    description:
      "The PhRMA Foundation awards $20,000 predoctoral fellowships to support students conducting innovative pharmaceutical research. Awards support training in pharmacology/toxicology, pharmaceutics, informatics, drug delivery, and health outcomes.",
    amount: "$20,000",
    amountMin: 20000,
    amountMax: 20000,
    deadline: new Date("2026-02-01"),
    url: "https://www.phrmafoundation.org/awards-programs/",
    scholarshipType: "fellowship",
    renewable: true,
    educationLevels: ["graduate"],
    fieldsOfStudy: ["pharmacology", "pharmacy", "pharmaceutical sciences", "toxicology"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["pharmaceutical", "pharmacology", "research", "graduate", "fellowship"],
    sourceId: "phrma-foundation",
    sourceUrl: "https://www.phrmafoundation.org",
  },
  {
    title: "Herbert W. Nickens Medical Student Scholarships",
    provider: "Association of American Medical Colleges",
    description:
      "The Herbert W. Nickens Medical Student Scholarships honor outstanding entering third-year medical students who have shown leadership in efforts to eliminate inequities in medical education and health care. Each of five recipients receives $5,000.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2026-04-30"),
    url: "https://www.aamc.org/services/student-programs/nickens-scholarships",
    scholarshipType: "merit",
    renewable: false,
    educationLevels: ["professional"],
    fieldsOfStudy: ["medicine"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["medicine", "health-equity", "leadership", "diversity", "AAMC"],
    sourceId: "aamc-nickens",
    sourceUrl: "https://www.aamc.org",
  },
  {
    title: "Paul & Daisy Soros Fellowships for New Americans",
    provider: "Paul & Daisy Soros Foundation",
    description:
      "Paul & Daisy Soros Fellowships for New Americans supports the graduate education of immigrants and children of immigrants to the U.S. who are contributing to American society. Up to $90,000 total ($25,000 stipend + 50% tuition) is awarded.",
    amount: "Up to $90,000 total",
    amountMin: 50000,
    amountMax: 90000,
    deadline: new Date("2025-11-01"),
    url: "https://www.pdsoros.org",
    scholarshipType: "merit",
    renewable: true,
    minGPA: 3.5,
    educationLevels: ["graduate"],
    citizenshipRequired: "US Citizen, Permanent Resident, or DACA recipient",
    essayRequired: true,
    essayWordLimit: 1000,
    submissionMethod: "portal",
    tags: ["immigrant", "new-american", "graduate", "prestigious", "diversity"],
    sourceId: "paul-daisy-soros",
    sourceUrl: "https://www.pdsoros.org",
  },
  {
    title: "National Merit Scholarship",
    provider: "National Merit Scholarship Corporation",
    description:
      "The National Merit Scholarship Program is an academic competition for college scholarships open to PSAT/NMSQT-qualifying students. Approximately 7,500 National Merit Scholarships worth about $2,500 each are offered annually.",
    amount: "$2,500",
    amountMin: 2500,
    amountMax: 2500,
    deadline: new Date("2025-10-15"),
    url: "https://www.nationalmerit.org",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.5,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: false,
    submissionMethod: "portal",
    tags: ["PSAT", "academic-excellence", "high-school-senior", "competitive"],
    sourceId: "national-merit",
    sourceUrl: "https://www.nationalmerit.org",
  },

  // ── Community / Service Scholarships ────────────────────────────────────────
  {
    title: "AmeriCorps Education Award",
    provider: "AmeriCorps (Corporation for National and Community Service)",
    description:
      "AmeriCorps members who complete their service term earn a Segal AmeriCorps Education Award of $7,395 (2024 rate). The award can be used to pay education costs at eligible institutions or repay qualified student loans.",
    amount: "$7,395",
    amountMin: 7395,
    amountMax: 7395,
    deadline: new Date("2026-12-31"),
    url: "https://americorps.gov/members-volunteers/segal-americorps-education-award",
    scholarshipType: "service-award",
    renewable: false,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: false,
    submissionMethod: "portal",
    tags: ["service", "community", "AmeriCorps", "education-award"],
    sourceId: "americorps-education",
    sourceUrl: "https://americorps.gov",
  },
  {
    title: "Bonner Scholars Program",
    provider: "Bonner Foundation",
    description:
      "The Bonner Scholars Program provides financial assistance and community engagement opportunities to students at partner institutions who demonstrate financial need and commitment to community service. Students receive up to $10,000 annually.",
    amount: "Up to $10,000/year",
    amountMin: 5000,
    amountMax: 10000,
    deadline: new Date("2026-02-28"),
    url: "https://bonner.org/bonner-scholars",
    scholarshipType: "service",
    renewable: true,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["community-service", "need-based", "renewable", "leadership"],
    sourceId: "bonner-scholars",
    sourceUrl: "https://bonner.org",
  },
  {
    title: "Davis-UWC Scholarship",
    provider: "Davis UWC Scholars Program",
    description:
      "The Davis UWC Scholars Program awards up to $40,000 in scholarships for two years of study at a United World College. Scholars are selected on the basis of exceptional academic achievement and potential for leadership and international service.",
    amount: "Up to $40,000",
    amountMin: 20000,
    amountMax: 40000,
    deadline: new Date("2026-01-15"),
    url: "https://www.davisfoundation.org/programs/davis-uwc-scholars-program",
    scholarshipType: "merit",
    renewable: true,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["international", "leadership", "service", "prestigious", "UWC"],
    sourceId: "davis-uwc",
    sourceUrl: "https://www.davisfoundation.org",
  },
  {
    title: "Jefferson Scholarship",
    provider: "University of Virginia",
    description:
      "The Jefferson Scholarship at the University of Virginia is an exclusive, full-expense scholarship for students of high academic achievement, strong leadership potential, and magnetic character. The four-year award covers tuition, room, board, and fees.",
    amount: "Up to $70,000 total",
    amountMin: 60000,
    amountMax: 70000,
    deadline: new Date("2025-11-15"),
    url: "https://jeffersonscholars.org",
    scholarshipType: "merit",
    renewable: true,
    minGPA: 3.8,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["UVA", "full-ride", "prestigious", "leadership", "character"],
    sourceId: "jefferson-scholarship",
    sourceUrl: "https://jeffersonscholars.org",
  },
  {
    title: "Morehead-Cain Scholarship",
    provider: "Morehead-Cain Foundation / UNC Chapel Hill",
    description:
      "The Morehead-Cain Scholarship is the nation's first merit scholarship program, awarded to exceptional students at the University of North Carolina at Chapel Hill. The four-year award covers tuition, room, board, books, and funded summer programs.",
    amount: "Up to $70,000 total",
    amountMin: 60000,
    amountMax: 70000,
    deadline: new Date("2025-11-15"),
    url: "https://www.moreheadcain.org",
    scholarshipType: "merit",
    renewable: true,
    minGPA: 3.7,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["UNC", "full-ride", "prestigious", "leadership", "summer-experiences"],
    sourceId: "morehead-cain",
    sourceUrl: "https://www.moreheadcain.org",
  },
  {
    title: "Stamps Scholarship",
    provider: "Stamps Family Charitable Foundation",
    description:
      "Stamps Scholarships are awarded at select partner universities to students of exceptional academic performance and personal character. Awards cover tuition, fees, room, board, and include an enrichment fund for study abroad, research, or internships.",
    amount: "Up to $60,000+",
    amountMin: 40000,
    amountMax: 60000,
    deadline: new Date("2025-12-01"),
    url: "https://stampsfoundation.org",
    scholarshipType: "merit",
    renewable: true,
    minGPA: 3.7,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["full-ride", "prestigious", "enrichment", "leadership", "multi-university"],
    sourceId: "stamps-scholarship",
    sourceUrl: "https://stampsfoundation.org",
  },
  {
    title: "Posse Scholarship",
    provider: "Posse Foundation",
    description:
      "The Posse Foundation recruits students with extraordinary leadership potential and sends them in cohorts to top colleges and universities. The full-tuition scholarship is awarded to students nominated by their high school and is worth up to $60,000.",
    amount: "Up to $60,000 (full tuition)",
    amountMin: 40000,
    amountMax: 60000,
    deadline: new Date("2025-10-31"),
    url: "https://www.possefoundation.org",
    scholarshipType: "merit-need",
    renewable: true,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["leadership", "diversity", "cohort", "prestigious", "full-tuition"],
    sourceId: "posse",
    sourceUrl: "https://www.possefoundation.org",
  },
  {
    title: "Gates Scholarship (QuestBridge College Match)",
    provider: "QuestBridge",
    description:
      "QuestBridge College Match connects the nation's most exceptional low-income students with admission and full four-year scholarships to top-ranked partner colleges. The scholarship covers tuition, room and board, travel, and personal expenses.",
    amount: "Full ride (avg. $40,000/year)",
    amountMin: 30000,
    amountMax: 40000,
    deadline: new Date("2025-09-26"),
    url: "https://www.questbridge.org",
    scholarshipType: "need-based",
    renewable: true,
    minGPA: 3.5,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["low-income", "full-ride", "college-match", "prestigious"],
    sourceId: "questbridge-college-match",
    sourceUrl: "https://www.questbridge.org",
  },
  {
    title: "Heisman High School Scholarship",
    provider: "Heisman Trophy Trust",
    description:
      "The Heisman High School Scholarship recognizes student-athletes who excel in academics, athletics, and community service. Awards range from $1,000 to $10,000 for students who demonstrate the character exemplified by the Heisman Trophy.",
    amount: "$1,000–$10,000",
    amountMin: 1000,
    amountMax: 10000,
    deadline: new Date("2026-03-15"),
    url: "https://www.heisman.com/community/scholarship/",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen",
    essayRequired: true,
    essayWordLimit: 500,
    submissionMethod: "portal",
    tags: ["student-athlete", "sports", "leadership", "community-service", "academic"],
    sourceId: "heisman-high-school",
    sourceUrl: "https://www.heisman.com",
  },
  {
    title: "Rotary Foundation Ambassadorial Scholarship",
    provider: "Rotary International",
    description:
      "Rotary Foundation Scholarships fund one to two academic years of study abroad and promote international goodwill through educational and cultural exchange. Scholars serve as ambassadors of goodwill in the host country.",
    amount: "$12,000–$26,000",
    amountMin: 12000,
    amountMax: 26000,
    deadline: new Date("2026-05-01"),
    url: "https://www.rotary.org/en/our-programs/scholarships",
    scholarshipType: "fellowship",
    renewable: false,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "Any nationality",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["international", "cultural-exchange", "goodwill", "study-abroad"],
    sourceId: "rotary-ambassadorial",
    sourceUrl: "https://www.rotary.org",
  },
  {
    title: "Newman Civic Fellowship",
    provider: "Campus Compact",
    description:
      "The Newman Civic Fellowship recognizes inspiring college students who have demonstrated meaningful impact as leaders of change. Fellows receive a $1,500 stipend and gain access to exclusive professional development and networking opportunities.",
    amount: "$1,500",
    amountMin: 1500,
    amountMax: 1500,
    deadline: new Date("2026-02-28"),
    url: "https://compact.org/initiatives/newman-civic-fellowship",
    scholarshipType: "fellowship",
    renewable: false,
    educationLevels: ["undergraduate"],
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["civic-engagement", "leadership", "community-change", "campus-compact"],
    sourceId: "newman-civic",
    sourceUrl: "https://compact.org",
  },
  {
    title: "Prudential Spirit of Community Award",
    provider: "Prudential Financial",
    description:
      "The Prudential Spirit of Community Awards honors middle and high school students for outstanding community service. State honorees receive $1,000 and national honorees receive an additional $5,000 and a gold medallion.",
    amount: "$1,000–$5,000",
    amountMin: 1000,
    amountMax: 5000,
    deadline: new Date("2025-11-05"),
    url: "https://spirit.prudential.com",
    scholarshipType: "merit",
    renewable: false,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 700,
    submissionMethod: "portal",
    tags: ["community-service", "high-school", "youth", "Prudential"],
    sourceId: "prudential-spirit",
    sourceUrl: "https://spirit.prudential.com",
  },
  {
    title: "Comcast Leaders and Achievers Scholarship",
    provider: "Comcast NBCUniversal Foundation",
    description:
      "The Comcast Leaders and Achievers Scholarship Program recognizes outstanding high school seniors who demonstrate leadership, community service, and strong academic performance. Recipients receive $1,000 one-time scholarships.",
    amount: "$1,000",
    amountMin: 1000,
    amountMax: 1000,
    deadline: new Date("2026-01-21"),
    url: "https://corporate.comcast.com/our-company/foundation/comcast-leaders-achievers-scholarship",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["leadership", "community-service", "high-school-senior", "Comcast"],
    sourceId: "comcast-leaders",
    sourceUrl: "https://corporate.comcast.com",
  },
  {
    title: "American Indian College Fund Scholarship",
    provider: "American Indian College Fund",
    description:
      "The American Indian College Fund provides scholarships to Native American and Alaska Native students attending Tribal Colleges and Universities and mainstream institutions. Awards range from $1,000 to $20,000 and support full-time and part-time students.",
    amount: "$1,000–$20,000",
    amountMin: 1000,
    amountMax: 20000,
    deadline: new Date("2026-05-31"),
    url: "https://collegefund.org/students/scholarships/",
    scholarshipType: "merit-need",
    renewable: true,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["Native-American", "Alaska-Native", "tribal-college", "minority", "indigenous"],
    sourceId: "aicf",
    sourceUrl: "https://collegefund.org",
  },
  {
    title: "Jackie Robinson Foundation Scholarship",
    provider: "Jackie Robinson Foundation",
    description:
      "The Jackie Robinson Foundation Scholarship provides scholarships and comprehensive support services to minority students who demonstrate high academic achievement, leadership skills, and financial need. Recipients receive up to $30,000 over four years.",
    amount: "Up to $30,000 total ($7,500/year)",
    amountMin: 7500,
    amountMax: 30000,
    deadline: new Date("2026-02-01"),
    url: "https://jackierobinson.org/apply/",
    scholarshipType: "merit-need",
    renewable: true,
    minGPA: 3.0,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen",
    essayRequired: true,
    essayWordLimit: 750,
    submissionMethod: "portal",
    tags: ["minority", "African-American", "leadership", "need-based", "renewable"],
    sourceId: "jackie-robinson",
    sourceUrl: "https://jackierobinson.org",
  },
  {
    title: "NAACP Agnes Jones Jackson Scholarship",
    provider: "NAACP",
    description:
      "The NAACP Agnes Jones Jackson Scholarship awards $1,500 to $2,500 annually to full-time students who are NAACP members in good standing. Both undergraduate and graduate students are eligible with demonstrated financial need and academic merit.",
    amount: "$1,500–$2,500",
    amountMin: 1500,
    amountMax: 2500,
    deadline: new Date("2026-03-07"),
    url: "https://naacp.org/find-resources/scholarships-awards-internships/scholarships",
    scholarshipType: "merit-need",
    renewable: false,
    minGPA: 2.5,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["NAACP", "African-American", "civil-rights", "need-based", "membership"],
    sourceId: "naacp-agnes-jones",
    sourceUrl: "https://naacp.org",
  },
  {
    title: "Congressional Hispanic Caucus Institute Scholarship",
    provider: "Congressional Hispanic Caucus Institute",
    description:
      "CHCI awards scholarships to exceptional Hispanic Americans who are committed to public service. Scholarships of $1,000 to $5,000 are awarded to undergraduate and graduate students, with accompanying leadership development opportunities.",
    amount: "$1,000–$5,000",
    amountMin: 1000,
    amountMax: 5000,
    deadline: new Date("2026-04-15"),
    url: "https://chci.org/scholarships/",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 750,
    submissionMethod: "portal",
    tags: ["Hispanic", "Latino", "public-service", "leadership", "congressional"],
    sourceId: "chci-scholarship",
    sourceUrl: "https://chci.org",
  },
  {
    title: "Asian American Journalists Association Scholarship",
    provider: "Asian American Journalists Association",
    description:
      "AAJA awards scholarships to Asian American and Pacific Islander students pursuing journalism or mass communications careers. Awards of $2,000 to $5,000 support students who demonstrate journalistic promise and a commitment to diversity in media.",
    amount: "$2,000–$5,000",
    amountMin: 2000,
    amountMax: 5000,
    deadline: new Date("2026-04-30"),
    url: "https://www.aaja.org/programs-and-initiatives/scholarships-and-internships/",
    scholarshipType: "merit",
    renewable: false,
    educationLevels: ["undergraduate", "graduate"],
    fieldsOfStudy: ["journalism", "communications", "media", "broadcasting"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["Asian-American", "journalism", "media", "diversity", "AAPI"],
    sourceId: "aaja-scholarship",
    sourceUrl: "https://www.aaja.org",
  },
  {
    title: "Foundation for Global Scholars Award",
    provider: "Foundation for Global Scholars",
    description:
      "The Foundation for Global Scholars awards merit-based scholarships to international students studying in the United States. Awards of $1,000 to $5,000 recognize academic excellence and contributions to cross-cultural understanding.",
    amount: "$1,000–$5,000",
    amountMin: 1000,
    amountMax: 5000,
    deadline: new Date("2026-03-15"),
    url: "https://foundationforglobalscholars.org",
    scholarshipType: "merit",
    renewable: false,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "Any nationality",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["international", "cross-cultural", "merit", "global"],
    sourceId: "foundation-global-scholars",
    sourceUrl: "https://foundationforglobalscholars.org",
  },
  {
    title: "Thurgood Marshall College Fund Scholarship",
    provider: "Thurgood Marshall College Fund",
    description:
      "TMCF provides scholarships and career development to students attending its 47 publicly supported Historically Black Colleges and Universities. Awards of $2,000 to $13,400 are available for full-time students demonstrating academic excellence and financial need.",
    amount: "$2,000–$13,400",
    amountMin: 2000,
    amountMax: 13400,
    deadline: new Date("2026-06-15"),
    url: "https://tmcf.org/scholarships-internships/scholarships/",
    scholarshipType: "merit-need",
    renewable: true,
    minGPA: 3.0,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["HBCU", "African-American", "need-based", "renewable", "Thurgood-Marshall"],
    sourceId: "tmcf",
    sourceUrl: "https://tmcf.org",
  },
  {
    title: "P.E.O. Program for Continuing Education",
    provider: "P.E.O. Sisterhood",
    description:
      "P.E.O. provides need-based grants to women re-entering the educational system after an interruption in their academic careers. Grants of up to $3,000 assist women in completing their educational goals at accredited institutions.",
    amount: "Up to $3,000",
    amountMin: 1000,
    amountMax: 3000,
    deadline: new Date("2026-02-15"),
    url: "https://www.peointernational.org/peo-projects/continuing-education/",
    scholarshipType: "need-based",
    renewable: false,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    submissionMethod: "portal",
    tags: ["women", "returning-student", "need-based", "re-entry", "PEO"],
    sourceId: "peo-continuing-ed",
    sourceUrl: "https://www.peointernational.org",
  },
  {
    title: "AFSA High School Essay Contest Scholarship",
    provider: "American Foreign Service Association",
    description:
      "AFSA's High School Essay Contest awards scholarships to students in grades 9–12 for essays on topics related to international relations and U.S. foreign policy. First prize is $2,500, with additional awards for second and third place.",
    amount: "$1,000–$2,500",
    amountMin: 1000,
    amountMax: 2500,
    deadline: new Date("2026-04-30"),
    url: "https://afsa.org/essay-contest",
    scholarshipType: "merit",
    renewable: false,
    educationLevels: ["undergraduate"],
    fieldsOfStudy: ["international relations", "foreign policy", "political science"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 1500,
    submissionMethod: "portal",
    tags: ["essay", "international-relations", "foreign-policy", "high-school", "writing"],
    sourceId: "afsa-essay-contest",
    sourceUrl: "https://afsa.org",
  },
];
