import type { ScholarshipSource, ScrapedScholarship, ScholarshipFilters } from "./types";

export class EssayContestsSource implements ScholarshipSource {
  id = "essay-contests";
  name = "Essay Contests & Writing Scholarships";
  type = "foundation" as const;

  isEnabled(): boolean {
    return true;
  }

  async scrape(_filters?: ScholarshipFilters): Promise<ScrapedScholarship[]> {
    return ESSAY_CONTEST_SCHOLARSHIPS;
  }
}

const ESSAY_CONTEST_SCHOLARSHIPS: ScrapedScholarship[] = [
  {
    title: "Ayn Rand Institute Atlas Shrugged Essay Contest",
    provider: "Ayn Rand Institute",
    description:
      "The Ayn Rand Institute's Atlas Shrugged Essay Contest invites college students and high school seniors to write an essay about Ayn Rand's novel Atlas Shrugged. Top prizes are $10,000 for first place, with numerous other prizes ranging from $50 to $2,000. The contest encourages students to engage with ideas of individualism, reason, and capitalism.",
    amount: "Up to $10,000",
    amountMin: 50,
    amountMax: 10000,
    deadline: new Date("2027-10-18"),
    url: "https://www.aynrand.org/contests/atlas-shrugged",
    scholarshipType: "contest",
    renewable: false,
    educationLevels: ["undergraduate"],
    essayRequired: true,
    essayPrompt: "Write an analytical essay on a provided theme from Ayn Rand's Atlas Shrugged, exploring the novel's ideas about individual achievement, the role of the mind in human existence, and the morality of capitalism.",
    essayWordLimit: 1600,
    submissionMethod: "portal",
    portalUrl: "https://www.aynrand.org/contests/atlas-shrugged",
    tags: ["essay-contest", "Ayn-Rand", "philosophy", "literature", "individualism", "college"],
    sourceId: "ayn-rand-atlas-shrugged",
    sourceUrl: "https://www.aynrand.org/contests/atlas-shrugged",
  },
  {
    title: "Ayn Rand Institute Anthem Essay Contest",
    provider: "Ayn Rand Institute",
    description:
      "The Ayn Rand Institute's Anthem Essay Contest is open to 8th–12th grade students and awards up to $2,000 for essays about Ayn Rand's novella Anthem. The contest explores themes of individualism, collectivism, freedom, and identity, and is one of the most popular high school essay competitions in the country.",
    amount: "Up to $2,000",
    amountMin: 50,
    amountMax: 2000,
    deadline: new Date("2027-04-25"),
    url: "https://www.aynrand.org/contests/anthem",
    scholarshipType: "contest",
    renewable: false,
    educationLevels: ["undergraduate"],
    essayRequired: true,
    essayPrompt: "Write an analytical essay on a provided theme from Ayn Rand's Anthem, examining the novella's exploration of individualism versus collectivism, freedom of the mind, and the meaning of identity.",
    essayWordLimit: 1000,
    submissionMethod: "portal",
    portalUrl: "https://www.aynrand.org/contests/anthem",
    tags: ["essay-contest", "Ayn-Rand", "philosophy", "literature", "high-school", "individualism"],
    sourceId: "ayn-rand-anthem",
    sourceUrl: "https://www.aynrand.org/contests/anthem",
  },
  {
    title: "JFK Profile in Courage Essay Contest",
    provider: "John F. Kennedy Presidential Library and Museum",
    description:
      "The JFK Profile in Courage Essay Contest is open to students in grades 9–12 and awards a $10,000 prize to the winner. Students write about a U.S. elected official at any level of government who demonstrated political courage by taking a stand that was difficult or unpopular. The contest honors President Kennedy's Pulitzer Prize-winning book Profiles in Courage.",
    amount: "$10,000",
    amountMin: 100,
    amountMax: 10000,
    deadline: new Date("2027-01-10"),
    url: "https://www.jfklibrary.org/learn/education/profile-in-courage-essay-contest",
    scholarshipType: "contest",
    renewable: false,
    educationLevels: ["undergraduate"],
    essayRequired: true,
    essayPrompt: "Write a 700–1,000 word essay describing an act of political courage by a U.S. elected official — at the federal, state, or local level — who risked their career or reputation by taking a principled stand, and explain the significance of that act of courage.",
    essayWordLimit: 1000,
    submissionMethod: "portal",
    portalUrl: "https://www.jfklibrary.org/learn/education/profile-in-courage-essay-contest",
    tags: ["essay-contest", "JFK", "political-courage", "civics", "government", "high-school", "history"],
    sourceId: "jfk-profile-in-courage",
    sourceUrl: "https://www.jfklibrary.org/learn/education/profile-in-courage-essay-contest",
  },
  {
    title: "DAR Good Citizens Scholarship",
    provider: "National Society Daughters of the American Revolution (DAR)",
    description:
      "The DAR Good Citizens Scholarship awards $2,500 to graduating high school seniors who demonstrate qualities of good citizenship including dependability, service, leadership, and patriotism. Applicants submit a 1,000-word essay on a patriotic theme as well as transcripts and teacher recommendations.",
    amount: "$2,500",
    amountMin: 2500,
    amountMax: 2500,
    deadline: new Date("2027-01-31"),
    url: "https://www.dar.org/national-society/scholarships/dar-good-citizen",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 0,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen",
    essayRequired: true,
    essayPrompt: "Write a 1,000-word essay demonstrating your understanding of good citizenship and patriotism, exploring your commitment to serving your community and upholding American democratic values.",
    essayWordLimit: 1000,
    submissionMethod: "portal",
    portalUrl: "https://www.dar.org/national-society/scholarships/dar-good-citizen",
    tags: ["essay-contest", "DAR", "citizenship", "patriotism", "service", "leadership", "high-school"],
    sourceId: "dar-good-citizens",
    sourceUrl: "https://www.dar.org/national-society/scholarships/dar-good-citizen",
  },
  {
    title: "VFW Voice of Democracy Scholarship",
    provider: "Veterans of Foreign Wars (VFW)",
    description:
      "The VFW Voice of Democracy audio-essay competition awards up to $30,000 in scholarships to high school students who write and record a three-to-five minute audio essay on a patriotic theme. The national first-place winner receives $30,000 and a trip to Washington D.C. Over $2 million in scholarship assistance is awarded nationwide each year.",
    amount: "Up to $30,000",
    amountMin: 1000,
    amountMax: 30000,
    deadline: new Date("2027-10-31"),
    url: "https://www.vfw.org/community/youth-and-education/voice-of-democracy",
    scholarshipType: "contest",
    renewable: false,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayPrompt: "Record a 3–5 minute audio essay on the current patriotic theme (announced annually by VFW), expressing your views on American values, democracy, freedom, or civic responsibility.",
    essayWordLimit: 600,
    submissionMethod: "email",
    tags: ["essay-contest", "VFW", "patriotism", "veterans", "audio-essay", "democracy", "high-school"],
    sourceId: "vfw-voice-of-democracy",
    sourceUrl: "https://www.vfw.org/community/youth-and-education/voice-of-democracy",
  },
  {
    title: "Optimist International Essay Contest",
    provider: "Optimist International",
    description:
      "The Optimist International Essay Contest awards up to $2,500 to students under age 18 who write a compelling essay on a provided theme related to optimism. Club-level winners advance to district competitions, with the possibility of earning a $2,500 scholarship. The contest promotes optimistic thinking and positive communication among young people.",
    amount: "Up to $2,500",
    amountMin: 500,
    amountMax: 2500,
    deadline: new Date("2027-03-01"),
    url: "https://www.optimist.org/member/scholarships3.cfm",
    scholarshipType: "contest",
    renewable: false,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen, Canadian, or Caribbean",
    essayRequired: true,
    essayPrompt: "Write an essay on the current annual theme (announced by Optimist International), exploring how optimism can make a difference in your life, your community, and the world.",
    essayWordLimit: 800,
    submissionMethod: "email",
    tags: ["essay-contest", "Optimist-International", "optimism", "youth", "positive-thinking", "community"],
    sourceId: "optimist-essay-contest",
    sourceUrl: "https://www.optimist.org/member/scholarships3.cfm",
  },
  {
    title: "NFIB Young Entrepreneur Award",
    provider: "NFIB Legal Center / Young Entrepreneur Foundation",
    description:
      "The NFIB Young Entrepreneur Award provides $12,000 scholarships to students who demonstrate entrepreneurial spirit and have started or plan to start a business. Applicants submit an essay about their business idea or enterprise, explaining how they plan to grow it and create value in their community.",
    amount: "$12,000",
    amountMin: 1000,
    amountMax: 12000,
    deadline: new Date("2027-04-30"),
    url: "https://www.nfibyoungentrepreneur.com/",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 2.5,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayPrompt: "Describe your business idea or existing business venture. Explain what problem it solves, what makes it unique, how you plan to grow it, and how entrepreneurship and free enterprise principles will guide your approach.",
    essayWordLimit: 1000,
    submissionMethod: "portal",
    portalUrl: "https://www.nfibyoungentrepreneur.com/",
    tags: ["essay-contest", "NFIB", "entrepreneurship", "business", "free-enterprise", "youth", "innovation"],
    sourceId: "nfib-young-entrepreneur",
    sourceUrl: "https://www.nfibyoungentrepreneur.com/",
  },
  {
    title: "Scholastic Art & Writing Awards",
    provider: "Alliance for Young Artists & Writers",
    description:
      "The Scholastic Art & Writing Awards are the nation's longest-running and most prestigious recognition program for creative students. Awards up to $10,000 in gold portfolios recognize outstanding work in 29 categories including creative writing, poetry, journalism, and short story. Over 330,000 students enter each year.",
    amount: "Up to $10,000",
    amountMin: 100,
    amountMax: 10000,
    deadline: new Date("2026-12-01"),
    url: "https://www.artandwriting.org/",
    scholarshipType: "contest",
    renewable: false,
    educationLevels: ["undergraduate"],
    essayRequired: true,
    essayPrompt: "Submit an original piece of creative writing — which may include personal essay/memoir, poetry, short story, humor, science fiction & fantasy, journalism, novel writing, or another approved category — that demonstrates your distinct creative voice and craft.",
    essayWordLimit: 3000,
    submissionMethod: "portal",
    portalUrl: "https://www.artandwriting.org/",
    tags: ["essay-contest", "Scholastic", "creative-writing", "art", "poetry", "short-story", "high-school", "literature"],
    sourceId: "scholastic-art-writing",
    sourceUrl: "https://www.artandwriting.org/",
  },
  {
    title: "Signet Classics Student Scholarship Essay Contest",
    provider: "New American Library / Penguin Group",
    description:
      "The Signet Classics Student Scholarship Essay Contest awards $1,000 to high school juniors and seniors who write the best analytical essay about a selected classic work of literature from the Signet Classics catalog. The competition encourages close reading and analytical thinking about enduring works of literature.",
    amount: "$1,000",
    amountMin: 1000,
    amountMax: 1000,
    deadline: new Date("2027-04-15"),
    url: "https://www.penguin.com/signet-classics-scholarship/",
    scholarshipType: "contest",
    renewable: false,
    educationLevels: ["undergraduate"],
    essayRequired: true,
    essayPrompt: "Write a concise analytical essay (no longer than 5 pages) on the selected Signet Classic title for that year (announced annually), analyzing the work's themes, characters, literary style, or enduring significance.",
    essayWordLimit: 1500,
    submissionMethod: "email",
    tags: ["essay-contest", "Signet-Classics", "literature", "analytical-writing", "classic-literature", "high-school"],
    sourceId: "signet-classics-essay",
    sourceUrl: "https://www.penguin.com/signet-classics-scholarship/",
  },
  {
    title: "Laws of Life Essay Contest",
    provider: "John Templeton Foundation",
    description:
      "The Laws of Life Essay Contest awards $5,000 to students who write about the principles they live by — their personal laws of life. Students from middle school through college compete by writing an essay that explores the values, lessons, and guiding principles they have discovered, often through personal experience. The contest fosters character development and ethical reflection.",
    amount: "Up to $5,000",
    amountMin: 100,
    amountMax: 5000,
    deadline: new Date("2027-05-31"),
    url: "https://www.lawsoflife.org/",
    scholarshipType: "contest",
    renewable: false,
    educationLevels: ["undergraduate"],
    essayRequired: true,
    essayPrompt: "Write a personal essay describing the principles, values, and guiding beliefs that serve as your own 'laws of life' — the core truths you have discovered through experience that shape how you live, make decisions, and treat others.",
    essayWordLimit: 1500,
    submissionMethod: "portal",
    portalUrl: "https://www.lawsoflife.org/essay-contest/",
    tags: ["essay-contest", "John-Templeton", "character", "ethics", "personal-values", "life-lessons", "youth"],
    sourceId: "laws-of-life-essay",
    sourceUrl: "https://www.lawsoflife.org/",
  },
];
