import type { ScholarshipSource, ScrapedScholarship, ScholarshipFilters } from "./types";

export class MinorityScholarshipsSource implements ScholarshipSource {
  id = "minority";
  name = "Minority & Underrepresented Scholarships";
  type = "foundation" as const;

  isEnabled(): boolean {
    return true;
  }

  async scrape(_filters?: ScholarshipFilters): Promise<ScrapedScholarship[]> {
    return MINORITY_SCHOLARSHIPS;
  }
}

const MINORITY_SCHOLARSHIPS: ScrapedScholarship[] = [
  {
    title: "UNCF General Scholarship",
    provider: "United Negro College Fund (UNCF)",
    description:
      "The United Negro College Fund administers hundreds of scholarships totaling over $100 million annually to African American students. The UNCF General Scholarship provides up to $25,000 to Black undergraduate students attending accredited four-year colleges and universities with demonstrated financial need.",
    amount: "Up to $25,000",
    amountMin: 2500,
    amountMax: 25000,
    deadline: new Date("2027-03-01"),
    url: "https://scholarships.uncf.org/",
    scholarshipType: "need-based",
    renewable: false,
    minGPA: 2.5,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 1000,
    submissionMethod: "portal",
    portalUrl: "https://scholarships.uncf.org/",
    tags: ["minority", "African-American", "Black", "UNCF", "HBCU", "need-based", "underrepresented"],
    sourceId: "uncf-general",
    sourceUrl: "https://scholarships.uncf.org/",
  },
  {
    title: "Thurgood Marshall College Fund Scholarship",
    provider: "Thurgood Marshall College Fund",
    description:
      "The Thurgood Marshall College Fund awards $10,000 scholarships to academically talented, community-minded students attending Historically Black Colleges and Universities (HBCUs) and predominantly Black institutions. The fund honors Supreme Court Justice Thurgood Marshall's legacy of civil rights and academic excellence.",
    amount: "$10,000",
    amountMin: 10000,
    amountMax: 10000,
    deadline: new Date("2027-05-01"),
    url: "https://www.tmcf.org/students-alumni/scholarships/",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 800,
    submissionMethod: "portal",
    portalUrl: "https://www.tmcf.org/students-alumni/scholarships/",
    tags: ["minority", "African-American", "Black", "HBCU", "Thurgood-Marshall", "civil-rights", "underrepresented"],
    sourceId: "thurgood-marshall-fund",
    sourceUrl: "https://www.tmcf.org/students-alumni/scholarships/",
  },
  {
    title: "Jackie Robinson Scholarship",
    provider: "Jackie Robinson Foundation",
    description:
      "The Jackie Robinson Foundation awards four-year scholarships of up to $30,000 ($7,500/year) to minority students demonstrating extraordinary leadership potential, academic excellence, and commitment to community service. Recipients join an elite community of scholars and gain access to mentoring, internship opportunities, and a lifelong network.",
    amount: "Up to $30,000 (over 4 years)",
    amountMin: 7500,
    amountMax: 30000,
    deadline: new Date("2027-02-01"),
    url: "https://www.jackierobinson.org/apply/",
    scholarshipType: "merit-need",
    renewable: true,
    minGPA: 3.0,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 1000,
    submissionMethod: "portal",
    portalUrl: "https://www.jackierobinson.org/apply/",
    tags: ["minority", "African-American", "leadership", "Jackie-Robinson", "community-service", "renewable", "underrepresented"],
    sourceId: "jackie-robinson",
    sourceUrl: "https://www.jackierobinson.org/apply/",
  },
  {
    title: "Hispanic Scholarship Fund (HSF) Scholarship",
    provider: "Hispanic Scholarship Fund",
    description:
      "The Hispanic Scholarship Fund awards $5,000 scholarships to Hispanic college students who demonstrate academic achievement and a commitment to giving back to their communities. As the nation's largest nonprofit organization supporting Hispanic higher education, HSF has awarded over $600 million to more than 700,000 scholars since 1975.",
    amount: "$5,000",
    amountMin: 500,
    amountMax: 5000,
    deadline: new Date("2027-02-15"),
    url: "https://www.hsf.net/scholarship",
    scholarshipType: "merit-need",
    renewable: true,
    minGPA: 3.0,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 800,
    submissionMethod: "portal",
    portalUrl: "https://www.hsf.net/scholarship",
    tags: ["minority", "Hispanic", "Latino", "HSF", "community-service", "need-based", "underrepresented", "renewable"],
    sourceId: "hispanic-scholarship-fund",
    sourceUrl: "https://www.hsf.net/scholarship",
  },
  {
    title: "LULAC National Scholarship Fund",
    provider: "League of United Latin American Citizens (LULAC)",
    description:
      "LULAC's National Scholarship Fund provides over $1 million annually in scholarships ranging from $250 to $2,000 to Hispanic students enrolled at accredited colleges and universities. The fund is administered by local LULAC councils and awards are based on academic achievement, financial need, and leadership in the community.",
    amount: "$250–$2,000",
    amountMin: 250,
    amountMax: 2000,
    deadline: new Date("2027-03-31"),
    url: "https://lnesc.org/scholarships/",
    scholarshipType: "merit-need",
    renewable: false,
    minGPA: 2.5,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 500,
    submissionMethod: "portal",
    portalUrl: "https://lnesc.org/scholarships/",
    tags: ["minority", "Hispanic", "Latino", "LULAC", "community", "need-based", "underrepresented"],
    sourceId: "lulac-national",
    sourceUrl: "https://lnesc.org/scholarships/",
  },
  {
    title: "Chicano/Latino Foundation Scholarship",
    provider: "Chicano/Latino Foundation",
    description:
      "The Chicano/Latino Foundation awards $5,000 scholarships to Chicano and Latino students in California who demonstrate academic excellence and a commitment to community service. The foundation prioritizes applicants who plan to work in fields that will benefit underserved Latino communities.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2027-03-15"),
    url: "https://www.chicanolatino.org/scholarship/",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 2.5,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    stateRestriction: "CA",
    essayRequired: true,
    essayWordLimit: 600,
    submissionMethod: "portal",
    portalUrl: "https://www.chicanolatino.org/scholarship/",
    tags: ["minority", "Chicano", "Latino", "Hispanic", "California", "community-service", "underrepresented"],
    sourceId: "chicano-latino-foundation",
    sourceUrl: "https://www.chicanolatino.org/scholarship/",
  },
  {
    title: "APIA Scholars College Scholarship",
    provider: "Asian & Pacific Islander American Scholarship Fund (APIA Scholars)",
    description:
      "APIA Scholars awards up to $20,000 in multi-year scholarships to Asian and Pacific Islander American students demonstrating academic excellence, financial need, and involvement in their communities. As the largest nonprofit organization dedicated to API college students, APIA Scholars provides a network of over 19,000 alumni.",
    amount: "Up to $20,000",
    amountMin: 2500,
    amountMax: 20000,
    deadline: new Date("2027-01-15"),
    url: "https://apiascholars.org/scholarship/apia-scholarship/",
    scholarshipType: "merit-need",
    renewable: true,
    minGPA: 2.7,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 800,
    submissionMethod: "portal",
    portalUrl: "https://apiascholars.org/scholarship/apia-scholarship/",
    tags: ["minority", "Asian-American", "Pacific-Islander", "APIA", "need-based", "renewable", "underrepresented"],
    sourceId: "apia-scholars",
    sourceUrl: "https://apiascholars.org/scholarship/apia-scholarship/",
  },
  {
    title: "JACL National Scholarship Program",
    provider: "Japanese American Citizens League (JACL)",
    description:
      "The Japanese American Citizens League awards $5,000 scholarships to students of Japanese ancestry who demonstrate academic excellence and commitment to the JACL's values of upholding American democratic ideals. The program celebrates Japanese American heritage and promotes civic engagement.",
    amount: "$5,000",
    amountMin: 1000,
    amountMax: 5000,
    deadline: new Date("2027-04-01"),
    url: "https://jacl.org/education/scholarships/",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 2.7,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 500,
    submissionMethod: "portal",
    portalUrl: "https://jacl.org/education/scholarships/",
    tags: ["minority", "Japanese-American", "Asian-American", "JACL", "civic-engagement", "heritage", "underrepresented"],
    sourceId: "jacl-scholarship",
    sourceUrl: "https://jacl.org/education/scholarships/",
  },
  {
    title: "American Indian College Fund Full Circle Scholarship",
    provider: "American Indian College Fund",
    description:
      "The American Indian College Fund's Full Circle Scholarship Program awards up to $10,000 annually to American Indian and Alaska Native students enrolled at tribal colleges and universities or mainstream colleges. The fund supports Indigenous students through financial aid, mentoring, and cultural connections.",
    amount: "Up to $10,000",
    amountMin: 500,
    amountMax: 10000,
    deadline: new Date("2027-05-31"),
    url: "https://collegefund.org/students/scholarships/",
    scholarshipType: "merit-need",
    renewable: true,
    minGPA: 2.0,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    eligibilityText: "Must be an enrolled member of a federally recognized American Indian or Alaska Native tribe.",
    essayRequired: true,
    essayWordLimit: 500,
    submissionMethod: "portal",
    portalUrl: "https://collegefund.org/students/scholarships/",
    tags: ["minority", "Native-American", "Indigenous", "Alaska-Native", "tribal", "need-based", "underrepresented", "renewable"],
    sourceId: "american-indian-college-fund",
    sourceUrl: "https://collegefund.org/students/scholarships/",
  },
  {
    title: "Gates Millennium Scholars Program",
    provider: "Bill & Melinda Gates Foundation",
    description:
      "The Gates Millennium Scholars Program provides full-ride scholarships to outstanding minority students with significant financial need, enabling them to complete undergraduate and graduate education in any field of study. As one of the most prestigious awards, Gates Scholars receive a comprehensive support package including mentorship and leadership development.",
    amount: "Full Ride (varies by institution)",
    amountMin: 10000,
    amountMax: 100000,
    deadline: new Date("2027-01-13"),
    url: "https://www.gmsp.org/",
    scholarshipType: "need-based",
    renewable: true,
    minGPA: 3.3,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 1500,
    submissionMethod: "portal",
    portalUrl: "https://www.gmsp.org/",
    tags: ["minority", "Gates", "full-ride", "African-American", "Hispanic", "Native-American", "Asian-Pacific-Islander", "need-based", "renewable", "prestigious"],
    sourceId: "gates-millennium",
    sourceUrl: "https://www.gmsp.org/",
  },
  {
    title: "Point Foundation LGBTQ+ Scholarship",
    provider: "Point Foundation",
    description:
      "The Point Foundation awards multi-year scholarships of up to $10,000 annually to LGBTQ+ students who demonstrate leadership potential, community involvement, and academic excellence. Point Foundation is the nation's largest LGBTQ+ scholarship-granting organization and provides scholars with extensive mentoring and leadership development.",
    amount: "Up to $10,000/year",
    amountMin: 2000,
    amountMax: 10000,
    deadline: new Date("2027-02-01"),
    url: "https://pointfoundation.org/scholarships/",
    scholarshipType: "merit",
    renewable: true,
    minGPA: 3.0,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 1000,
    submissionMethod: "portal",
    portalUrl: "https://pointfoundation.org/scholarships/",
    tags: ["minority", "LGBTQ", "queer", "Point-Foundation", "leadership", "community", "underrepresented", "renewable"],
    sourceId: "point-foundation-lgbtq",
    sourceUrl: "https://pointfoundation.org/scholarships/",
  },
  {
    title: "Pride Foundation Scholarship",
    provider: "Pride Foundation",
    description:
      "Pride Foundation awards $12,000 scholarships to LGBTQ+ students and allies in the Pacific Northwest who demonstrate academic achievement, community involvement, and commitment to LGBTQ+ equality. The foundation serves students in Alaska, Idaho, Montana, Oregon, and Washington.",
    amount: "$12,000",
    amountMin: 1000,
    amountMax: 12000,
    deadline: new Date("2027-01-27"),
    url: "https://www.pridefoundation.org/programs/scholarships/",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 2.5,
    educationLevels: ["undergraduate", "graduate", "vocational", "trade-school"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 600,
    submissionMethod: "portal",
    portalUrl: "https://www.pridefoundation.org/programs/scholarships/",
    tags: ["minority", "LGBTQ", "queer", "Pride-Foundation", "Pacific-Northwest", "community", "underrepresented"],
    sourceId: "pride-foundation",
    sourceUrl: "https://www.pridefoundation.org/programs/scholarships/",
  },
  {
    title: "NAACP Scholarship Program",
    provider: "National Association for the Advancement of Colored People (NAACP)",
    description:
      "The NAACP offers multiple scholarship programs totaling $3,000 per award to African American students with outstanding academic achievement and demonstrated commitment to civil rights and community service. Recipients must be NAACP members or willing to join and participate in civil rights activities.",
    amount: "$3,000",
    amountMin: 1000,
    amountMax: 3000,
    deadline: new Date("2027-04-30"),
    url: "https://naacp.org/find-resources/scholarships-awards-internships",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 2.5,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 700,
    submissionMethod: "portal",
    portalUrl: "https://naacp.org/find-resources/scholarships-awards-internships",
    tags: ["minority", "African-American", "Black", "NAACP", "civil-rights", "community-service", "underrepresented"],
    sourceId: "naacp-scholarship",
    sourceUrl: "https://naacp.org/find-resources/scholarships-awards-internships",
  },
  {
    title: "CBC Spouses Education Scholarship",
    provider: "Congressional Black Caucus Foundation",
    description:
      "The CBC Spouses Education Scholarship awards $5,000 to African American students who live or attend school in a Congressional Black Caucus member's district. Recipients demonstrate exceptional academic achievement, community service, and leadership potential.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2027-04-07"),
    url: "https://www.cbcfinc.org/scholarships/",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 2.5,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 600,
    submissionMethod: "portal",
    portalUrl: "https://www.cbcfinc.org/scholarships/",
    tags: ["minority", "African-American", "Black", "CBC", "Congressional", "community-service", "leadership", "underrepresented"],
    sourceId: "cbc-spouses",
    sourceUrl: "https://www.cbcfinc.org/scholarships/",
  },
  {
    title: "Ron Brown Scholar Program",
    provider: "Ron Brown Scholar Fund",
    description:
      "The Ron Brown Scholar Program awards $40,000 four-year scholarships ($10,000/year) to academically talented African American high school students with demonstrated financial need and exceptional leadership and community service. Named for Secretary of Commerce Ron Brown, this competitive program develops the next generation of African American leaders.",
    amount: "$40,000 (over 4 years)",
    amountMin: 10000,
    amountMax: 40000,
    deadline: new Date("2027-01-09"),
    url: "https://www.ronbrown.org/",
    scholarshipType: "merit-need",
    renewable: true,
    minGPA: 0,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen",
    essayRequired: true,
    essayWordLimit: 1500,
    submissionMethod: "portal",
    portalUrl: "https://www.ronbrown.org/apply",
    tags: ["minority", "African-American", "Black", "Ron-Brown", "leadership", "need-based", "renewable", "prestigious", "underrepresented"],
    sourceId: "ron-brown-scholar",
    sourceUrl: "https://www.ronbrown.org/",
  },
];
