import type { ScholarshipSource, ScrapedScholarship, ScholarshipFilters } from "./types";

export class NicheScholarshipsSource implements ScholarshipSource {
  id = "niche";
  name = "Niche & Specialty Scholarships";
  type = "foundation" as const;

  isEnabled(): boolean {
    return true;
  }

  async scrape(_filters?: ScholarshipFilters): Promise<ScrapedScholarship[]> {
    return NICHE_SCHOLARSHIPS;
  }
}

const NICHE_SCHOLARSHIPS: ScrapedScholarship[] = [
  // --- Religious (5) ---
  {
    title: "Knights of Columbus Scholarship",
    provider: "Knights of Columbus",
    description:
      "The Knights of Columbus offers scholarships to Catholic students who are active in their faith community and demonstrate academic excellence and financial need. Awards of $1,500 support undergraduate studies at accredited Catholic institutions.",
    amount: "$1,500",
    amountMin: 1500,
    amountMax: 1500,
    deadline: new Date("2027-03-01"),
    url: "https://www.kofc.org/en/what-we-do/scholarships.html",
    scholarshipType: "merit-need",
    renewable: false,
    minGPA: 2.5,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayPrompt: "Describe how your Catholic faith and involvement in your parish community have shaped your academic and personal goals.",
    essayWordLimit: 500,
    submissionMethod: "portal",
    portalUrl: "https://www.kofc.org/en/what-we-do/scholarships.html",
    tags: ["religious", "Catholic", "faith", "community", "need-based"],
    sourceId: "knights-of-columbus",
    sourceUrl: "https://www.kofc.org/en/what-we-do/scholarships.html",
  },
  {
    title: "Presbyterian Church USA Scholarship",
    provider: "Presbyterian Church (USA) Foundation",
    description:
      "The PC(USA) offers $5,000 scholarships to students who are active members of a Presbyterian congregation. Awards support undergraduate and graduate students at accredited colleges and universities, with preference for students pursuing ministry or service-oriented fields.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2027-04-01"),
    url: "https://pcusa.org/resources/scholarships/",
    scholarshipType: "merit-need",
    renewable: false,
    minGPA: 2.5,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayPrompt: "How has your involvement in the Presbyterian Church shaped your sense of calling and your plans for the future?",
    essayWordLimit: 600,
    submissionMethod: "portal",
    portalUrl: "https://pcusa.org/resources/scholarships/",
    tags: ["religious", "Presbyterian", "faith", "ministry", "need-based"],
    sourceId: "presbyterian-church-usa",
    sourceUrl: "https://pcusa.org/resources/scholarships/",
  },
  {
    title: "United Methodist GBHEM Scholarship",
    provider: "General Board of Higher Education and Ministry (GBHEM)",
    description:
      "The United Methodist Church's General Board of Higher Education and Ministry awards $5,000 scholarships to undergraduate and graduate students who are active members of a United Methodist congregation. Applicants must be enrolled full-time at an accredited institution.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2027-05-01"),
    url: "https://www.gbhem.org/loans-scholarships/scholarships/",
    scholarshipType: "merit-need",
    renewable: false,
    minGPA: 2.5,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayPrompt: "Describe your involvement with the United Methodist Church and how your faith guides your educational aspirations.",
    essayWordLimit: 500,
    submissionMethod: "portal",
    portalUrl: "https://www.gbhem.org/loans-scholarships/scholarships/",
    tags: ["religious", "Methodist", "faith", "United-Methodist", "need-based"],
    sourceId: "united-methodist-gbhem",
    sourceUrl: "https://www.gbhem.org/loans-scholarships/scholarships/",
  },
  {
    title: "Jewish Federation Scholarship Program",
    provider: "Jewish Federations of North America",
    description:
      "Jewish Federations across North America award scholarships of up to $5,000 to Jewish students demonstrating academic merit, community involvement, and financial need. Applicants must be active in their local Jewish community and enrolled at an accredited college or university.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2027-03-15"),
    url: "https://www.jewishfederations.org/",
    scholarshipType: "merit-need",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayPrompt: "How has your Jewish identity and community involvement informed your educational goals and future plans?",
    essayWordLimit: 600,
    submissionMethod: "portal",
    portalUrl: "https://www.jewishfederations.org/",
    tags: ["religious", "Jewish", "faith", "community", "need-based", "merit"],
    sourceId: "jewish-federation",
    sourceUrl: "https://www.jewishfederations.org/",
  },
  {
    title: "Islamic Scholarship Fund",
    provider: "Islamic Scholarship Fund",
    description:
      "The Islamic Scholarship Fund awards $5,000 scholarships to Muslim American students pursuing degrees at accredited colleges and universities. Recipients are selected based on academic achievement, community service, and a demonstrated commitment to American Muslim civic engagement.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2027-02-28"),
    url: "https://islamicscholarshipfund.org/",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayPrompt: "How do you plan to use your education to contribute positively to the American Muslim community and broader society?",
    essayWordLimit: 700,
    submissionMethod: "portal",
    portalUrl: "https://islamicscholarshipfund.org/apply/",
    tags: ["religious", "Muslim", "Islamic", "civic-engagement", "community", "merit"],
    sourceId: "islamic-scholarship-fund",
    sourceUrl: "https://islamicscholarshipfund.org/",
  },

  // --- Fraternal (5) ---
  {
    title: "Elks Most Valuable Student Scholarship",
    provider: "Benevolent and Protective Order of Elks",
    description:
      "The Elks Most Valuable Student (MVS) Scholarship Program is one of the largest scholarship competitions in the country. Awards range from $4,000 to $60,000 over four years and are based on scholarship, leadership, and financial need. Five hundred students are selected nationally each year.",
    amount: "$4,000–$60,000",
    amountMin: 4000,
    amountMax: 60000,
    deadline: new Date("2027-11-15"),
    url: "https://www.elks.org/scholars/scholarships/mvs.cfm",
    scholarshipType: "merit-need",
    renewable: true,
    minGPA: 0,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen",
    essayRequired: true,
    essayWordLimit: 600,
    submissionMethod: "portal",
    portalUrl: "https://www.elks.org/scholars/scholarships/mvs.cfm",
    tags: ["fraternal", "Elks", "leadership", "merit-need", "renewable", "national"],
    sourceId: "elks-mvs",
    sourceUrl: "https://www.elks.org/scholars/scholarships/mvs.cfm",
  },
  {
    title: "Rotary Peace Fellowship",
    provider: "Rotary Foundation",
    description:
      "The Rotary Peace Fellowship funds up to 130 fellows each year to study at one of Rotary's peace centers worldwide. Fellows earn a master's degree in peace and conflict resolution and join a global network of peacebuilders. The fellowship covers tuition, fees, living expenses, and round-trip transportation.",
    amount: "$30,000",
    amountMin: 30000,
    amountMax: 30000,
    deadline: new Date("2027-05-31"),
    url: "https://www.rotary.org/en/our-programs/peace-fellowships",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["graduate"],
    fieldsOfStudy: ["international relations", "peace studies", "conflict resolution", "public policy"],
    essayRequired: true,
    essayWordLimit: 1500,
    submissionMethod: "portal",
    portalUrl: "https://www.rotary.org/en/our-programs/peace-fellowships",
    tags: ["fraternal", "Rotary", "peace", "international", "graduate", "full-funding"],
    sourceId: "rotary-peace-fellowship",
    sourceUrl: "https://www.rotary.org/en/our-programs/peace-fellowships",
  },
  {
    title: "Kiwanis Club Scholarship",
    provider: "Kiwanis International Foundation",
    description:
      "The Kiwanis International Foundation awards $10,000 scholarships to high school seniors who have demonstrated outstanding service to their communities, academic achievement, and leadership potential. Recipients are recognized for their commitment to improving the lives of children.",
    amount: "$10,000",
    amountMin: 10000,
    amountMax: 10000,
    deadline: new Date("2027-01-31"),
    url: "https://www.kiwanis.org/foundation/scholarships",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 500,
    submissionMethod: "portal",
    portalUrl: "https://www.kiwanis.org/foundation/scholarships",
    tags: ["fraternal", "Kiwanis", "service", "leadership", "community", "children"],
    sourceId: "kiwanis-scholarship",
    sourceUrl: "https://www.kiwanis.org/foundation/scholarships",
  },
  {
    title: "Lions Club International Scholarship",
    provider: "Lions Clubs International Foundation",
    description:
      "Lions Clubs International Foundation awards $5,000 scholarships to students who demonstrate academic excellence, community service, and leadership. Local Lions Clubs sponsor applicants, who must have a connection to the Lions family or embody Lions values of service and volunteerism.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2027-04-15"),
    url: "https://www.lionsclubs.org/en/lions-resources/grant-awards/scholarship",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 2.5,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 400,
    submissionMethod: "email",
    tags: ["fraternal", "Lions-Club", "service", "volunteerism", "community", "leadership"],
    sourceId: "lions-club-scholarship",
    sourceUrl: "https://www.lionsclubs.org/en/lions-resources/grant-awards/scholarship",
  },
  {
    title: "Masonic Grand Lodge Scholarship",
    provider: "Masonic Foundation",
    description:
      "The Masonic Foundation awards $10,000 scholarships to students who are Masons, relatives of Masons, or who demonstrate the Masonic values of brotherly love, relief, and truth. Recipients are selected based on academic achievement, character, and service to community.",
    amount: "$10,000",
    amountMin: 10000,
    amountMax: 10000,
    deadline: new Date("2027-03-31"),
    url: "https://www.masonicfoundation.org/scholarships",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 500,
    submissionMethod: "portal",
    portalUrl: "https://www.masonicfoundation.org/scholarships",
    tags: ["fraternal", "Masonic", "character", "service", "community", "heritage"],
    sourceId: "masonic-grand-lodge",
    sourceUrl: "https://www.masonicfoundation.org/scholarships",
  },

  // --- Unusual (5) ---
  {
    title: "Tall Clubs International Scholarship",
    provider: "Tall Clubs International",
    description:
      "The Tall Clubs International Scholarship awards $1,000 to tall young adults (women must be at least 5'10\" and men must be at least 6'2\") who demonstrate academic achievement and involvement in their community. This unique scholarship celebrates height as a positive attribute.",
    amount: "$1,000",
    amountMin: 1000,
    amountMax: 1000,
    deadline: new Date("2027-03-01"),
    url: "https://tall.org/tci-scholarships/",
    scholarshipType: "merit",
    renewable: false,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    eligibilityText: "Women must be at least 5'10\" and men must be at least 6'2\" tall.",
    essayRequired: true,
    essayPrompt: "How has your height influenced your life experiences, personal development, and outlook?",
    essayWordLimit: 500,
    submissionMethod: "portal",
    portalUrl: "https://tall.org/tci-scholarships/",
    tags: ["unusual", "height", "unique-eligibility", "community", "merit"],
    sourceId: "tall-clubs-international",
    sourceUrl: "https://tall.org/tci-scholarships/",
  },
  {
    title: "Duck Brand Stuck at Prom Scholarship",
    provider: "Duck Brand / ShurTech Brands",
    description:
      "The Duck Brand Stuck at Prom Scholarship awards $10,000 to the couple that creates the best-looking prom attire made entirely from Duck Tape. Contestants submit photos of their duct tape outfits and compete in online voting. One of the most unusual scholarships available to high school students.",
    amount: "$10,000",
    amountMin: 10000,
    amountMax: 10000,
    deadline: new Date("2027-05-31"),
    url: "https://www.duckbrand.com/stuck-at-prom",
    scholarshipType: "contest",
    renewable: false,
    educationLevels: ["undergraduate"],
    essayRequired: false,
    submissionMethod: "portal",
    portalUrl: "https://www.duckbrand.com/stuck-at-prom",
    tags: ["unusual", "contest", "creative", "prom", "Duck-Tape", "high-school"],
    sourceId: "duck-brand-stuck-at-prom",
    sourceUrl: "https://www.duckbrand.com/stuck-at-prom",
  },
  {
    title: "Vegetarian Resource Group Scholarship",
    provider: "Vegetarian Resource Group",
    description:
      "The Vegetarian Resource Group awards two $10,000 scholarships to graduating high school seniors who have promoted vegetarianism or veganism in their schools and communities. Applicants must demonstrate dedication to a vegetarian or vegan lifestyle and animal welfare advocacy.",
    amount: "$10,000",
    amountMin: 10000,
    amountMax: 10000,
    deadline: new Date("2027-02-20"),
    url: "https://www.vrg.org/student/scholar.htm",
    scholarshipType: "merit",
    renewable: false,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayPrompt: "How have you promoted vegetarianism or veganism in your school or community, and how has a plant-based lifestyle influenced your personal values and future goals?",
    essayWordLimit: 500,
    submissionMethod: "email",
    tags: ["unusual", "vegetarian", "vegan", "animal-welfare", "advocacy", "environmental"],
    sourceId: "vrg-scholarship",
    sourceUrl: "https://www.vrg.org/student/scholar.htm",
  },
  {
    title: "Zombie Apocalypse Scholarship",
    provider: "Unigo",
    description:
      "Unigo's Zombie Apocalypse Scholarship is a fun, creative competition awarding $2,000 to the student who best explains how they would survive a zombie apocalypse and what college major would help them. It's designed to encourage creative thinking and show that college is the best preparation for any challenge.",
    amount: "$2,000",
    amountMin: 2000,
    amountMax: 2000,
    deadline: new Date("2027-10-31"),
    url: "https://www.unigo.com/scholarships/all/zombie-apocalypse-scholarship",
    scholarshipType: "contest",
    renewable: false,
    educationLevels: ["undergraduate", "graduate"],
    essayRequired: true,
    essayPrompt: "Describe how you would survive a zombie apocalypse and explain which college major would best prepare you for that scenario.",
    essayWordLimit: 250,
    submissionMethod: "portal",
    portalUrl: "https://www.unigo.com/scholarships/all/zombie-apocalypse-scholarship",
    tags: ["unusual", "creative", "fun", "contest", "zombies", "Unigo"],
    sourceId: "zombie-apocalypse-scholarship",
    sourceUrl: "https://www.unigo.com/scholarships/all/zombie-apocalypse-scholarship",
  },
  {
    title: "Patrick Kerr Skateboard Scholarship",
    provider: "Skateboard Scholarship Fund",
    description:
      "The Patrick Kerr Skateboard Scholarship awards $5,000 to students who are avid skateboarders and who demonstrate academic achievement and community involvement. Created in honor of Patrick Kerr, the scholarship celebrates the skateboarding community's culture of perseverance and creativity.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2027-04-01"),
    url: "https://skateboardscholarship.com/",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 2.5,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayPrompt: "Describe how skateboarding has influenced your life, values, and goals for the future.",
    essayWordLimit: 500,
    submissionMethod: "portal",
    portalUrl: "https://skateboardscholarship.com/apply",
    tags: ["unusual", "skateboarding", "athletics", "community", "creativity", "perseverance"],
    sourceId: "patrick-kerr-skateboard",
    sourceUrl: "https://skateboardscholarship.com/",
  },

  // --- Condition-specific (5) ---
  {
    title: "ADHD Scholarship Award",
    provider: "Anne Ford Scholarship / NCLD",
    description:
      "The National Center for Learning Disabilities awards a $2,000 scholarship to an outstanding graduating high school senior with a documented learning disability or ADHD. The award recognizes academic perseverance and personal achievement in the face of learning challenges.",
    amount: "$2,000",
    amountMin: 2000,
    amountMax: 2000,
    deadline: new Date("2027-02-01"),
    url: "https://www.ncld.org/anne-ford-scholarship/",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    eligibilityText: "Must have a documented learning disability (e.g., dyslexia, ADHD) and be enrolled full-time at a four-year college or university.",
    essayRequired: true,
    essayPrompt: "Describe the challenges you have faced because of your learning disability and how you have overcome them to achieve academic and personal success.",
    essayWordLimit: 1000,
    submissionMethod: "portal",
    portalUrl: "https://www.ncld.org/anne-ford-scholarship/",
    tags: ["disability", "ADHD", "learning-disability", "perseverance", "NCLD"],
    sourceId: "adhd-scholarship",
    sourceUrl: "https://www.ncld.org/anne-ford-scholarship/",
  },
  {
    title: "Diabetes Scholars Foundation Scholarship",
    provider: "Diabetes Scholars Foundation",
    description:
      "The Diabetes Scholars Foundation awards scholarships of up to $5,000 to college students who have Type 1 diabetes. Recipients are selected based on academic achievement, community involvement, and the demonstrated ability to manage their diabetes while pursuing their education.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2027-06-01"),
    url: "https://www.diabetesscholars.org/scholarship/",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 2.5,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    eligibilityText: "Must have Type 1 diabetes and be enrolled at an accredited college or university.",
    essayRequired: true,
    essayPrompt: "How has managing Type 1 diabetes shaped your character, resilience, and outlook on life?",
    essayWordLimit: 500,
    submissionMethod: "portal",
    portalUrl: "https://www.diabetesscholars.org/scholarship/",
    tags: ["disability", "diabetes", "Type-1", "chronic-illness", "resilience", "health"],
    sourceId: "diabetes-scholars",
    sourceUrl: "https://www.diabetesscholars.org/scholarship/",
  },
  {
    title: "Cancer for College Scholarship",
    provider: "Cancer for College",
    description:
      "Cancer for College awards $10,000 scholarships to cancer survivors and amputees who demonstrate academic achievement and a commitment to giving back to their communities. Founded by Craig Pollard, a cancer survivor himself, the program supports students who have faced extraordinary medical challenges.",
    amount: "$10,000",
    amountMin: 10000,
    amountMax: 10000,
    deadline: new Date("2027-01-31"),
    url: "https://www.cancerforcollege.org/",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 2.75,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    eligibilityText: "Must be a cancer survivor, current cancer patient, or amputee.",
    essayRequired: true,
    essayPrompt: "Describe your cancer experience and how it has influenced your educational and life goals.",
    essayWordLimit: 500,
    submissionMethod: "portal",
    portalUrl: "https://www.cancerforcollege.org/apply/",
    tags: ["disability", "cancer", "survivor", "chronic-illness", "amputee", "resilience"],
    sourceId: "cancer-for-college",
    sourceUrl: "https://www.cancerforcollege.org/",
  },
  {
    title: "AG Bell College Scholarship Program",
    provider: "Alexander Graham Bell Association for the Deaf and Hard of Hearing",
    description:
      "The AG Bell Association awards scholarships of $3,000 to students who are deaf or hard of hearing and who use spoken language as their primary mode of communication. Recipients are selected based on academic achievement, financial need, and a commitment to serving the hearing loss community.",
    amount: "$3,000",
    amountMin: 3000,
    amountMax: 3000,
    deadline: new Date("2027-03-15"),
    url: "https://www.agbell.org/professionals-and-families/ag-bell-college-scholarship-awards/",
    scholarshipType: "merit-need",
    renewable: false,
    minGPA: 3.25,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    eligibilityText: "Must be deaf or hard of hearing with bilateral hearing loss of 60 dB or more, and use spoken language as primary mode of communication.",
    essayRequired: true,
    essayPrompt: "How has your hearing loss shaped your identity, and how do you plan to use your education to contribute to the deaf and hard-of-hearing community?",
    essayWordLimit: 800,
    submissionMethod: "portal",
    portalUrl: "https://www.agbell.org/professionals-and-families/ag-bell-college-scholarship-awards/",
    tags: ["disability", "hearing-loss", "deaf", "hard-of-hearing", "AG-Bell", "accessibility"],
    sourceId: "ag-bell-scholarship",
    sourceUrl: "https://www.agbell.org/professionals-and-families/ag-bell-college-scholarship-awards/",
  },
  {
    title: "Epilepsy Foundation Scholarship",
    provider: "Epilepsy Foundation of America",
    description:
      "The Epilepsy Foundation awards $5,000 scholarships to individuals with epilepsy who demonstrate academic achievement, financial need, and community involvement. The scholarship aims to reduce barriers to higher education for students living with epilepsy and related seizure disorders.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2027-04-08"),
    url: "https://www.epilepsy.com/living-epilepsy/epilepsy-foundation-scholarships",
    scholarshipType: "merit-need",
    renewable: false,
    minGPA: 2.5,
    educationLevels: ["undergraduate", "graduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    eligibilityText: "Must have a diagnosis of epilepsy or a seizure disorder and be under physician's care.",
    essayRequired: true,
    essayPrompt: "Describe how living with epilepsy has impacted your life and how your education will help you achieve your goals and contribute to your community.",
    essayWordLimit: 500,
    submissionMethod: "portal",
    portalUrl: "https://www.epilepsy.com/living-epilepsy/epilepsy-foundation-scholarships",
    tags: ["disability", "epilepsy", "seizure", "chronic-illness", "need-based", "health"],
    sourceId: "epilepsy-foundation",
    sourceUrl: "https://www.epilepsy.com/living-epilepsy/epilepsy-foundation-scholarships",
  },
];
