import type { ScholarshipSource, ScrapedScholarship, ScholarshipFilters } from "./types";

export class ProfessionalAssociationsSource implements ScholarshipSource {
  id = "professional";
  name = "Professional Association Scholarships";
  type = "foundation" as const;

  isEnabled(): boolean {
    return true;
  }

  async scrape(_filters?: ScholarshipFilters): Promise<ScrapedScholarship[]> {
    return PROFESSIONAL_SCHOLARSHIPS;
  }
}

const PROFESSIONAL_SCHOLARSHIPS: ScrapedScholarship[] = [
  {
    title: "AMA Foundation Physicians of Tomorrow Scholarship",
    provider: "American Medical Association (AMA) Foundation",
    description:
      "The AMA Foundation Physicians of Tomorrow Scholarship awards $10,000 to fourth-year medical students who demonstrate academic achievement, financial need, and a commitment to medicine's ideals. Recipients are selected for their potential to become outstanding physicians and contribute to the medical profession.",
    amount: "$10,000",
    amountMin: 10000,
    amountMax: 10000,
    deadline: new Date("2027-04-30"),
    url: "https://www.ama-assn.org/member-groups-sections/medical-students/ama-foundation-scholarships",
    scholarshipType: "merit-need",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["graduate"],
    fieldsOfStudy: ["medicine", "medical school", "health sciences"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 600,
    submissionMethod: "portal",
    portalUrl: "https://www.ama-assn.org/member-groups-sections/medical-students/ama-foundation-scholarships",
    tags: ["medicine", "medical-school", "healthcare", "AMA", "professional-association"],
    sourceId: "ama-physicians-tomorrow",
    sourceUrl: "https://www.ama-assn.org/member-groups-sections/medical-students/ama-foundation-scholarships",
  },
  {
    title: "ABA Legal Opportunity Scholarship",
    provider: "American Bar Association (ABA)",
    description:
      "The ABA Legal Opportunity Scholarship awards $15,000 over three years ($5,000 per year) to law students from racial and ethnic minority groups to help diversify the legal profession. Recipients must demonstrate financial need and a commitment to serving underrepresented communities through legal practice.",
    amount: "$15,000 (over 3 years)",
    amountMin: 5000,
    amountMax: 15000,
    deadline: new Date("2027-02-01"),
    url: "https://www.americanbar.org/groups/diversity/racial_ethnic_diversity/initiatives_awards/legal_opportunity_scholarship/",
    scholarshipType: "merit-need",
    renewable: true,
    minGPA: 0,
    educationLevels: ["graduate"],
    fieldsOfStudy: ["law", "legal studies"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 1000,
    submissionMethod: "portal",
    portalUrl: "https://www.americanbar.org/groups/diversity/racial_ethnic_diversity/initiatives_awards/legal_opportunity_scholarship/",
    tags: ["law", "legal", "diversity", "minority", "ABA", "professional-association", "renewable"],
    sourceId: "aba-legal-opportunity",
    sourceUrl: "https://www.americanbar.org/groups/diversity/racial_ethnic_diversity/initiatives_awards/legal_opportunity_scholarship/",
  },
  {
    title: "IEEE Scholarship Plus Initiative",
    provider: "IEEE Foundation",
    description:
      "The IEEE Scholarship Plus Initiative awards $10,000 scholarships to electrical engineering, computer engineering, and computer science students who demonstrate academic excellence and leadership. Recipients also receive mentoring from IEEE professional members and opportunities to network within the global engineering community.",
    amount: "$10,000",
    amountMin: 10000,
    amountMax: 10000,
    deadline: new Date("2027-05-31"),
    url: "https://www.ieee.org/education/scholarships/scholarship-plus-initiative.html",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate"],
    fieldsOfStudy: ["electrical engineering", "computer engineering", "computer science", "STEM"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 500,
    submissionMethod: "portal",
    portalUrl: "https://www.ieee.org/education/scholarships/scholarship-plus-initiative.html",
    tags: ["engineering", "IEEE", "electrical-engineering", "computer-science", "professional-association", "STEM"],
    sourceId: "ieee-scholarship-plus",
    sourceUrl: "https://www.ieee.org/education/scholarships/scholarship-plus-initiative.html",
  },
  {
    title: "ACM/CSTA Cutler-Bell Prize in High School Computing",
    provider: "Association for Computing Machinery (ACM) & CSTA",
    description:
      "The ACM/CSTA Cutler-Bell Prize awards $10,000 to high school students who demonstrate excellence and creativity in computer science. Students submit original computational artifacts — programs, algorithms, or applications — that address a real-world problem or push computing boundaries.",
    amount: "$10,000",
    amountMin: 10000,
    amountMax: 10000,
    deadline: new Date("2027-11-01"),
    url: "https://csta.acm.org/Programs/sub/CutlerBell.html",
    scholarshipType: "merit",
    renewable: false,
    educationLevels: ["undergraduate"],
    fieldsOfStudy: ["computer science", "software engineering", "technology", "programming"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 800,
    submissionMethod: "portal",
    portalUrl: "https://csta.acm.org/Programs/sub/CutlerBell.html",
    tags: ["computer-science", "programming", "ACM", "CSTA", "innovation", "high-school", "professional-association"],
    sourceId: "acm-csta-cutler-bell",
    sourceUrl: "https://csta.acm.org/Programs/sub/CutlerBell.html",
  },
  {
    title: "ASCE Civil Engineering Scholarship",
    provider: "American Society of Civil Engineers (ASCE)",
    description:
      "The American Society of Civil Engineers offers multiple scholarships of $5,000 to undergraduate and graduate civil engineering students who demonstrate academic excellence, leadership, and a commitment to the civil engineering profession. Recipients are encouraged to become active ASCE members.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2027-02-10"),
    url: "https://www.asce.org/career-growth/awards-and-honors/scholarships",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate", "graduate"],
    fieldsOfStudy: ["civil engineering", "structural engineering", "environmental engineering"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 500,
    submissionMethod: "portal",
    portalUrl: "https://www.asce.org/career-growth/awards-and-honors/scholarships",
    tags: ["engineering", "civil-engineering", "ASCE", "professional-association", "infrastructure"],
    sourceId: "asce-civil-engineering",
    sourceUrl: "https://www.asce.org/career-growth/awards-and-honors/scholarships",
  },
  {
    title: "ASME Scholarships",
    provider: "American Society of Mechanical Engineers (ASME)",
    description:
      "ASME offers dozens of scholarship programs totaling $5,000 per award for undergraduate and graduate mechanical engineering students. Scholarships are distributed through the ASME Foundation and recognize academic excellence, leadership, and a commitment to advancing the mechanical engineering profession.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2027-03-31"),
    url: "https://www.asme.org/asme-programs/students/scholarships",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 2.5,
    educationLevels: ["undergraduate", "graduate"],
    fieldsOfStudy: ["mechanical engineering", "engineering", "manufacturing", "robotics"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 500,
    submissionMethod: "portal",
    portalUrl: "https://www.asme.org/asme-programs/students/scholarships",
    tags: ["engineering", "mechanical-engineering", "ASME", "professional-association", "manufacturing"],
    sourceId: "asme-scholarships",
    sourceUrl: "https://www.asme.org/asme-programs/students/scholarships",
  },
  {
    title: "APA Psychology Scholarship",
    provider: "American Psychological Association (APA)",
    description:
      "The APA offers $5,000 scholarships to undergraduate and graduate students pursuing psychology degrees, with special consideration for students from underrepresented populations. Recipients demonstrate strong academic performance and a commitment to advancing psychological science and practice.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2027-01-15"),
    url: "https://www.apa.org/about/awards/scholarships",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate", "graduate"],
    fieldsOfStudy: ["psychology", "behavioral science", "neuroscience", "counseling"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 600,
    submissionMethod: "portal",
    portalUrl: "https://www.apa.org/about/awards/scholarships",
    tags: ["psychology", "APA", "behavioral-science", "mental-health", "professional-association"],
    sourceId: "apa-psychology",
    sourceUrl: "https://www.apa.org/about/awards/scholarships",
  },
  {
    title: "NASW Foundation Social Work Scholarship",
    provider: "National Association of Social Workers (NASW) Foundation",
    description:
      "The NASW Foundation awards $5,000 scholarships to BSW and MSW students who demonstrate academic excellence and a commitment to social justice and advocacy. Priority is given to students from historically underrepresented groups who plan to work in underserved communities.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2027-03-01"),
    url: "https://naswfoundation.org/Grants-Fellowships/Scholarships",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate", "graduate"],
    fieldsOfStudy: ["social work", "human services", "community development"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 500,
    submissionMethod: "portal",
    portalUrl: "https://naswfoundation.org/Grants-Fellowships/Scholarships",
    tags: ["social-work", "NASW", "social-justice", "advocacy", "underrepresented", "professional-association"],
    sourceId: "nasw-social-work",
    sourceUrl: "https://naswfoundation.org/Grants-Fellowships/Scholarships",
  },
  {
    title: "AAAS Mass Media Science & Engineering Fellowship",
    provider: "American Association for the Advancement of Science (AAAS)",
    description:
      "The AAAS Mass Media Fellowship awards $5,000 plus a living stipend to science students who work with media organizations to improve public understanding of science. Fellows spend 10 weeks at major news outlets learning to communicate complex scientific topics to general audiences.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2027-01-01"),
    url: "https://www.aaas.org/programs/mass-media-fellowship",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 0,
    educationLevels: ["graduate"],
    fieldsOfStudy: ["science", "biology", "chemistry", "physics", "environmental science", "STEM"],
    essayRequired: true,
    essayWordLimit: 800,
    submissionMethod: "portal",
    portalUrl: "https://www.aaas.org/programs/mass-media-fellowship",
    tags: ["science", "AAAS", "journalism", "science-communication", "media", "professional-association"],
    sourceId: "aaas-mass-media",
    sourceUrl: "https://www.aaas.org/programs/mass-media-fellowship",
  },
  {
    title: "ACS Scholars Program",
    provider: "American Chemical Society (ACS)",
    description:
      "The ACS Scholars Program awards renewable scholarships of up to $5,000 to African American, Hispanic, and American Indian students pursuing degrees in chemistry or chemistry-related fields. The program aims to increase diversity in the chemical sciences and prepares scholars for careers in STEM.",
    amount: "Up to $5,000",
    amountMin: 2500,
    amountMax: 5000,
    deadline: new Date("2027-03-01"),
    url: "https://www.acs.org/content/acs/en/funding/scholarships-fellowships/acs-scholars.html",
    scholarshipType: "merit-need",
    renewable: true,
    minGPA: 3.0,
    educationLevels: ["undergraduate"],
    fieldsOfStudy: ["chemistry", "biochemistry", "chemical engineering", "materials science"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 500,
    submissionMethod: "portal",
    portalUrl: "https://www.acs.org/content/acs/en/funding/scholarships-fellowships/acs-scholars.html",
    tags: ["chemistry", "ACS", "minority", "underrepresented", "STEM", "renewable", "professional-association"],
    sourceId: "acs-scholars",
    sourceUrl: "https://www.acs.org/content/acs/en/funding/scholarships-fellowships/acs-scholars.html",
  },
  {
    title: "AICPA Scholarship for Minority Accounting Students",
    provider: "American Institute of CPAs (AICPA)",
    description:
      "The AICPA Foundation awards $10,000 scholarships to African American, Hispanic, Native American, and Pacific Islander accounting students pursuing CPA certification. The program aims to diversify the accounting profession by supporting talented minority students through their education.",
    amount: "$10,000",
    amountMin: 10000,
    amountMax: 10000,
    deadline: new Date("2027-04-01"),
    url: "https://www.aicpa-cima.com/scholarships",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate", "graduate"],
    fieldsOfStudy: ["accounting", "finance", "business", "CPA"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 500,
    submissionMethod: "portal",
    portalUrl: "https://www.aicpa-cima.com/scholarships",
    tags: ["accounting", "AICPA", "CPA", "minority", "finance", "business", "professional-association"],
    sourceId: "aicpa-minority",
    sourceUrl: "https://www.aicpa-cima.com/scholarships",
  },
  {
    title: "AIA/AAF Minority/Disadvantaged Scholarship",
    provider: "American Institute of Architects (AIA) / American Architectural Foundation (AAF)",
    description:
      "The AIA/AAF Scholarship Program awards $5,000 to architecture students from minority or economically disadvantaged backgrounds who demonstrate academic excellence and commitment to the profession. The program increases diversity in architecture and supports emerging designers.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2027-04-15"),
    url: "https://www.aia.org/education-events/scholarships",
    scholarshipType: "merit-need",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate", "graduate"],
    fieldsOfStudy: ["architecture", "urban planning", "interior architecture", "design"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 600,
    submissionMethod: "portal",
    portalUrl: "https://www.aia.org/education-events/scholarships",
    tags: ["architecture", "AIA", "minority", "design", "disadvantaged", "professional-association"],
    sourceId: "aia-aaf-scholarship",
    sourceUrl: "https://www.aia.org/education-events/scholarships",
  },
  {
    title: "NSA Stokes Educational Scholarship Program",
    provider: "National Security Agency (NSA)",
    description:
      "The NSA Stokes Program awards scholarships of up to $25,000 per year to exceptional math and computer science students who agree to work for the NSA after graduation. In addition to scholarship funding, recipients receive paid summer employment at NSA headquarters in Fort Meade, Maryland.",
    amount: "Up to $25,000/year",
    amountMin: 20000,
    amountMax: 25000,
    deadline: new Date("2027-11-15"),
    url: "https://www.intelligencecareers.gov/nsa/nsastudents.html",
    scholarshipType: "merit",
    renewable: true,
    minGPA: 3.0,
    educationLevels: ["undergraduate"],
    fieldsOfStudy: ["mathematics", "computer science", "electrical engineering", "STEM"],
    citizenshipRequired: "US Citizen",
    essayRequired: true,
    essayWordLimit: 800,
    submissionMethod: "portal",
    portalUrl: "https://www.intelligencecareers.gov/nsa/nsastudents.html",
    tags: ["NSA", "mathematics", "computer-science", "government", "security-clearance", "employment", "renewable"],
    sourceId: "nsa-stokes",
    sourceUrl: "https://www.intelligencecareers.gov/nsa/nsastudents.html",
  },
  {
    title: "SWE Scholarship Program",
    provider: "Society of Women Engineers (SWE)",
    description:
      "The Society of Women Engineers distributes over $1 million in scholarships annually, including numerous individual awards of $15,000, to women pursuing engineering and computer science degrees. SWE scholarships recognize women for academic excellence and leadership in their fields.",
    amount: "Up to $15,000",
    amountMin: 1000,
    amountMax: 15000,
    deadline: new Date("2027-02-15"),
    url: "https://scholarships.swe.org/",
    scholarshipType: "merit",
    renewable: true,
    minGPA: 3.0,
    educationLevels: ["undergraduate", "graduate"],
    fieldsOfStudy: ["engineering", "computer science", "technology", "STEM", "mechanical engineering", "electrical engineering"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 700,
    submissionMethod: "portal",
    portalUrl: "https://scholarships.swe.org/",
    tags: ["engineering", "women", "SWE", "gender-diversity", "STEM", "computer-science", "professional-association", "renewable"],
    sourceId: "swe-scholarship",
    sourceUrl: "https://scholarships.swe.org/",
  },
  {
    title: "SHPE Scholarship Program",
    provider: "Society of Hispanic Professional Engineers (SHPE)",
    description:
      "SHPE awards $5,000 scholarships to Hispanic undergraduate and graduate students pursuing STEM degrees. Recipients demonstrate academic excellence, community service, and a commitment to increasing Hispanic representation in science, technology, engineering, and mathematics.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2027-04-01"),
    url: "https://shpe.org/membership/scholarships/",
    scholarshipType: "merit",
    renewable: false,
    minGPA: 3.0,
    educationLevels: ["undergraduate", "graduate"],
    fieldsOfStudy: ["engineering", "computer science", "mathematics", "science", "technology", "STEM"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    essayRequired: true,
    essayWordLimit: 500,
    submissionMethod: "portal",
    portalUrl: "https://shpe.org/membership/scholarships/",
    tags: ["Hispanic", "Latino", "engineering", "SHPE", "STEM", "diversity", "professional-association"],
    sourceId: "shpe-scholarship",
    sourceUrl: "https://shpe.org/membership/scholarships/",
  },
];
