import type { ScholarshipSource, ScrapedScholarship, ScholarshipFilters } from "./types";

export class StateScholarshipsSource implements ScholarshipSource {
  id = "state-programs";
  name = "State Scholarship Programs";
  type = "state" as const;

  isEnabled(): boolean {
    return true;
  }

  async scrape(_filters?: ScholarshipFilters): Promise<ScrapedScholarship[]> {
    return STATE_SCHOLARSHIPS;
  }
}

const STATE_SCHOLARSHIPS: ScrapedScholarship[] = [
  {
    title: "Cal Grant A",
    provider: "California Student Aid Commission (CSAC)",
    description:
      "Cal Grant A covers up to $12,570 in annual tuition and fees at UC, CSU, and qualifying independent and career colleges in California. It is awarded to high school graduates and transfer students who demonstrate financial need and meet academic requirements. Recipients must be California residents enrolled at least half-time.",
    amount: "Up to $12,570",
    amountMin: 0,
    amountMax: 12570,
    deadline: new Date("2027-03-02"),
    url: "https://www.csac.ca.gov/cal-grants",
    scholarshipType: "need-based",
    renewable: true,
    minGPA: 2.4,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    stateRestriction: "CA",
    eligibilityText: "Must be a California resident attending a qualifying CA institution with demonstrated financial need.",
    essayRequired: false,
    submissionMethod: "portal",
    portalUrl: "https://www.csac.ca.gov/cal-grants",
    tags: ["need-based", "California", "state-grant", "renewable", "tuition", "Cal-Grant"],
    sourceId: "cal-grant-a",
    sourceUrl: "https://www.csac.ca.gov/cal-grants",
  },
  {
    title: "CSAC Middle Class Scholarship",
    provider: "California Student Aid Commission (CSAC)",
    description:
      "The Middle Class Scholarship reduces tuition and student fee costs for California residents at UC or CSU campuses from families earning up to $201,000. Awards can be up to $10,000 per year depending on family income and institutional costs. Designed to bridge the gap for middle-income families that earn too much for traditional aid.",
    amount: "Up to $10,000",
    amountMin: 0,
    amountMax: 10000,
    deadline: new Date("2027-03-02"),
    url: "https://www.csac.ca.gov/middle-class-scholarship",
    scholarshipType: "need-based",
    renewable: true,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    stateRestriction: "CA",
    eligibilityText: "Must be a California resident at a UC or CSU campus with family income under $201,000.",
    essayRequired: false,
    submissionMethod: "portal",
    portalUrl: "https://www.csac.ca.gov/middle-class-scholarship",
    tags: ["need-based", "California", "middle-class", "state-grant", "UC", "CSU", "renewable"],
    sourceId: "csac-middle-class",
    sourceUrl: "https://www.csac.ca.gov/middle-class-scholarship",
  },
  {
    title: "NYS Tuition Assistance Program (TAP)",
    provider: "New York State Higher Education Services Corporation (HESC)",
    description:
      "The New York State Tuition Assistance Program (TAP) provides up to $5,500 per year to eligible New York residents attending in-state colleges and universities. Awards are based on net taxable income and are renewable for up to four years of undergraduate study.",
    amount: "Up to $5,500",
    amountMin: 500,
    amountMax: 5500,
    deadline: new Date("2027-04-30"),
    url: "https://www.hesc.ny.gov/pay-for-college/apply-for-financial-aid/nys-tap.html",
    scholarshipType: "need-based",
    renewable: true,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    stateRestriction: "NY",
    eligibilityText: "Must be a New York State resident enrolled full-time at an approved NY institution and meet income limits.",
    essayRequired: false,
    submissionMethod: "portal",
    portalUrl: "https://www.hesc.ny.gov/",
    tags: ["need-based", "New-York", "state-grant", "TAP", "renewable", "tuition"],
    sourceId: "nys-tap",
    sourceUrl: "https://www.hesc.ny.gov/pay-for-college/apply-for-financial-aid/nys-tap.html",
  },
  {
    title: "Excelsior Scholarship",
    provider: "New York State Higher Education Services Corporation (HESC)",
    description:
      "The Excelsior Scholarship provides last-dollar tuition coverage at SUNY and CUNY institutions for New York residents from families earning $125,000 or less annually. Combined with other financial aid, the scholarship covers any remaining tuition balance. Recipients must commit to living and working in New York for the same number of years the award was received.",
    amount: "Up to $7,500",
    amountMin: 0,
    amountMax: 7500,
    deadline: new Date("2027-07-31"),
    url: "https://www.hesc.ny.gov/pay-for-college/apply-for-financial-aid/tuition-free-excelsior-scholarship.html",
    scholarshipType: "need-based",
    renewable: true,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    stateRestriction: "NY",
    eligibilityText: "Must be NY resident attending SUNY/CUNY full-time with family income under $125,000. Must live and work in NY after graduation.",
    essayRequired: false,
    submissionMethod: "portal",
    portalUrl: "https://www.hesc.ny.gov/",
    tags: ["need-based", "New-York", "Excelsior", "SUNY", "CUNY", "tuition-free", "renewable"],
    sourceId: "excelsior-scholarship",
    sourceUrl: "https://www.hesc.ny.gov/pay-for-college/apply-for-financial-aid/tuition-free-excelsior-scholarship.html",
  },
  {
    title: "TEXAS Grant",
    provider: "Texas Higher Education Coordinating Board",
    description:
      "The Toward EXcellence, Access, and Success (TEXAS) Grant program provides up to $10,000 annually to eligible Texas residents who demonstrate financial need and graduate from a Texas public high school. Recipients must be enrolled at a Texas public institution of higher education.",
    amount: "Up to $10,000",
    amountMin: 0,
    amountMax: 10000,
    deadline: new Date("2027-01-15"),
    url: "https://www.highered.texas.gov/apps/financial-aid/texas-grant/",
    scholarshipType: "need-based",
    renewable: true,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    stateRestriction: "TX",
    eligibilityText: "Must be a Texas resident, graduate from a Texas public high school, and demonstrate financial need.",
    essayRequired: false,
    submissionMethod: "portal",
    portalUrl: "https://www.highered.texas.gov/apps/financial-aid/texas-grant/",
    tags: ["need-based", "Texas", "state-grant", "TEXAS-Grant", "renewable", "public-school"],
    sourceId: "texas-grant",
    sourceUrl: "https://www.highered.texas.gov/apps/financial-aid/texas-grant/",
  },
  {
    title: "Top 10% Scholarship (Texas)",
    provider: "Texas Higher Education Coordinating Board",
    description:
      "The Top 10% Scholarship awards $5,000 per year to Texas residents who graduated in the top 10% of their Texas public high school class and demonstrate financial need. The scholarship is designed to reward academic excellence and encourage top students to attend Texas colleges.",
    amount: "$5,000",
    amountMin: 5000,
    amountMax: 5000,
    deadline: new Date("2027-01-15"),
    url: "https://www.highered.texas.gov/apps/financial-aid/top-10-percent/",
    scholarshipType: "merit-need",
    renewable: true,
    minGPA: 0,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    stateRestriction: "TX",
    eligibilityText: "Must be a Texas resident who graduated in the top 10% of a Texas public high school class and demonstrate financial need.",
    essayRequired: false,
    submissionMethod: "portal",
    portalUrl: "https://www.highered.texas.gov/apps/financial-aid/top-10-percent/",
    tags: ["merit-need", "Texas", "top-10-percent", "state-scholarship", "renewable", "academic"],
    sourceId: "texas-top-10",
    sourceUrl: "https://www.highered.texas.gov/apps/financial-aid/top-10-percent/",
  },
  {
    title: "Florida Bright Futures Scholarship",
    provider: "Florida Department of Education",
    description:
      "The Florida Bright Futures Scholarship Program provides merit-based awards to Florida high school graduates who achieve high academic standards. The Florida Academic Scholars award covers up to 100% of tuition at Florida public institutions (up to $9,000/year). The program recognizes students who work hard in high school and rewards them for their efforts.",
    amount: "Up to $9,000",
    amountMin: 3000,
    amountMax: 9000,
    deadline: new Date("2027-08-31"),
    url: "https://www.floridastudentfinancialaidsg.org/SAPHome/SAPHome?url=home",
    scholarshipType: "merit",
    renewable: true,
    minGPA: 3.5,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    stateRestriction: "FL",
    eligibilityText: "Must be a Florida resident, graduate from a Florida high school, and meet GPA and standardized test score requirements.",
    essayRequired: false,
    submissionMethod: "portal",
    portalUrl: "https://www.floridastudentfinancialaidsg.org/",
    tags: ["merit", "Florida", "Bright-Futures", "state-scholarship", "renewable", "academic"],
    sourceId: "florida-bright-futures",
    sourceUrl: "https://www.floridastudentfinancialaidsg.org/",
  },
  {
    title: "First Generation Matching Grant (Florida)",
    provider: "Florida Department of Education",
    description:
      "Florida's First Generation Matching Grant Program provides need-based awards up to $4,000 to Florida residents who are the first in their family to attend college. Participating institutions match the state award dollar for dollar, doubling the financial assistance available.",
    amount: "Up to $4,000",
    amountMin: 0,
    amountMax: 4000,
    deadline: new Date("2027-05-01"),
    url: "https://www.floridastudentfinancialaidsg.org/SAPHome/SAPHome?url=home",
    scholarshipType: "need-based",
    renewable: true,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    stateRestriction: "FL",
    eligibilityText: "Must be a Florida resident, first-generation college student, and demonstrate financial need.",
    essayRequired: false,
    submissionMethod: "portal",
    portalUrl: "https://www.floridastudentfinancialaidsg.org/",
    tags: ["need-based", "Florida", "first-generation", "state-grant", "matching", "renewable"],
    sourceId: "florida-first-gen",
    sourceUrl: "https://www.floridastudentfinancialaidsg.org/",
  },
  {
    title: "Illinois Monetary Award Program (MAP Grant)",
    provider: "Illinois Student Assistance Commission (ISAC)",
    description:
      "The Illinois Monetary Award Program (MAP) is the state's primary need-based grant, providing up to $5,000 annually to eligible Illinois residents attending approved Illinois colleges and universities. Awards are based on demonstrated financial need and are limited to students enrolled at least half-time.",
    amount: "Up to $5,000",
    amountMin: 0,
    amountMax: 5000,
    deadline: new Date("2027-10-01"),
    url: "https://www.isac.org/students/before-college/financial-awareness/types-of-financial-aid/illinois-monetary-award-program/",
    scholarshipType: "need-based",
    renewable: true,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    stateRestriction: "IL",
    eligibilityText: "Must be an Illinois resident attending an approved Illinois institution with demonstrated financial need.",
    essayRequired: false,
    submissionMethod: "portal",
    portalUrl: "https://www.isac.org/",
    tags: ["need-based", "Illinois", "MAP-Grant", "state-grant", "renewable"],
    sourceId: "illinois-map-grant",
    sourceUrl: "https://www.isac.org/students/before-college/financial-awareness/types-of-financial-aid/illinois-monetary-award-program/",
  },
  {
    title: "Pennsylvania State Grant (PHEAA)",
    provider: "Pennsylvania Higher Education Assistance Agency (PHEAA)",
    description:
      "The Pennsylvania State Grant provides need-based financial assistance of up to $4,500 per year to Pennsylvania residents attending college at least half-time. The PHEAA State Grant is one of the most significant sources of grant aid available to Pennsylvania students and can be used at approved institutions in Pennsylvania and select out-of-state colleges.",
    amount: "Up to $4,500",
    amountMin: 0,
    amountMax: 4500,
    deadline: new Date("2027-05-01"),
    url: "https://www.pheaa.org/funding-opportunities/state-grant-program/",
    scholarshipType: "need-based",
    renewable: true,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    stateRestriction: "PA",
    eligibilityText: "Must be a Pennsylvania resident enrolled at least half-time at an approved institution with demonstrated financial need.",
    essayRequired: false,
    submissionMethod: "portal",
    portalUrl: "https://www.pheaa.org/",
    tags: ["need-based", "Pennsylvania", "PHEAA", "state-grant", "renewable"],
    sourceId: "pheaa-state-grant",
    sourceUrl: "https://www.pheaa.org/funding-opportunities/state-grant-program/",
  },
  {
    title: "MASSGrant (Massachusetts Need-Based Grant)",
    provider: "Massachusetts Office of Student Financial Assistance (OSFA)",
    description:
      "MASSGrant is Massachusetts' primary need-based grant program, providing up to $2,500 per year to state residents enrolled full-time at an approved Massachusetts institution. The program targets students from low- and moderate-income families who demonstrate financial need.",
    amount: "Up to $2,500",
    amountMin: 300,
    amountMax: 2500,
    deadline: new Date("2027-05-01"),
    url: "https://www.mass.edu/osfa/programs/massgrant.asp",
    scholarshipType: "need-based",
    renewable: true,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    stateRestriction: "MA",
    eligibilityText: "Must be a Massachusetts resident enrolled full-time at an approved MA institution with demonstrated financial need.",
    essayRequired: false,
    submissionMethod: "portal",
    portalUrl: "https://www.mass.edu/osfa/",
    tags: ["need-based", "Massachusetts", "MASSGrant", "state-grant", "renewable"],
    sourceId: "massgrant",
    sourceUrl: "https://www.mass.edu/osfa/programs/massgrant.asp",
  },
  {
    title: "HOPE Scholarship (Georgia)",
    provider: "Georgia Student Finance Commission",
    description:
      "The HOPE Scholarship provides merit-based assistance to Georgia residents who graduate from high school with a 3.0 GPA or higher. Recipients receive up to $7,500 annually toward tuition at any eligible Georgia public or private institution. The program, funded by the Georgia Lottery, celebrates and rewards academic achievement.",
    amount: "Up to $7,500",
    amountMin: 0,
    amountMax: 7500,
    deadline: new Date("2027-08-01"),
    url: "https://www.gsfc.georgia.gov/HOPE",
    scholarshipType: "merit",
    renewable: true,
    minGPA: 3.0,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    stateRestriction: "GA",
    eligibilityText: "Must be a Georgia resident who graduated from a Georgia high school with a 3.0 GPA and maintain a 3.0 GPA in college.",
    essayRequired: false,
    submissionMethod: "portal",
    portalUrl: "https://www.gsfc.georgia.gov/",
    tags: ["merit", "Georgia", "HOPE", "state-scholarship", "lottery-funded", "renewable"],
    sourceId: "georgia-hope",
    sourceUrl: "https://www.gsfc.georgia.gov/HOPE",
  },
  {
    title: "Ohio College Opportunity Grant (OCOG)",
    provider: "Ohio Department of Higher Education",
    description:
      "The Ohio College Opportunity Grant (OCOG) provides need-based grants of up to $4,000 annually to Ohio residents with exceptional financial need. Recipients must be enrolled full-time at an eligible Ohio two-year or four-year institution and demonstrate financial need through the FAFSA.",
    amount: "Up to $4,000",
    amountMin: 0,
    amountMax: 4000,
    deadline: new Date("2027-10-01"),
    url: "https://www.ohiohighered.org/ocog",
    scholarshipType: "need-based",
    renewable: true,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    stateRestriction: "OH",
    eligibilityText: "Must be an Ohio resident attending an eligible Ohio institution with demonstrated exceptional financial need.",
    essayRequired: false,
    submissionMethod: "portal",
    portalUrl: "https://www.ohiohighered.org/",
    tags: ["need-based", "Ohio", "OCOG", "state-grant", "renewable"],
    sourceId: "ohio-ocog",
    sourceUrl: "https://www.ohiohighered.org/ocog",
  },
  {
    title: "NC Need-Based Scholarship",
    provider: "North Carolina State Education Assistance Authority (NCSEAA)",
    description:
      "The NC Need-Based Scholarship provides up to $6,000 annually to North Carolina residents demonstrating financial need who attend private, nonprofit colleges and universities in the state. The program helps students access the broad range of higher education options available in North Carolina.",
    amount: "Up to $6,000",
    amountMin: 100,
    amountMax: 6000,
    deadline: new Date("2027-03-01"),
    url: "https://www.ncseaa.edu/nc-financial-aid/nc-need-based-scholarship/",
    scholarshipType: "need-based",
    renewable: true,
    educationLevels: ["undergraduate"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    stateRestriction: "NC",
    eligibilityText: "Must be a North Carolina resident attending an approved private nonprofit NC institution with demonstrated financial need.",
    essayRequired: false,
    submissionMethod: "portal",
    portalUrl: "https://www.ncseaa.edu/",
    tags: ["need-based", "North-Carolina", "private-college", "state-grant", "renewable"],
    sourceId: "nc-need-based",
    sourceUrl: "https://www.ncseaa.edu/nc-financial-aid/nc-need-based-scholarship/",
  },
  {
    title: "Washington College Grant (WA College Grant)",
    provider: "Washington Student Achievement Council (WSAC)",
    description:
      "The Washington College Grant, formerly the State Need Grant, is Washington's primary need-based grant program providing up to $10,000 annually. It serves the state's lowest-income students attending eligible Washington State schools. There are no GPA requirements to apply, only financial need.",
    amount: "Up to $10,000",
    amountMin: 0,
    amountMax: 10000,
    deadline: new Date("2027-06-01"),
    url: "https://wsac.wa.gov/wacollege-grant",
    scholarshipType: "need-based",
    renewable: true,
    educationLevels: ["undergraduate", "vocational", "trade-school"],
    citizenshipRequired: "US Citizen or Permanent Resident",
    stateRestriction: "WA",
    eligibilityText: "Must be a Washington State resident with demonstrated financial need attending an eligible WA institution. No minimum GPA required.",
    essayRequired: false,
    submissionMethod: "portal",
    portalUrl: "https://wsac.wa.gov/wacollege-grant",
    tags: ["need-based", "Washington", "WA-College-Grant", "state-grant", "no-GPA", "renewable"],
    sourceId: "wa-college-grant",
    sourceUrl: "https://wsac.wa.gov/wacollege-grant",
  },
];
